#!/usr/bin/env python3
"""
    Copyright: SingerLinks Consulting LLC dba NodeEra Software 2018-2019 - all rights reserved
    Confidential Material - Do Not Distribute - SingerLinks Consulting dba NodeEra Software
"""
class Error(Exception):
    """Base class for exceptions in this module."""
    pass

class loadJobError(Error):
    """
    Exception raised during load job processing
    Attributes:
        logfile -- the logfile name and directory based on log directory commmand line parameter and file name generated by the program
        message -- explanation of the error
    """

    def __init__(self, message):
        self.message = message
        
class loggingsetupError(Error):
    """
    Exception raised when logging setup fails
    Attributes:
        logfile -- the logfile name and directory based on log directory commmand line parameter and file name generated by the program
        message -- explanation of the error
    """

    def __init__(self, logfile, message):
        self.logfile = logfile
        self.message = message
        
class inifileError(Error):
    """
    Exception raised when inifile processing fails
    Attributes:
        inifile -- name of the ini file specified on the command line.  
        message -- explanation of the error
    """

    def __init__(self, inifile, message):
        self.inifile = inifile
        self.message = message

class CSVFileError(Error):
    """
    Exception raised during processing of the CSV file parameters in the run file
    Attributes:  
        message -- explanation of the error
    """
    def __init__(self, message):
        self.message = message

class neo4jError(Error):
    """
    Exception raised during processing of neoCon methods.
    Attributes:  
        message -- explanation of the error
    """
    def __init__(self, message):
        self.message = message
