# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Jsing\OneDrive\Documents\DEV_LAPTOP_LOCAL_REPO\NODEERA\forms\CypherEditGridWidget.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_cypherEditGridWidget(object):
    def setupUi(self, cypherEditGridWidget):
        cypherEditGridWidget.setObjectName("cypherEditGridWidget")
        cypherEditGridWidget.resize(771, 660)
        self.horizontalLayout = QtWidgets.QHBoxLayout(cypherEditGridWidget)
        self.horizontalLayout.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frmEditnGrid = QtWidgets.QFrame(cypherEditGridWidget)
        self.frmEditnGrid.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frmEditnGrid.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frmEditnGrid.setLineWidth(0)
        self.frmEditnGrid.setObjectName("frmEditnGrid")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frmEditnGrid)
        self.verticalLayout.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(self.frmEditnGrid)
        self.splitter.setLineWidth(0)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.frmEdit = QtWidgets.QFrame(self.splitter)
        self.frmEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frmEdit.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frmEdit.setLineWidth(0)
        self.frmEdit.setObjectName("frmEdit")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frmEdit)
        self.verticalLayout_2.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frmEditorButton = QtWidgets.QFrame(self.frmEdit)
        self.frmEditorButton.setMinimumSize(QtCore.QSize(0, 40))
        self.frmEditorButton.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frmEditorButton.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frmEditorButton.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frmEditorButton.setLineWidth(0)
        self.frmEditorButton.setObjectName("frmEditorButton")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frmEditorButton)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnRun = QtWidgets.QToolButton(self.frmEditorButton)
        self.btnRun.setMinimumSize(QtCore.QSize(32, 32))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/RUN and DATA TAB/Run.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRun.setIcon(icon)
        self.btnRun.setIconSize(QtCore.QSize(32, 32))
        self.btnRun.setAutoRaise(False)
        self.btnRun.setObjectName("btnRun")
        self.horizontalLayout_2.addWidget(self.btnRun)
        self.btnRunScript = QtWidgets.QToolButton(self.frmEditorButton)
        self.btnRunScript.setMinimumSize(QtCore.QSize(32, 32))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/RUN and DATA TAB/RunScript.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRunScript.setIcon(icon1)
        self.btnRunScript.setIconSize(QtCore.QSize(32, 30))
        self.btnRunScript.setAutoRaise(True)
        self.btnRunScript.setObjectName("btnRunScript")
        self.horizontalLayout_2.addWidget(self.btnRunScript)
        self.cmbAutoCommit = QtWidgets.QComboBox(self.frmEditorButton)
        self.cmbAutoCommit.setMinimumSize(QtCore.QSize(121, 0))
        self.cmbAutoCommit.setMaximumSize(QtCore.QSize(121, 16777215))
        self.cmbAutoCommit.setObjectName("cmbAutoCommit")
        self.cmbAutoCommit.addItem("")
        self.cmbAutoCommit.addItem("")
        self.horizontalLayout_2.addWidget(self.cmbAutoCommit)
        self.btnCommit = QtWidgets.QToolButton(self.frmEditorButton)
        self.btnCommit.setMinimumSize(QtCore.QSize(32, 32))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/RUN and DATA TAB/Commit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCommit.setIcon(icon2)
        self.btnCommit.setIconSize(QtCore.QSize(32, 32))
        self.btnCommit.setAutoRaise(True)
        self.btnCommit.setObjectName("btnCommit")
        self.horizontalLayout_2.addWidget(self.btnCommit)
        self.btnRollBack = QtWidgets.QToolButton(self.frmEditorButton)
        self.btnRollBack.setMinimumSize(QtCore.QSize(32, 32))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/RUN and DATA TAB/RollBack.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRollBack.setIcon(icon3)
        self.btnRollBack.setIconSize(QtCore.QSize(32, 32))
        self.btnRollBack.setAutoRaise(True)
        self.btnRollBack.setObjectName("btnRollBack")
        self.horizontalLayout_2.addWidget(self.btnRollBack)
        spacerItem = QtWidgets.QSpacerItem(175, 19, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.frmEditorButton)
        self.frmData = QtWidgets.QFrame(self.splitter)
        self.frmData.setFrameShape(QtWidgets.QFrame.Box)
        self.frmData.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frmData.setObjectName("frmData")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frmData)
        self.verticalLayout_6.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_6.setSpacing(1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frmDataGrid = QtWidgets.QFrame(self.frmData)
        self.frmDataGrid.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frmDataGrid.setLineWidth(0)
        self.frmDataGrid.setObjectName("frmDataGrid")
        self.verticalLayout_6.addWidget(self.frmDataGrid)
        self.verticalLayout.addWidget(self.splitter)
        self.horizontalLayout.addWidget(self.frmEditnGrid)

        self.retranslateUi(cypherEditGridWidget)
        QtCore.QMetaObject.connectSlotsByName(cypherEditGridWidget)

    def retranslateUi(self, cypherEditGridWidget):
        _translate = QtCore.QCoreApplication.translate
        cypherEditGridWidget.setWindowTitle(_translate("cypherEditGridWidget", "Form"))
        self.btnRun.setToolTip(_translate("cypherEditGridWidget", "Run Query at cursor"))
        self.btnRun.setText(_translate("cypherEditGridWidget", "run"))
        self.btnRunScript.setToolTip(_translate("cypherEditGridWidget", "Run File as Script"))
        self.btnRunScript.setText(_translate("cypherEditGridWidget", "script"))
        self.cmbAutoCommit.setToolTip(_translate("cypherEditGridWidget", "How To Commit"))
        self.cmbAutoCommit.setItemText(0, _translate("cypherEditGridWidget", "Auto Commit On"))
        self.cmbAutoCommit.setItemText(1, _translate("cypherEditGridWidget", "Auto Commit Off"))
        self.btnCommit.setToolTip(_translate("cypherEditGridWidget", "Commit Current Transaction"))
        self.btnCommit.setText(_translate("cypherEditGridWidget", "Commit"))
        self.btnRollBack.setToolTip(_translate("cypherEditGridWidget", "RollBack Current Transaction"))
        self.btnRollBack.setText(_translate("cypherEditGridWidget", "RollBack"))

import icons.icons_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    cypherEditGridWidget = QtWidgets.QWidget()
    ui = Ui_cypherEditGridWidget()
    ui.setupUi(cypherEditGridWidget)
    cypherEditGridWidget.show()
    sys.exit(app.exec_())

