# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Jsing\OneDrive\Documents\DEV_LAPTOP_LOCAL_REPO\forms\ConstraintNodeKeyDlg.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ConstraintNodeKeyDlg(object):
    def setupUi(self, ConstraintNodeKeyDlg):
        ConstraintNodeKeyDlg.setObjectName("ConstraintNodeKeyDlg")
        ConstraintNodeKeyDlg.setWindowModality(QtCore.Qt.ApplicationModal)
        ConstraintNodeKeyDlg.resize(591, 408)
        ConstraintNodeKeyDlg.setSizeGripEnabled(True)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(ConstraintNodeKeyDlg)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(ConstraintNodeKeyDlg)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.frame = QtWidgets.QFrame(ConstraintNodeKeyDlg)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.cbLabel = QtWidgets.QComboBox(self.frame)
        self.cbLabel.setMinimumSize(QtCore.QSize(150, 0))
        self.cbLabel.setEditable(True)
        self.cbLabel.setObjectName("cbLabel")
        self.horizontalLayout.addWidget(self.cbLabel)
        spacerItem = QtWidgets.QSpacerItem(276, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_3.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(ConstraintNodeKeyDlg)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.cbProperty = QtWidgets.QComboBox(self.frame_6)
        self.cbProperty.setMinimumSize(QtCore.QSize(250, 0))
        self.cbProperty.setEditable(True)
        self.cbProperty.setObjectName("cbProperty")
        self.horizontalLayout_3.addWidget(self.cbProperty)
        self.pbAddToList = QtWidgets.QPushButton(self.frame_6)
        self.pbAddToList.setObjectName("pbAddToList")
        self.horizontalLayout_3.addWidget(self.pbAddToList)
        spacerItem1 = QtWidgets.QSpacerItem(76, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.frame_6)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2.addWidget(self.frame_3)
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lstProperty = QtWidgets.QListWidget(self.frame_5)
        self.lstProperty.setObjectName("lstProperty")
        self.horizontalLayout_2.addWidget(self.lstProperty)
        self.frame_4 = QtWidgets.QFrame(self.frame_5)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnMoveUp = QtWidgets.QPushButton(self.frame_4)
        self.btnMoveUp.setObjectName("btnMoveUp")
        self.verticalLayout.addWidget(self.btnMoveUp)
        self.btnMoveDown = QtWidgets.QPushButton(self.frame_4)
        self.btnMoveDown.setObjectName("btnMoveDown")
        self.verticalLayout.addWidget(self.btnMoveDown)
        self.pbRemoveList = QtWidgets.QPushButton(self.frame_4)
        self.pbRemoveList.setObjectName("pbRemoveList")
        self.verticalLayout.addWidget(self.pbRemoveList)
        spacerItem2 = QtWidgets.QSpacerItem(20, 101, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(ConstraintNodeKeyDlg)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)

        self.retranslateUi(ConstraintNodeKeyDlg)
        QtCore.QMetaObject.connectSlotsByName(ConstraintNodeKeyDlg)

    def retranslateUi(self, ConstraintNodeKeyDlg):
        _translate = QtCore.QCoreApplication.translate
        ConstraintNodeKeyDlg.setWindowTitle(_translate("ConstraintNodeKeyDlg", "Node Key Constraint"))
        self.label.setText(_translate("ConstraintNodeKeyDlg", "Create Node Key Constraint"))
        self.label_2.setText(_translate("ConstraintNodeKeyDlg", "Enter or Select a Label:"))
        self.label_3.setText(_translate("ConstraintNodeKeyDlg", "Enter or Select a Property:"))
        self.pbAddToList.setToolTip(_translate("ConstraintNodeKeyDlg", "<html><head/><body><p>Click to add this property to the list.</p></body></html>"))
        self.pbAddToList.setText(_translate("ConstraintNodeKeyDlg", "Add To List"))
        self.btnMoveUp.setText(_translate("ConstraintNodeKeyDlg", "Move Up"))
        self.btnMoveDown.setText(_translate("ConstraintNodeKeyDlg", "Move Down"))
        self.pbRemoveList.setToolTip(_translate("ConstraintNodeKeyDlg", "<html><head/><body><p>Select a property in the list and click to remove it.</p></body></html>"))
        self.pbRemoveList.setText(_translate("ConstraintNodeKeyDlg", "Remove From List"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ConstraintNodeKeyDlg = QtWidgets.QDialog()
    ui = Ui_ConstraintNodeKeyDlg()
    ui.setupUi(ConstraintNodeKeyDlg)
    ConstraintNodeKeyDlg.show()
    sys.exit(app.exec_())

