# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Jsing\OneDrive\Documents\DEV_LAPTOP_LOCAL_REPO\NODEERA\forms\CreateIndexDlg.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateIndexDlg(object):
    def setupUi(self, CreateIndexDlg):
        CreateIndexDlg.setObjectName("CreateIndexDlg")
        CreateIndexDlg.resize(619, 443)
        CreateIndexDlg.setSizeGripEnabled(True)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(CreateIndexDlg)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(CreateIndexDlg)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.frame = QtWidgets.QFrame(CreateIndexDlg)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.cbLabel = QtWidgets.QComboBox(self.frame)
        self.cbLabel.setMinimumSize(QtCore.QSize(150, 0))
        self.cbLabel.setEditable(True)
        self.cbLabel.setObjectName("cbLabel")
        self.horizontalLayout.addWidget(self.cbLabel)
        spacerItem = QtWidgets.QSpacerItem(276, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_6 = QtWidgets.QFrame(CreateIndexDlg)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.cbProperty = QtWidgets.QComboBox(self.frame_6)
        self.cbProperty.setMinimumSize(QtCore.QSize(250, 0))
        self.cbProperty.setEditable(True)
        self.cbProperty.setObjectName("cbProperty")
        self.horizontalLayout_3.addWidget(self.cbProperty)
        self.pbAddToList = QtWidgets.QPushButton(self.frame_6)
        self.pbAddToList.setObjectName("pbAddToList")
        self.horizontalLayout_3.addWidget(self.pbAddToList)
        spacerItem1 = QtWidgets.QSpacerItem(76, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.frame_6)
        self.frame_5 = QtWidgets.QFrame(CreateIndexDlg)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lstProperty = QtWidgets.QListWidget(self.frame_5)
        self.lstProperty.setObjectName("lstProperty")
        self.horizontalLayout_2.addWidget(self.lstProperty)
        self.frame_4 = QtWidgets.QFrame(self.frame_5)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnMoveUp = QtWidgets.QPushButton(self.frame_4)
        self.btnMoveUp.setObjectName("btnMoveUp")
        self.verticalLayout.addWidget(self.btnMoveUp)
        self.btnMoveDown = QtWidgets.QPushButton(self.frame_4)
        self.btnMoveDown.setObjectName("btnMoveDown")
        self.verticalLayout.addWidget(self.btnMoveDown)
        self.pbRemoveList = QtWidgets.QPushButton(self.frame_4)
        self.pbRemoveList.setObjectName("pbRemoveList")
        self.verticalLayout.addWidget(self.pbRemoveList)
        spacerItem2 = QtWidgets.QSpacerItem(20, 101, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.buttonBox = QtWidgets.QDialogButtonBox(CreateIndexDlg)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(CreateIndexDlg)
        QtCore.QMetaObject.connectSlotsByName(CreateIndexDlg)

    def retranslateUi(self, CreateIndexDlg):
        _translate = QtCore.QCoreApplication.translate
        CreateIndexDlg.setWindowTitle(_translate("CreateIndexDlg", "Create Index"))
        self.label.setText(_translate("CreateIndexDlg", "Create Index"))
        self.label_2.setText(_translate("CreateIndexDlg", "Enter or Select a Label:"))
        self.label_3.setText(_translate("CreateIndexDlg", "Enter or Select a Property:"))
        self.pbAddToList.setToolTip(_translate("CreateIndexDlg", "<html><head/><body><p>Click to add this property to the list.</p></body></html>"))
        self.pbAddToList.setText(_translate("CreateIndexDlg", "Add To List"))
        self.btnMoveUp.setText(_translate("CreateIndexDlg", "Move Up"))
        self.btnMoveDown.setText(_translate("CreateIndexDlg", "Move Down"))
        self.pbRemoveList.setToolTip(_translate("CreateIndexDlg", "<html><head/><body><p>Select a property in the list and click to remove it.</p></body></html>"))
        self.pbRemoveList.setText(_translate("CreateIndexDlg", "Remove From List"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CreateIndexDlg = QtWidgets.QDialog()
    ui = Ui_CreateIndexDlg()
    ui.setupUi(CreateIndexDlg)
    CreateIndexDlg.show()
    sys.exit(app.exec_())
