# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Jsing\OneDrive\Documents\DEV_LAPTOP_LOCAL_REPO\forms\cypherEditnGrid.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CypherEditnGrid(object):
    def setupUi(self, CypherEditnGrid):
        CypherEditnGrid.setObjectName("CypherEditnGrid")
        CypherEditnGrid.resize(771, 660)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(CypherEditnGrid)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frmEditnGrid = QtWidgets.QFrame(CypherEditnGrid)
        self.frmEditnGrid.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frmEditnGrid.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frmEditnGrid.setLineWidth(0)
        self.frmEditnGrid.setObjectName("frmEditnGrid")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frmEditnGrid)
        self.horizontalLayout_7.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_7.setSpacing(1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.splitter = QtWidgets.QSplitter(self.frmEditnGrid)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.frmEdit = QtWidgets.QFrame(self.splitter)
        self.frmEdit.setFrameShape(QtWidgets.QFrame.Box)
        self.frmEdit.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frmEdit.setObjectName("frmEdit")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frmEdit)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frmEditorButton = QtWidgets.QFrame(self.frmEdit)
        self.frmEditorButton.setMinimumSize(QtCore.QSize(0, 40))
        self.frmEditorButton.setMaximumSize(QtCore.QSize(16777215, 36))
        self.frmEditorButton.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frmEditorButton.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frmEditorButton.setObjectName("frmEditorButton")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frmEditorButton)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnRun = QtWidgets.QToolButton(self.frmEditorButton)
        self.btnRun.setMinimumSize(QtCore.QSize(32, 32))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/RUN and DATA TAB/Run.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRun.setIcon(icon)
        self.btnRun.setIconSize(QtCore.QSize(32, 32))
        self.btnRun.setAutoRaise(True)
        self.btnRun.setObjectName("btnRun")
        self.horizontalLayout.addWidget(self.btnRun)
        self.btnRunScript = QtWidgets.QToolButton(self.frmEditorButton)
        self.btnRunScript.setMinimumSize(QtCore.QSize(32, 32))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/RUN and DATA TAB/RunScript.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRunScript.setIcon(icon1)
        self.btnRunScript.setIconSize(QtCore.QSize(32, 30))
        self.btnRunScript.setAutoRaise(True)
        self.btnRunScript.setObjectName("btnRunScript")
        self.horizontalLayout.addWidget(self.btnRunScript)
        self.cmbAutoCommit = QtWidgets.QComboBox(self.frmEditorButton)
        self.cmbAutoCommit.setMinimumSize(QtCore.QSize(121, 0))
        self.cmbAutoCommit.setMaximumSize(QtCore.QSize(121, 16777215))
        self.cmbAutoCommit.setObjectName("cmbAutoCommit")
        self.cmbAutoCommit.addItem("")
        self.cmbAutoCommit.addItem("")
        self.horizontalLayout.addWidget(self.cmbAutoCommit)
        self.btnCommit = QtWidgets.QToolButton(self.frmEditorButton)
        self.btnCommit.setMinimumSize(QtCore.QSize(32, 32))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/RUN and DATA TAB/Commit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCommit.setIcon(icon2)
        self.btnCommit.setIconSize(QtCore.QSize(32, 32))
        self.btnCommit.setAutoRaise(True)
        self.btnCommit.setObjectName("btnCommit")
        self.horizontalLayout.addWidget(self.btnCommit)
        self.btnRollBack = QtWidgets.QToolButton(self.frmEditorButton)
        self.btnRollBack.setMinimumSize(QtCore.QSize(32, 32))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/RUN and DATA TAB/RollBack.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRollBack.setIcon(icon3)
        self.btnRollBack.setIconSize(QtCore.QSize(32, 32))
        self.btnRollBack.setAutoRaise(True)
        self.btnRollBack.setObjectName("btnRollBack")
        self.horizontalLayout.addWidget(self.btnRollBack)
        self.btnComment = QtWidgets.QToolButton(self.frmEditorButton)
        self.btnComment.setMinimumSize(QtCore.QSize(32, 32))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/FILE/FILE/comment.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnComment.setIcon(icon4)
        self.btnComment.setIconSize(QtCore.QSize(32, 32))
        self.btnComment.setAutoRaise(True)
        self.btnComment.setObjectName("btnComment")
        self.horizontalLayout.addWidget(self.btnComment)
        self.btnUncomment = QtWidgets.QToolButton(self.frmEditorButton)
        self.btnUncomment.setMinimumSize(QtCore.QSize(32, 32))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/FILE/FILE/nocomment.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnUncomment.setIcon(icon5)
        self.btnUncomment.setIconSize(QtCore.QSize(32, 32))
        self.btnUncomment.setAutoRaise(True)
        self.btnUncomment.setObjectName("btnUncomment")
        self.horizontalLayout.addWidget(self.btnUncomment)
        spacerItem = QtWidgets.QSpacerItem(175, 19, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.frmEditorButton)
        self.frmGrid = QtWidgets.QFrame(self.splitter)
        self.frmGrid.setFrameShape(QtWidgets.QFrame.Box)
        self.frmGrid.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frmGrid.setObjectName("frmGrid")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frmGrid)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tabWidget = QtWidgets.QTabWidget(self.frmGrid)
        self.tabWidget.setObjectName("tabWidget")
        self.tabData = QtWidgets.QWidget()
        self.tabData.setObjectName("tabData")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tabData)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame = QtWidgets.QFrame(self.tabData)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_4.setSpacing(1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frmGridButtons = QtWidgets.QFrame(self.frame)
        self.frmGridButtons.setMinimumSize(QtCore.QSize(0, 40))
        self.frmGridButtons.setMaximumSize(QtCore.QSize(16777215, 36))
        self.frmGridButtons.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frmGridButtons.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frmGridButtons.setObjectName("frmGridButtons")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frmGridButtons)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnExport = QtWidgets.QToolButton(self.frmGridButtons)
        self.btnExport.setMinimumSize(QtCore.QSize(32, 32))
        self.btnExport.setMaximumSize(QtCore.QSize(32, 32))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/RUN and DATA TAB/Export.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnExport.setIcon(icon6)
        self.btnExport.setIconSize(QtCore.QSize(32, 32))
        self.btnExport.setAutoRaise(True)
        self.btnExport.setObjectName("btnExport")
        self.horizontalLayout_3.addWidget(self.btnExport)
        self.btnBegin = QtWidgets.QToolButton(self.frmGridButtons)
        self.btnBegin.setMinimumSize(QtCore.QSize(32, 32))
        self.btnBegin.setMaximumSize(QtCore.QSize(32, 32))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/RUN and DATA TAB/GridStart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBegin.setIcon(icon7)
        self.btnBegin.setIconSize(QtCore.QSize(32, 32))
        self.btnBegin.setAutoRaise(True)
        self.btnBegin.setObjectName("btnBegin")
        self.horizontalLayout_3.addWidget(self.btnBegin)
        self.btnBack = QtWidgets.QToolButton(self.frmGridButtons)
        self.btnBack.setMinimumSize(QtCore.QSize(32, 32))
        self.btnBack.setMaximumSize(QtCore.QSize(32, 32))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/RUN and DATA TAB/GridBack.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBack.setIcon(icon8)
        self.btnBack.setIconSize(QtCore.QSize(32, 32))
        self.btnBack.setAutoRaise(True)
        self.btnBack.setObjectName("btnBack")
        self.horizontalLayout_3.addWidget(self.btnBack)
        self.btnForward = QtWidgets.QToolButton(self.frmGridButtons)
        self.btnForward.setMinimumSize(QtCore.QSize(32, 32))
        self.btnForward.setMaximumSize(QtCore.QSize(32, 32))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/RUN and DATA TAB/GridForward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnForward.setIcon(icon9)
        self.btnForward.setIconSize(QtCore.QSize(32, 32))
        self.btnForward.setAutoRaise(True)
        self.btnForward.setObjectName("btnForward")
        self.horizontalLayout_3.addWidget(self.btnForward)
        self.btnEnd = QtWidgets.QToolButton(self.frmGridButtons)
        self.btnEnd.setMinimumSize(QtCore.QSize(32, 32))
        self.btnEnd.setMaximumSize(QtCore.QSize(32, 32))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/RUN and DATA TAB/GridEnd.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnEnd.setIcon(icon10)
        self.btnEnd.setIconSize(QtCore.QSize(32, 32))
        self.btnEnd.setAutoRaise(True)
        self.btnEnd.setObjectName("btnEnd")
        self.horizontalLayout_3.addWidget(self.btnEnd)
        spacerItem1 = QtWidgets.QSpacerItem(494, 19, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_4.addWidget(self.frmGridButtons)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tblCypherData = QtWidgets.QTableView(self.frame_2)
        self.tblCypherData.setObjectName("tblCypherData")
        self.verticalLayout.addWidget(self.tblCypherData)
        self.txtPosition = QtWidgets.QLineEdit(self.frame_2)
        self.txtPosition.setObjectName("txtPosition")
        self.verticalLayout.addWidget(self.txtPosition)
        self.verticalLayout_4.addWidget(self.frame_2)
        self.verticalLayout_5.addWidget(self.frame)
        self.tabWidget.addTab(self.tabData, "")
        self.tabLog = QtWidgets.QWidget()
        self.tabLog.setObjectName("tabLog")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.tabLog)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_4 = QtWidgets.QFrame(self.tabLog)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_4.setSpacing(1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLog = QtWidgets.QTableView(self.frame_4)
        self.gridLog.setObjectName("gridLog")
        self.horizontalLayout_4.addWidget(self.gridLog)
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btnExportLog = QtWidgets.QPushButton(self.frame_5)
        self.btnExportLog.setObjectName("btnExportLog")
        self.verticalLayout_3.addWidget(self.btnExportLog)
        self.btnClearLog = QtWidgets.QPushButton(self.frame_5)
        self.btnClearLog.setObjectName("btnClearLog")
        self.verticalLayout_3.addWidget(self.btnClearLog)
        spacerItem2 = QtWidgets.QSpacerItem(20, 210, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_4.addWidget(self.frame_5)
        self.horizontalLayout_6.addWidget(self.frame_4)
        self.tabWidget.addTab(self.tabLog, "")
        self.tabTrace = QtWidgets.QWidget()
        self.tabTrace.setObjectName("tabTrace")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tabTrace)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_6 = QtWidgets.QFrame(self.tabTrace)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_5.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_5.setSpacing(1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.textTrace = QtWidgets.QTextBrowser(self.frame_6)
        self.textTrace.setObjectName("textTrace")
        self.horizontalLayout_5.addWidget(self.textTrace)
        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.btnExportTrace = QtWidgets.QPushButton(self.frame_7)
        self.btnExportTrace.setObjectName("btnExportTrace")
        self.verticalLayout_8.addWidget(self.btnExportTrace)
        self.btnClearTrace = QtWidgets.QPushButton(self.frame_7)
        self.btnClearTrace.setObjectName("btnClearTrace")
        self.verticalLayout_8.addWidget(self.btnClearTrace)
        spacerItem3 = QtWidgets.QSpacerItem(20, 164, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem3)
        self.horizontalLayout_5.addWidget(self.frame_7)
        self.horizontalLayout_2.addWidget(self.frame_6)
        self.tabWidget.addTab(self.tabTrace, "")
        self.verticalLayout_6.addWidget(self.tabWidget)
        self.horizontalLayout_7.addWidget(self.splitter)
        self.verticalLayout_7.addWidget(self.frmEditnGrid)

        self.retranslateUi(CypherEditnGrid)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(CypherEditnGrid)

    def retranslateUi(self, CypherEditnGrid):
        _translate = QtCore.QCoreApplication.translate
        CypherEditnGrid.setWindowTitle(_translate("CypherEditnGrid", "Form"))
        self.btnRun.setToolTip(_translate("CypherEditnGrid", "Run Query at cursor"))
        self.btnRun.setText(_translate("CypherEditnGrid", "run"))
        self.btnRunScript.setToolTip(_translate("CypherEditnGrid", "Run File as Script"))
        self.btnRunScript.setText(_translate("CypherEditnGrid", "script"))
        self.cmbAutoCommit.setToolTip(_translate("CypherEditnGrid", "How To Commit"))
        self.cmbAutoCommit.setItemText(0, _translate("CypherEditnGrid", "Auto Commit On"))
        self.cmbAutoCommit.setItemText(1, _translate("CypherEditnGrid", "Auto Commit Off"))
        self.btnCommit.setToolTip(_translate("CypherEditnGrid", "Commit Current Transaction"))
        self.btnCommit.setText(_translate("CypherEditnGrid", "Commit"))
        self.btnRollBack.setToolTip(_translate("CypherEditnGrid", "RollBack Current Transaction"))
        self.btnRollBack.setText(_translate("CypherEditnGrid", "RollBack"))
        self.btnComment.setToolTip(_translate("CypherEditnGrid", "comment the line(s)"))
        self.btnComment.setText(_translate("CypherEditnGrid", "Comment"))
        self.btnUncomment.setToolTip(_translate("CypherEditnGrid", "Uncomment the line(s)"))
        self.btnUncomment.setText(_translate("CypherEditnGrid", "uncomment"))
        self.btnExport.setToolTip(_translate("CypherEditnGrid", "Export results"))
        self.btnExport.setText(_translate("CypherEditnGrid", "Export"))
        self.btnBegin.setToolTip(_translate("CypherEditnGrid", "Go to beginning of result set"))
        self.btnBegin.setText(_translate("CypherEditnGrid", "<<"))
        self.btnBack.setToolTip(_translate("CypherEditnGrid", "Move back"))
        self.btnBack.setText(_translate("CypherEditnGrid", "<"))
        self.btnForward.setToolTip(_translate("CypherEditnGrid", "Move forward"))
        self.btnForward.setText(_translate("CypherEditnGrid", ">"))
        self.btnEnd.setToolTip(_translate("CypherEditnGrid", "Go to the end of the result set"))
        self.btnEnd.setText(_translate("CypherEditnGrid", ">>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabData), _translate("CypherEditnGrid", "Data"))
        self.btnExportLog.setText(_translate("CypherEditnGrid", "Export..."))
        self.btnClearLog.setText(_translate("CypherEditnGrid", "Clear Log"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLog), _translate("CypherEditnGrid", "Log"))
        self.btnExportTrace.setText(_translate("CypherEditnGrid", "Export..."))
        self.btnClearTrace.setText(_translate("CypherEditnGrid", "Clear Trace"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTrace), _translate("CypherEditnGrid", "Trace"))

import icons.icons_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CypherEditnGrid = QtWidgets.QWidget()
    ui = Ui_CypherEditnGrid()
    ui.setupUi(CypherEditnGrid)
    CypherEditnGrid.show()
    sys.exit(app.exec_())

