# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Jsing\OneDrive\Documents\DEV_LAPTOP_LOCAL_REPO\NODEERA\forms\CopyNodeToDiagramDlg.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CopyNodeToDiagramDlg(object):
    def setupUi(self, CopyNodeToDiagramDlg):
        CopyNodeToDiagramDlg.setObjectName("CopyNodeToDiagramDlg")
        CopyNodeToDiagramDlg.resize(1140, 599)
        CopyNodeToDiagramDlg.setSizeGripEnabled(True)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(CopyNodeToDiagramDlg)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtWidgets.QFrame(CopyNodeToDiagramDlg)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(1, -1, 1, -1)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout.setContentsMargins(-1, 1, -1, 1)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.txtDiagramName = QtWidgets.QLineEdit(self.frame_4)
        self.txtDiagramName.setReadOnly(True)
        self.txtDiagramName.setObjectName("txtDiagramName")
        self.gridLayout.addWidget(self.txtDiagramName, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.txtNeoCon = QtWidgets.QLineEdit(self.frame_4)
        self.txtNeoCon.setReadOnly(True)
        self.txtNeoCon.setObjectName("txtNeoCon")
        self.gridLayout.addWidget(self.txtNeoCon, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(475, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setContentsMargins(9, 9, 1, 1)
        self.gridLayout_3.setSpacing(1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabGrids = QtWidgets.QTabWidget(self.groupBox)
        self.tabGrids.setObjectName("tabGrids")
        self.tabNodeEraNodes = QtWidgets.QWidget()
        self.tabNodeEraNodes.setObjectName("tabNodeEraNodes")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tabNodeEraNodes)
        self.gridLayout_2.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_2.setSpacing(1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.tabNodeEraNodes)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_2.setSpacing(1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.rbAllNodes = QtWidgets.QRadioButton(self.frame_2)
        self.rbAllNodes.setObjectName("rbAllNodes")
        self.horizontalLayout_2.addWidget(self.rbAllNodes)
        self.rbFilterTemplate = QtWidgets.QRadioButton(self.frame_2)
        self.rbFilterTemplate.setObjectName("rbFilterTemplate")
        self.horizontalLayout_2.addWidget(self.rbFilterTemplate)
        self.cboNodeTemplates = QtWidgets.QComboBox(self.frame_2)
        self.cboNodeTemplates.setMinimumSize(QtCore.QSize(225, 0))
        self.cboNodeTemplates.setObjectName("cboNodeTemplates")
        self.horizontalLayout_2.addWidget(self.cboNodeTemplates)
        spacerItem2 = QtWidgets.QSpacerItem(550, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frmDataGrid = QtWidgets.QFrame(self.frame_6)
        self.frmDataGrid.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmDataGrid.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmDataGrid.setObjectName("frmDataGrid")
        self.horizontalLayout.addWidget(self.frmDataGrid)
        self.frame_5 = QtWidgets.QFrame(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnAdd = QtWidgets.QPushButton(self.frame_5)
        self.btnAdd.setObjectName("btnAdd")
        self.verticalLayout.addWidget(self.btnAdd)
        spacerItem3 = QtWidgets.QSpacerItem(20, 330, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout.addWidget(self.frame_5)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.gridLayout_2.addWidget(self.frame_3, 0, 0, 1, 1)
        self.tabGrids.addTab(self.tabNodeEraNodes, "")
        self.gridLayout_3.addWidget(self.tabGrids, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.verticalLayout_4.addWidget(self.frame)
        self.buttonBox = QtWidgets.QDialogButtonBox(CopyNodeToDiagramDlg)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_4.addWidget(self.buttonBox)
        self.label.setBuddy(self.txtDiagramName)
        self.label_2.setBuddy(self.txtNeoCon)

        self.retranslateUi(CopyNodeToDiagramDlg)
        self.tabGrids.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(CopyNodeToDiagramDlg)

    def retranslateUi(self, CopyNodeToDiagramDlg):
        _translate = QtCore.QCoreApplication.translate
        CopyNodeToDiagramDlg.setWindowTitle(_translate("CopyNodeToDiagramDlg", "Copy Nodes To Diagram"))
        self.label.setText(_translate("CopyNodeToDiagramDlg", "Diagram Name:"))
        self.label_2.setText(_translate("CopyNodeToDiagramDlg", "Neo4j Connection:"))
        self.groupBox.setTitle(_translate("CopyNodeToDiagramDlg", "Select the Node(s) you want and click Add Nodes"))
        self.rbAllNodes.setText(_translate("CopyNodeToDiagramDlg", "All Nodes (limit 10,000)"))
        self.rbFilterTemplate.setText(_translate("CopyNodeToDiagramDlg", "Filter On Node Template"))
        self.btnAdd.setText(_translate("CopyNodeToDiagramDlg", "Add Nodes"))
        self.tabGrids.setTabText(self.tabGrids.indexOf(self.tabNodeEraNodes), _translate("CopyNodeToDiagramDlg", "Instance Nodes in this database"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CopyNodeToDiagramDlg = QtWidgets.QDialog()
    ui = Ui_CopyNodeToDiagramDlg()
    ui.setupUi(CopyNodeToDiagramDlg)
    CopyNodeToDiagramDlg.show()
    sys.exit(app.exec_())
