# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Jsing\OneDrive\Documents\DEV_LAPTOP_LOCAL_REPO\forms\dataSourceTab.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DataSourceTab(object):
    def setupUi(self, DataSourceTab):
        DataSourceTab.setObjectName("DataSourceTab")
        DataSourceTab.resize(783, 574)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(DataSourceTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frmHeader = QtWidgets.QFrame(DataSourceTab)
        self.frmHeader.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frmHeader.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frmHeader.setObjectName("frmHeader")
        self.formLayout = QtWidgets.QFormLayout(self.frmHeader)
        self.formLayout.setObjectName("formLayout")
        self.lblName = QtWidgets.QLabel(self.frmHeader)
        self.lblName.setObjectName("lblName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblName)
        self.txtName = QtWidgets.QLineEdit(self.frmHeader)
        self.txtName.setReadOnly(True)
        self.txtName.setObjectName("txtName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtName)
        self.lblDesc = QtWidgets.QLabel(self.frmHeader)
        self.lblDesc.setObjectName("lblDesc")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblDesc)
        self.txtDesc = QtWidgets.QLineEdit(self.frmHeader)
        self.txtDesc.setReadOnly(True)
        self.txtDesc.setObjectName("txtDesc")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtDesc)
        self.verticalLayout_2.addWidget(self.frmHeader)
        self.frameBody = QtWidgets.QFrame(DataSourceTab)
        self.frameBody.setFrameShape(QtWidgets.QFrame.Box)
        self.frameBody.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameBody.setObjectName("frameBody")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frameBody)
        self.verticalLayout.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.frameBody)
        self.tabWidget.setObjectName("tabWidget")
        self.tabDataSource = QtWidgets.QWidget()
        self.tabDataSource.setObjectName("tabDataSource")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tabDataSource)
        self.verticalLayout_5.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_5.setSpacing(1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame = QtWidgets.QFrame(self.tabDataSource)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.cmbDataSourceType = QtWidgets.QComboBox(self.frame)
        self.cmbDataSourceType.setObjectName("cmbDataSourceType")
        self.cmbDataSourceType.addItem("")
        self.cmbDataSourceType.addItem("")
        self.cmbDataSourceType.addItem("")
        self.cmbDataSourceType.addItem("")
        self.horizontalLayout.addWidget(self.cmbDataSourceType)
        spacerItem = QtWidgets.QSpacerItem(501, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_5.addWidget(self.frame)
        self.stackedWidget = QtWidgets.QStackedWidget(self.tabDataSource)
        self.stackedWidget.setObjectName("stackedWidget")
        self.pageNotSelected = QtWidgets.QWidget()
        self.pageNotSelected.setObjectName("pageNotSelected")
        self.label_2 = QtWidgets.QLabel(self.pageNotSelected)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 401, 20))
        self.label_2.setObjectName("label_2")
        self.stackedWidget.addWidget(self.pageNotSelected)
        self.pageCSV = QtWidgets.QWidget()
        self.pageCSV.setObjectName("pageCSV")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.pageCSV)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frmFile = QtWidgets.QFrame(self.pageCSV)
        self.frmFile.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmFile.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmFile.setObjectName("frmFile")
        self.gridLayout = QtWidgets.QGridLayout(self.frmFile)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.frmFile)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.txtFileName = QtWidgets.QLineEdit(self.frmFile)
        self.txtFileName.setMinimumSize(QtCore.QSize(231, 0))
        self.txtFileName.setReadOnly(True)
        self.txtFileName.setObjectName("txtFileName")
        self.gridLayout.addWidget(self.txtFileName, 0, 1, 1, 3)
        self.btnOpenFile = QtWidgets.QPushButton(self.frmFile)
        self.btnOpenFile.setObjectName("btnOpenFile")
        self.gridLayout.addWidget(self.btnOpenFile, 0, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 5, 1, 1)
        self.chkHasHeader = QtWidgets.QCheckBox(self.frmFile)
        self.chkHasHeader.setObjectName("chkHasHeader")
        self.gridLayout.addWidget(self.chkHasHeader, 1, 0, 1, 3)
        self.label_6 = QtWidgets.QLabel(self.frmFile)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.cmbDelimiter = QtWidgets.QComboBox(self.frmFile)
        self.cmbDelimiter.setEditable(True)
        self.cmbDelimiter.setObjectName("cmbDelimiter")
        self.cmbDelimiter.addItem("")
        self.cmbDelimiter.addItem("")
        self.cmbDelimiter.addItem("")
        self.cmbDelimiter.addItem("")
        self.gridLayout.addWidget(self.cmbDelimiter, 2, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frmFile)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 2)
        self.cmbQuoteChar = QtWidgets.QComboBox(self.frmFile)
        self.cmbQuoteChar.setEditable(True)
        self.cmbQuoteChar.setObjectName("cmbQuoteChar")
        self.cmbQuoteChar.addItem("")
        self.cmbQuoteChar.addItem("")
        self.gridLayout.addWidget(self.cmbQuoteChar, 3, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 3, 3, 1, 1)
        self.verticalLayout_6.addWidget(self.frmFile)
        self.frame_2 = QtWidgets.QFrame(self.pageCSV)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_4.setSpacing(1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.chkPreviewLimit = QtWidgets.QCheckBox(self.frame_3)
        self.chkPreviewLimit.setObjectName("chkPreviewLimit")
        self.horizontalLayout_2.addWidget(self.chkPreviewLimit)
        self.spinPreviewLimit = QtWidgets.QSpinBox(self.frame_3)
        self.spinPreviewLimit.setMinimumSize(QtCore.QSize(60, 0))
        self.spinPreviewLimit.setMinimum(1)
        self.spinPreviewLimit.setMaximum(10000000)
        self.spinPreviewLimit.setProperty("value", 1000)
        self.spinPreviewLimit.setObjectName("spinPreviewLimit")
        self.horizontalLayout_2.addWidget(self.spinPreviewLimit)
        spacerItem4 = QtWidgets.QSpacerItem(396, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.btnRefreshPreview = QtWidgets.QPushButton(self.frame_3)
        self.btnRefreshPreview.setObjectName("btnRefreshPreview")
        self.horizontalLayout_2.addWidget(self.btnRefreshPreview)
        self.verticalLayout_4.addWidget(self.frame_3)
        self.frmPreview = QtWidgets.QFrame(self.frame_2)
        self.frmPreview.setFrameShape(QtWidgets.QFrame.Box)
        self.frmPreview.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frmPreview.setObjectName("frmPreview")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frmPreview)
        self.verticalLayout_3.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_3.setSpacing(1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tblFilePreview = QtWidgets.QTableView(self.frmPreview)
        self.tblFilePreview.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tblFilePreview.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tblFilePreview.setObjectName("tblFilePreview")
        self.verticalLayout_3.addWidget(self.tblFilePreview)
        self.verticalLayout_4.addWidget(self.frmPreview)
        self.verticalLayout_6.addWidget(self.frame_2)
        self.stackedWidget.addWidget(self.pageCSV)
        self.pageODBC = QtWidgets.QWidget()
        self.pageODBC.setObjectName("pageODBC")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.pageODBC)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_6 = QtWidgets.QFrame(self.pageODBC)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_8 = QtWidgets.QLabel(self.frame_6)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 1)
        self.cmbODBCDataSource = QtWidgets.QComboBox(self.frame_6)
        self.cmbODBCDataSource.setObjectName("cmbODBCDataSource")
        self.gridLayout_2.addWidget(self.cmbODBCDataSource, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_6)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.txtSQLFileName = QtWidgets.QLineEdit(self.frame_6)
        self.txtSQLFileName.setMinimumSize(QtCore.QSize(231, 0))
        self.txtSQLFileName.setReadOnly(True)
        self.txtSQLFileName.setObjectName("txtSQLFileName")
        self.gridLayout_2.addWidget(self.txtSQLFileName, 1, 1, 1, 1)
        self.btnOpenSQL = QtWidgets.QPushButton(self.frame_6)
        self.btnOpenSQL.setObjectName("btnOpenSQL")
        self.gridLayout_2.addWidget(self.btnOpenSQL, 1, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(254, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 1, 3, 1, 1)
        self.verticalLayout_9.addWidget(self.frame_6)
        self.frame_4 = QtWidgets.QFrame(self.pageODBC)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_7.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_7.setSpacing(1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.chkPreviewLimit_ODBC = QtWidgets.QCheckBox(self.frame_5)
        self.chkPreviewLimit_ODBC.setObjectName("chkPreviewLimit_ODBC")
        self.horizontalLayout_3.addWidget(self.chkPreviewLimit_ODBC)
        self.spinPreviewLimit_ODBC = QtWidgets.QSpinBox(self.frame_5)
        self.spinPreviewLimit_ODBC.setMinimumSize(QtCore.QSize(60, 0))
        self.spinPreviewLimit_ODBC.setMinimum(1)
        self.spinPreviewLimit_ODBC.setMaximum(10000000)
        self.spinPreviewLimit_ODBC.setProperty("value", 1000)
        self.spinPreviewLimit_ODBC.setObjectName("spinPreviewLimit_ODBC")
        self.horizontalLayout_3.addWidget(self.spinPreviewLimit_ODBC)
        spacerItem6 = QtWidgets.QSpacerItem(396, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.btnRefreshPreview_ODBC = QtWidgets.QPushButton(self.frame_5)
        self.btnRefreshPreview_ODBC.setObjectName("btnRefreshPreview_ODBC")
        self.horizontalLayout_3.addWidget(self.btnRefreshPreview_ODBC)
        self.verticalLayout_7.addWidget(self.frame_5)
        self.frmPreview_2 = QtWidgets.QFrame(self.frame_4)
        self.frmPreview_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frmPreview_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frmPreview_2.setObjectName("frmPreview_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frmPreview_2)
        self.verticalLayout_8.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_8.setSpacing(1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tblFilePreview_ODBC = QtWidgets.QTableView(self.frmPreview_2)
        self.tblFilePreview_ODBC.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tblFilePreview_ODBC.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tblFilePreview_ODBC.setObjectName("tblFilePreview_ODBC")
        self.verticalLayout_8.addWidget(self.tblFilePreview_ODBC)
        self.verticalLayout_7.addWidget(self.frmPreview_2)
        self.verticalLayout_9.addWidget(self.frame_4)
        self.stackedWidget.addWidget(self.pageODBC)
        self.pageNeo4j = QtWidgets.QWidget()
        self.pageNeo4j.setObjectName("pageNeo4j")
        self.label_5 = QtWidgets.QLabel(self.pageNeo4j)
        self.label_5.setGeometry(QtCore.QRect(120, 10, 101, 16))
        self.label_5.setObjectName("label_5")
        self.stackedWidget.addWidget(self.pageNeo4j)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.tabWidget.addTab(self.tabDataSource, "")
        self.tabDescription = QtWidgets.QWidget()
        self.tabDescription.setObjectName("tabDescription")
        self.tabWidget.addTab(self.tabDescription, "")
        self.tabWhereUsed = QtWidgets.QWidget()
        self.tabWhereUsed.setObjectName("tabWhereUsed")
        self.tabWidget.addTab(self.tabWhereUsed, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.verticalLayout_2.addWidget(self.frameBody)
        self.label.setBuddy(self.cmbDataSourceType)
        self.label_3.setBuddy(self.txtFileName)
        self.label_6.setBuddy(self.cmbDelimiter)
        self.label_7.setBuddy(self.cmbQuoteChar)
        self.label_8.setBuddy(self.txtFileName)
        self.label_4.setBuddy(self.txtFileName)

        self.retranslateUi(DataSourceTab)
        self.tabWidget.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DataSourceTab)

    def retranslateUi(self, DataSourceTab):
        _translate = QtCore.QCoreApplication.translate
        DataSourceTab.setWindowTitle(_translate("DataSourceTab", "Form"))
        self.lblName.setText(_translate("DataSourceTab", "Name:"))
        self.lblDesc.setText(_translate("DataSourceTab", "Description:"))
        self.label.setText(_translate("DataSourceTab", "Data Source Type:"))
        self.cmbDataSourceType.setItemText(0, _translate("DataSourceTab", "Not Selected"))
        self.cmbDataSourceType.setItemText(1, _translate("DataSourceTab", "CSV"))
        self.cmbDataSourceType.setItemText(2, _translate("DataSourceTab", "ODBC"))
        self.cmbDataSourceType.setItemText(3, _translate("DataSourceTab", "NEO4J"))
        self.label_2.setText(_translate("DataSourceTab", "Select a Data Source Type Above"))
        self.label_3.setText(_translate("DataSourceTab", "File Name:"))
        self.btnOpenFile.setText(_translate("DataSourceTab", "Open CSV File"))
        self.chkHasHeader.setText(_translate("DataSourceTab", "Header has column names"))
        self.label_6.setText(_translate("DataSourceTab", "Delimiter:"))
        self.cmbDelimiter.setItemText(0, _translate("DataSourceTab", ","))
        self.cmbDelimiter.setItemText(1, _translate("DataSourceTab", "/"))
        self.cmbDelimiter.setItemText(2, _translate("DataSourceTab", "#"))
        self.cmbDelimiter.setItemText(3, _translate("DataSourceTab", "|"))
        self.label_7.setText(_translate("DataSourceTab", "Quote Character:"))
        self.cmbQuoteChar.setItemText(0, _translate("DataSourceTab", "\'"))
        self.cmbQuoteChar.setItemText(1, _translate("DataSourceTab", "\""))
        self.chkPreviewLimit.setText(_translate("DataSourceTab", "Limit Preview Records: "))
        self.btnRefreshPreview.setText(_translate("DataSourceTab", "Refresh Preview"))
        self.label_8.setText(_translate("DataSourceTab", "ODBC Data Source:"))
        self.label_4.setText(_translate("DataSourceTab", "SQL Query File:"))
        self.txtSQLFileName.setText(_translate("DataSourceTab", "SQL Query"))
        self.btnOpenSQL.setText(_translate("DataSourceTab", "Select Query File"))
        self.chkPreviewLimit_ODBC.setText(_translate("DataSourceTab", "Limit Preview Records: "))
        self.btnRefreshPreview_ODBC.setText(_translate("DataSourceTab", "Refresh Preview"))
        self.label_5.setText(_translate("DataSourceTab", "Neo4j future release"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDataSource), _translate("DataSourceTab", "Data Source"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDescription), _translate("DataSourceTab", "Description"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWhereUsed), _translate("DataSourceTab", "Where Used"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DataSourceTab = QtWidgets.QWidget()
    ui = Ui_DataSourceTab()
    ui.setupUi(DataSourceTab)
    DataSourceTab.show()
    sys.exit(app.exec_())

