# -*- coding: utf-8 -*-
'''Data Grid UI Generated class'''
# Form implementation generated from reading ui file 'C:\Users\John\Documents\NODEERA\V1\forms\DataGridDlg.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dlgDataGrid(object):
    '''Data Grid UI
    Display a grid with column and row headers.  This is used to show result sets from Neo4j
    Display a set of buttons to manipulate the data in the grid.'''
    def setupUi(self, dlgDataGrid):
        dlgDataGrid.setObjectName("dlgDataGrid")
        dlgDataGrid.resize(636, 456)
        dlgDataGrid.setSizeGripEnabled(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(dlgDataGrid)
        self.verticalLayout.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frmOutput = QtWidgets.QFrame(dlgDataGrid)
        self.frmOutput.setFrameShape(QtWidgets.QFrame.Box)
        self.frmOutput.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frmOutput.setObjectName("frmOutput")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frmOutput)
        self.verticalLayout_3.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_3.setSpacing(1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.frmOutput)
        self.tabWidget.setObjectName("tabWidget")
        self.tabDataGrid = QtWidgets.QWidget()
        self.tabDataGrid.setObjectName("tabDataGrid")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tabDataGrid)
        self.verticalLayout_5.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_5.setSpacing(1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frmDataGrid = QtWidgets.QFrame(self.tabDataGrid)
        self.frmDataGrid.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frmDataGrid.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frmDataGrid.setObjectName("frmDataGrid")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frmDataGrid)
        self.verticalLayout_4.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_4.setSpacing(1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtWidgets.QFrame(self.frmDataGrid)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_3.setSpacing(1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnExport = QtWidgets.QToolButton(self.frame)
        self.btnExport.setObjectName("btnExport")
        self.horizontalLayout_3.addWidget(self.btnExport)
        self.btnTop = QtWidgets.QToolButton(self.frame)
        self.btnTop.setObjectName("btnTop")
        self.horizontalLayout_3.addWidget(self.btnTop)
        self.btnBack = QtWidgets.QToolButton(self.frame)
        self.btnBack.setObjectName("btnBack")
        self.horizontalLayout_3.addWidget(self.btnBack)
        self.btnForward = QtWidgets.QToolButton(self.frame)
        self.btnForward.setObjectName("btnForward")
        self.horizontalLayout_3.addWidget(self.btnForward)
        self.btnBottom = QtWidgets.QToolButton(self.frame)
        self.btnBottom.setObjectName("btnBottom")
        self.horizontalLayout_3.addWidget(self.btnBottom)
        spacerItem = QtWidgets.QSpacerItem(320, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_4.addWidget(self.frame)
        self.tblCypherData = QtWidgets.QTableView(self.frmDataGrid)
        self.tblCypherData.setObjectName("tblCypherData")
        self.verticalLayout_4.addWidget(self.tblCypherData)
        self.frame_3 = QtWidgets.QFrame(self.frmDataGrid)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.txtPosition = QtWidgets.QLineEdit(self.frame_3)
        self.txtPosition.setFrame(False)
        self.txtPosition.setReadOnly(True)
        self.txtPosition.setObjectName("txtPosition")
        self.verticalLayout_2.addWidget(self.txtPosition)
        self.verticalLayout_4.addWidget(self.frame_3)
        self.verticalLayout_5.addWidget(self.frmDataGrid)
        self.tabWidget.addTab(self.tabDataGrid, "")
        self.tabOutput = QtWidgets.QWidget()
        self.tabOutput.setObjectName("tabOutput")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tabOutput)
        self.horizontalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_2.setSpacing(1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.txtCypherOutput = QtWidgets.QTextBrowser(self.tabOutput)
        self.txtCypherOutput.setFrameShape(QtWidgets.QFrame.Box)
        self.txtCypherOutput.setFrameShadow(QtWidgets.QFrame.Plain)
        self.txtCypherOutput.setObjectName("txtCypherOutput")
        self.horizontalLayout_2.addWidget(self.txtCypherOutput)
        self.tabWidget.addTab(self.tabOutput, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.verticalLayout.addWidget(self.frmOutput)
        self.btnFrame = QtWidgets.QFrame(dlgDataGrid)
        self.btnFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.btnFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.btnFrame.setObjectName("btnFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.btnFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(261, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btnClose = QtWidgets.QPushButton(self.btnFrame)
        self.btnClose.setObjectName("btnClose")
        self.horizontalLayout.addWidget(self.btnClose)
        spacerItem2 = QtWidgets.QSpacerItem(260, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.btnFrame)

        self.retranslateUi(dlgDataGrid)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(dlgDataGrid)

    def retranslateUi(self, dlgDataGrid):
        _translate = QtCore.QCoreApplication.translate
        dlgDataGrid.setWindowTitle(_translate("dlgDataGrid", "Data Grid"))
        self.btnExport.setToolTip(_translate("dlgDataGrid", "Export the data as a CSV File"))
        self.btnExport.setText(_translate("dlgDataGrid", "Export"))
        self.btnTop.setToolTip(_translate("dlgDataGrid", "Move to the first row in the result set."))
        self.btnTop.setText(_translate("dlgDataGrid", "<<"))
        self.btnBack.setToolTip(_translate("dlgDataGrid", "Move back X rows in result set."))
        self.btnBack.setText(_translate("dlgDataGrid", "< "))
        self.btnForward.setToolTip(_translate("dlgDataGrid", "Move forward X rows in result set."))
        self.btnForward.setText(_translate("dlgDataGrid", " >"))
        self.btnBottom.setToolTip(_translate("dlgDataGrid", "Move to the end of the result set."))
        self.btnBottom.setText(_translate("dlgDataGrid", ">>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDataGrid), _translate("dlgDataGrid", "Data Grid"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabOutput), _translate("dlgDataGrid", "Output"))
        self.btnClose.setText(_translate("dlgDataGrid", "Close"))


if __name__ == "__main__":
    '''Create an instance of the UI_dlgDataGrid class and display it.'''
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlgDataGrid = QtWidgets.QDialog()
    ui = Ui_dlgDataGrid()
    ui.setupUi(dlgDataGrid)
    dlgDataGrid.show()
    sys.exit(app.exec_())

