# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\John\Documents\NODEERA\V1\forms\dataLoaderTab.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DataLoaderTab(object):
    def setupUi(self, DataLoaderTab):
        DataLoaderTab.setObjectName("DataLoaderTab")
        DataLoaderTab.resize(877, 620)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(DataLoaderTab)
        self.verticalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frmHeader = QtWidgets.QFrame(DataLoaderTab)
        self.frmHeader.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frmHeader.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frmHeader.setObjectName("frmHeader")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frmHeader)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lblName = QtWidgets.QLabel(self.frmHeader)
        self.lblName.setObjectName("lblName")
        self.gridLayout_2.addWidget(self.lblName, 0, 0, 1, 1)
        self.txtName = QtWidgets.QLineEdit(self.frmHeader)
        self.txtName.setReadOnly(True)
        self.txtName.setObjectName("txtName")
        self.gridLayout_2.addWidget(self.txtName, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(518, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 2, 1, 1)
        self.lblDesc = QtWidgets.QLabel(self.frmHeader)
        self.lblDesc.setObjectName("lblDesc")
        self.gridLayout_2.addWidget(self.lblDesc, 1, 0, 1, 1)
        self.txtDesc = QtWidgets.QLineEdit(self.frmHeader)
        self.txtDesc.setReadOnly(True)
        self.txtDesc.setObjectName("txtDesc")
        self.gridLayout_2.addWidget(self.txtDesc, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(518, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.frmHeader)
        self.tabWidget = QtWidgets.QTabWidget(DataLoaderTab)
        self.tabWidget.setObjectName("tabWidget")
        self.tabDataSource = QtWidgets.QWidget()
        self.tabDataSource.setObjectName("tabDataSource")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tabDataSource)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.tabDataSource)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 170))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.cboDataMap = QtWidgets.QComboBox(self.frame)
        self.cboDataMap.setMinimumSize(QtCore.QSize(150, 0))
        self.cboDataMap.setObjectName("cboDataMap")
        self.gridLayout.addWidget(self.cboDataMap, 0, 1, 1, 3)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 4, 1, 2)
        self.txtDataSource = QtWidgets.QLineEdit(self.frame)
        self.txtDataSource.setMinimumSize(QtCore.QSize(150, 0))
        self.txtDataSource.setReadOnly(True)
        self.txtDataSource.setObjectName("txtDataSource")
        self.gridLayout.addWidget(self.txtDataSource, 0, 6, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(78, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 7, 1, 1)
        self.btnRunLoad = QtWidgets.QPushButton(self.frame)
        self.btnRunLoad.setObjectName("btnRunLoad")
        self.gridLayout.addWidget(self.btnRunLoad, 0, 8, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.txtJobName = QtWidgets.QLineEdit(self.frame)
        self.txtJobName.setMinimumSize(QtCore.QSize(150, 0))
        self.txtJobName.setReadOnly(True)
        self.txtJobName.setObjectName("txtJobName")
        self.gridLayout.addWidget(self.txtJobName, 1, 1, 1, 3)
        spacerItem3 = QtWidgets.QSpacerItem(535, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 4, 1, 5)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.txtLogFolder = QtWidgets.QLineEdit(self.frame)
        self.txtLogFolder.setMinimumSize(QtCore.QSize(151, 0))
        self.txtLogFolder.setReadOnly(True)
        self.txtLogFolder.setObjectName("txtLogFolder")
        self.gridLayout.addWidget(self.txtLogFolder, 2, 1, 1, 3)
        self.btnLogFolder = QtWidgets.QPushButton(self.frame)
        self.btnLogFolder.setObjectName("btnLogFolder")
        self.gridLayout.addWidget(self.btnLogFolder, 2, 4, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(454, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 2, 5, 1, 4)
        self.chkGenCypher = QtWidgets.QCheckBox(self.frame)
        self.chkGenCypher.setObjectName("chkGenCypher")
        self.gridLayout.addWidget(self.chkGenCypher, 3, 0, 1, 1)
        self.txtCypherFolder = QtWidgets.QLineEdit(self.frame)
        self.txtCypherFolder.setMinimumSize(QtCore.QSize(151, 0))
        self.txtCypherFolder.setReadOnly(True)
        self.txtCypherFolder.setObjectName("txtCypherFolder")
        self.gridLayout.addWidget(self.txtCypherFolder, 3, 1, 1, 3)
        self.btnCypherFolder = QtWidgets.QPushButton(self.frame)
        self.btnCypherFolder.setObjectName("btnCypherFolder")
        self.gridLayout.addWidget(self.btnCypherFolder, 3, 4, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(454, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 3, 5, 1, 4)
        self.chkInputLimit = QtWidgets.QCheckBox(self.frame)
        self.chkInputLimit.setObjectName("chkInputLimit")
        self.gridLayout.addWidget(self.chkInputLimit, 4, 0, 1, 2)
        self.spinInputLimit = QtWidgets.QSpinBox(self.frame)
        self.spinInputLimit.setMaximum(1000000)
        self.spinInputLimit.setProperty("value", 1)
        self.spinInputLimit.setObjectName("spinInputLimit")
        self.gridLayout.addWidget(self.spinInputLimit, 4, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(69, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 4, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 4, 1, 1)
        self.spinCommitSize = QtWidgets.QSpinBox(self.frame)
        self.spinCommitSize.setMinimum(1)
        self.spinCommitSize.setMaximum(100000)
        self.spinCommitSize.setObjectName("spinCommitSize")
        self.gridLayout.addWidget(self.spinCommitSize, 4, 5, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(411, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 4, 6, 1, 3)
        self.verticalLayout.addWidget(self.frame)
        self.groupBox = QtWidgets.QGroupBox(self.tabDataSource)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.browserOutput = QtWidgets.QTextBrowser(self.groupBox)
        self.browserOutput.setObjectName("browserOutput")
        self.gridLayout_3.addWidget(self.browserOutput, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.tabWidget.addTab(self.tabDataSource, "")
        self.tabDescription = QtWidgets.QWidget()
        self.tabDescription.setObjectName("tabDescription")
        self.tabWidget.addTab(self.tabDescription, "")
        self.tabRunHistory = QtWidgets.QWidget()
        self.tabRunHistory.setObjectName("tabRunHistory")
        self.tabWidget.addTab(self.tabRunHistory, "")
        self.verticalLayout_2.addWidget(self.tabWidget)

        self.retranslateUi(DataLoaderTab)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DataLoaderTab)

    def retranslateUi(self, DataLoaderTab):
        _translate = QtCore.QCoreApplication.translate
        DataLoaderTab.setWindowTitle(_translate("DataLoaderTab", "Form"))
        self.lblName.setText(_translate("DataLoaderTab", "Name:"))
        self.lblDesc.setText(_translate("DataLoaderTab", "Description:"))
        self.label_2.setText(_translate("DataLoaderTab", "Data Mapping Definition:"))
        self.label.setText(_translate("DataLoaderTab", "Input Source Definition:"))
        self.btnRunLoad.setText(_translate("DataLoaderTab", "Run Bulk Load"))
        self.label_3.setText(_translate("DataLoaderTab", "Job Name:"))
        self.label_4.setText(_translate("DataLoaderTab", "Log File Folder:"))
        self.btnLogFolder.setText(_translate("DataLoaderTab", "Select Folder"))
        self.chkGenCypher.setText(_translate("DataLoaderTab", "Generate Cypher File"))
        self.btnCypherFolder.setText(_translate("DataLoaderTab", "Select Folder"))
        self.chkInputLimit.setText(_translate("DataLoaderTab", "Record Processing Limit:"))
        self.label_5.setText(_translate("DataLoaderTab", "Commit Size:"))
        self.groupBox.setTitle(_translate("DataLoaderTab", "Run Log"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDataSource), _translate("DataLoaderTab", "Data Loader"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDescription), _translate("DataLoaderTab", "Description"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRunHistory), _translate("DataLoaderTab", "Run History"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DataLoaderTab = QtWidgets.QWidget()
    ui = Ui_DataLoaderTab()
    ui.setupUi(DataLoaderTab)
    DataLoaderTab.show()
    sys.exit(app.exec_())

