# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\John\Documents\NODEERA\V1\forms\dmMergeRel.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DmMergeRel(object):
    def setupUi(self, DmMergeRel):
        DmMergeRel.setObjectName("DmMergeRel")
        DmMergeRel.resize(767, 858)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(DmMergeRel)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frmHeader = QtWidgets.QFrame(DmMergeRel)
        self.frmHeader.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmHeader.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmHeader.setObjectName("frmHeader")
        self.gridLayout = QtWidgets.QGridLayout(self.frmHeader)
        self.gridLayout.setObjectName("gridLayout")
        self.lblName = QtWidgets.QLabel(self.frmHeader)
        self.lblName.setObjectName("lblName")
        self.gridLayout.addWidget(self.lblName, 0, 0, 1, 1)
        self.txtName = QtWidgets.QLineEdit(self.frmHeader)
        self.txtName.setReadOnly(True)
        self.txtName.setObjectName("txtName")
        self.gridLayout.addWidget(self.txtName, 0, 1, 1, 2)
        self.lblDesc = QtWidgets.QLabel(self.frmHeader)
        self.lblDesc.setObjectName("lblDesc")
        self.gridLayout.addWidget(self.lblDesc, 0, 3, 1, 1)
        self.txtDesc = QtWidgets.QLineEdit(self.frmHeader)
        self.txtDesc.setMinimumSize(QtCore.QSize(300, 0))
        self.txtDesc.setReadOnly(True)
        self.txtDesc.setObjectName("txtDesc")
        self.gridLayout.addWidget(self.txtDesc, 0, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(348, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 5, 1, 1)
        self.lblMethod = QtWidgets.QLabel(self.frmHeader)
        self.lblMethod.setObjectName("lblMethod")
        self.gridLayout.addWidget(self.lblMethod, 1, 0, 1, 2)
        self.txtStrategy = QtWidgets.QLineEdit(self.frmHeader)
        self.txtStrategy.setReadOnly(True)
        self.txtStrategy.setObjectName("txtStrategy")
        self.gridLayout.addWidget(self.txtStrategy, 1, 2, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(348, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 5, 1, 1)
        self.lblMethod_2 = QtWidgets.QLabel(self.frmHeader)
        self.lblMethod_2.setObjectName("lblMethod_2")
        self.gridLayout.addWidget(self.lblMethod_2, 2, 0, 1, 2)
        self.txtRelName = QtWidgets.QLineEdit(self.frmHeader)
        self.txtRelName.setReadOnly(False)
        self.txtRelName.setObjectName("txtRelName")
        self.gridLayout.addWidget(self.txtRelName, 2, 2, 1, 3)
        spacerItem2 = QtWidgets.QSpacerItem(338, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 5, 1, 1)
        self.lblMethod_3 = QtWidgets.QLabel(self.frmHeader)
        self.lblMethod_3.setObjectName("lblMethod_3")
        self.gridLayout.addWidget(self.lblMethod_3, 3, 0, 1, 2)
        self.cboDataSource = QtWidgets.QComboBox(self.frmHeader)
        self.cboDataSource.setObjectName("cboDataSource")
        self.gridLayout.addWidget(self.cboDataSource, 3, 2, 1, 3)
        spacerItem3 = QtWidgets.QSpacerItem(338, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 3, 5, 1, 1)
        self.verticalLayout_2.addWidget(self.frmHeader)
        self.tabWidget = QtWidgets.QTabWidget(DmMergeRel)
        self.tabWidget.setObjectName("tabWidget")
        self.tabDataMapping = QtWidgets.QWidget()
        self.tabDataMapping.setObjectName("tabDataMapping")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tabDataMapping)
        self.verticalLayout_7.setContentsMargins(1, 5, 1, 1)
        self.verticalLayout_7.setSpacing(1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.grpMatchFromNode = QtWidgets.QGroupBox(self.tabDataMapping)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpMatchFromNode.sizePolicy().hasHeightForWidth())
        self.grpMatchFromNode.setSizePolicy(sizePolicy)
        self.grpMatchFromNode.setMinimumSize(QtCore.QSize(0, 0))
        self.grpMatchFromNode.setToolTip("")
        self.grpMatchFromNode.setObjectName("grpMatchFromNode")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.grpMatchFromNode)
        self.gridLayout_2.setContentsMargins(1, 3, 1, 1)
        self.gridLayout_2.setSpacing(1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridFromMatchRules = QtWidgets.QTableView(self.grpMatchFromNode)
        self.gridFromMatchRules.setMinimumSize(QtCore.QSize(0, 0))
        self.gridFromMatchRules.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridFromMatchRules.setObjectName("gridFromMatchRules")
        self.gridLayout_2.addWidget(self.gridFromMatchRules, 0, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.grpMatchFromNode)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_3.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btnFromMatchRuleUp = QtWidgets.QToolButton(self.frame_5)
        self.btnFromMatchRuleUp.setObjectName("btnFromMatchRuleUp")
        self.verticalLayout_3.addWidget(self.btnFromMatchRuleUp)
        self.btnFromMatchRuleDown = QtWidgets.QToolButton(self.frame_5)
        self.btnFromMatchRuleDown.setObjectName("btnFromMatchRuleDown")
        self.verticalLayout_3.addWidget(self.btnFromMatchRuleDown)
        spacerItem4 = QtWidgets.QSpacerItem(20, 243, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.gridLayout_2.addWidget(self.frame_5, 0, 1, 2, 1)
        self.frame_2 = QtWidgets.QFrame(self.grpMatchFromNode)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_2.setSpacing(1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnFromMatchRuleAdd = QtWidgets.QPushButton(self.frame_2)
        self.btnFromMatchRuleAdd.setToolTip("")
        self.btnFromMatchRuleAdd.setObjectName("btnFromMatchRuleAdd")
        self.horizontalLayout_2.addWidget(self.btnFromMatchRuleAdd)
        self.btnFromMatchRuleRemove = QtWidgets.QPushButton(self.frame_2)
        self.btnFromMatchRuleRemove.setToolTip("")
        self.btnFromMatchRuleRemove.setObjectName("btnFromMatchRuleRemove")
        self.horizontalLayout_2.addWidget(self.btnFromMatchRuleRemove)
        spacerItem5 = QtWidgets.QSpacerItem(759, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.gridLayout_2.addWidget(self.frame_2, 1, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.grpMatchFromNode)
        self.grpMergeRel = QtWidgets.QGroupBox(self.tabDataMapping)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpMergeRel.sizePolicy().hasHeightForWidth())
        self.grpMergeRel.setSizePolicy(sizePolicy)
        self.grpMergeRel.setMinimumSize(QtCore.QSize(0, 0))
        self.grpMergeRel.setToolTip("")
        self.grpMergeRel.setObjectName("grpMergeRel")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.grpMergeRel)
        self.gridLayout_3.setContentsMargins(1, 3, 1, 1)
        self.gridLayout_3.setSpacing(1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridToMatchRules = QtWidgets.QTableView(self.grpMergeRel)
        self.gridToMatchRules.setMinimumSize(QtCore.QSize(0, 0))
        self.gridToMatchRules.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridToMatchRules.setObjectName("gridToMatchRules")
        self.gridLayout_3.addWidget(self.gridToMatchRules, 0, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.grpMergeRel)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_4.setSpacing(1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnToMatchRuleAdd = QtWidgets.QPushButton(self.frame_4)
        self.btnToMatchRuleAdd.setToolTip("")
        self.btnToMatchRuleAdd.setObjectName("btnToMatchRuleAdd")
        self.horizontalLayout_4.addWidget(self.btnToMatchRuleAdd)
        self.btnToMatchRuleRemove = QtWidgets.QPushButton(self.frame_4)
        self.btnToMatchRuleRemove.setToolTip("")
        self.btnToMatchRuleRemove.setObjectName("btnToMatchRuleRemove")
        self.horizontalLayout_4.addWidget(self.btnToMatchRuleRemove)
        spacerItem6 = QtWidgets.QSpacerItem(497, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.gridLayout_3.addWidget(self.frame_4, 1, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.grpMergeRel)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_4.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_4.setSpacing(3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btnToMatchRuleUp = QtWidgets.QToolButton(self.frame_6)
        self.btnToMatchRuleUp.setObjectName("btnToMatchRuleUp")
        self.verticalLayout_4.addWidget(self.btnToMatchRuleUp)
        self.btnToMatchRuleDown = QtWidgets.QToolButton(self.frame_6)
        self.btnToMatchRuleDown.setObjectName("btnToMatchRuleDown")
        self.verticalLayout_4.addWidget(self.btnToMatchRuleDown)
        spacerItem7 = QtWidgets.QSpacerItem(20, 207, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem7)
        self.gridLayout_3.addWidget(self.frame_6, 0, 1, 2, 1)
        self.verticalLayout_7.addWidget(self.grpMergeRel)
        self.tabWidget.addTab(self.tabDataMapping, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.grpMergeRel_3 = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpMergeRel_3.sizePolicy().hasHeightForWidth())
        self.grpMergeRel_3.setSizePolicy(sizePolicy)
        self.grpMergeRel_3.setMinimumSize(QtCore.QSize(0, 0))
        self.grpMergeRel_3.setToolTip("")
        self.grpMergeRel_3.setObjectName("grpMergeRel_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.grpMergeRel_3)
        self.gridLayout_5.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_5.setHorizontalSpacing(1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridRelMatchRules = QtWidgets.QTableView(self.grpMergeRel_3)
        self.gridRelMatchRules.setMinimumSize(QtCore.QSize(0, 0))
        self.gridRelMatchRules.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridRelMatchRules.setObjectName("gridRelMatchRules")
        self.gridLayout_5.addWidget(self.gridRelMatchRules, 0, 0, 1, 1)
        self.frame_9 = QtWidgets.QFrame(self.grpMergeRel_3)
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_6.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_6.setSpacing(1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btnAddRelMatchRule = QtWidgets.QPushButton(self.frame_9)
        self.btnAddRelMatchRule.setToolTip("")
        self.btnAddRelMatchRule.setObjectName("btnAddRelMatchRule")
        self.horizontalLayout_6.addWidget(self.btnAddRelMatchRule)
        self.btnRemoveRelMatchRule = QtWidgets.QPushButton(self.frame_9)
        self.btnRemoveRelMatchRule.setToolTip("")
        self.btnRemoveRelMatchRule.setObjectName("btnRemoveRelMatchRule")
        self.horizontalLayout_6.addWidget(self.btnRemoveRelMatchRule)
        spacerItem8 = QtWidgets.QSpacerItem(497, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.gridLayout_5.addWidget(self.frame_9, 1, 0, 1, 1)
        self.frame_10 = QtWidgets.QFrame(self.grpMergeRel_3)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_6.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_6.setSpacing(3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.btnRelMatchRuleUp = QtWidgets.QToolButton(self.frame_10)
        self.btnRelMatchRuleUp.setObjectName("btnRelMatchRuleUp")
        self.verticalLayout_6.addWidget(self.btnRelMatchRuleUp)
        self.btnRelMatchRuleDown = QtWidgets.QToolButton(self.frame_10)
        self.btnRelMatchRuleDown.setObjectName("btnRelMatchRuleDown")
        self.verticalLayout_6.addWidget(self.btnRelMatchRuleDown)
        spacerItem9 = QtWidgets.QSpacerItem(20, 207, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem9)
        self.gridLayout_5.addWidget(self.frame_10, 0, 1, 2, 1)
        self.verticalLayout.addWidget(self.grpMergeRel_3)
        self.grpMergeRel_2 = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpMergeRel_2.sizePolicy().hasHeightForWidth())
        self.grpMergeRel_2.setSizePolicy(sizePolicy)
        self.grpMergeRel_2.setMinimumSize(QtCore.QSize(0, 0))
        self.grpMergeRel_2.setToolTip("")
        self.grpMergeRel_2.setObjectName("grpMergeRel_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.grpMergeRel_2)
        self.gridLayout_4.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_4.setSpacing(1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridRelMergeRules = QtWidgets.QTableView(self.grpMergeRel_2)
        self.gridRelMergeRules.setMinimumSize(QtCore.QSize(0, 0))
        self.gridRelMergeRules.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridRelMergeRules.setObjectName("gridRelMergeRules")
        self.gridLayout_4.addWidget(self.gridRelMergeRules, 0, 0, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.grpMergeRel_2)
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_5.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_5.setSpacing(1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btnAddRelMergeRule = QtWidgets.QPushButton(self.frame_7)
        self.btnAddRelMergeRule.setToolTip("")
        self.btnAddRelMergeRule.setObjectName("btnAddRelMergeRule")
        self.horizontalLayout_5.addWidget(self.btnAddRelMergeRule)
        self.btnRemoveRelMergeRule = QtWidgets.QPushButton(self.frame_7)
        self.btnRemoveRelMergeRule.setToolTip("")
        self.btnRemoveRelMergeRule.setObjectName("btnRemoveRelMergeRule")
        self.horizontalLayout_5.addWidget(self.btnRemoveRelMergeRule)
        spacerItem10 = QtWidgets.QSpacerItem(497, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem10)
        self.gridLayout_4.addWidget(self.frame_7, 1, 0, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.grpMergeRel_2)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_5.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_5.setSpacing(3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.btnRelMergeRuleUp = QtWidgets.QToolButton(self.frame_8)
        self.btnRelMergeRuleUp.setObjectName("btnRelMergeRuleUp")
        self.verticalLayout_5.addWidget(self.btnRelMergeRuleUp)
        self.btnRelMergeRuleDown = QtWidgets.QToolButton(self.frame_8)
        self.btnRelMergeRuleDown.setObjectName("btnRelMergeRuleDown")
        self.verticalLayout_5.addWidget(self.btnRelMergeRuleDown)
        spacerItem11 = QtWidgets.QSpacerItem(20, 207, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem11)
        self.gridLayout_4.addWidget(self.frame_8, 0, 1, 2, 1)
        self.verticalLayout.addWidget(self.grpMergeRel_2)
        self.tabWidget.addTab(self.tab, "")
        self.tabDescription = QtWidgets.QWidget()
        self.tabDescription.setObjectName("tabDescription")
        self.tabWidget.addTab(self.tabDescription, "")
        self.tabWhereUsed = QtWidgets.QWidget()
        self.tabWhereUsed.setObjectName("tabWhereUsed")
        self.tabWidget.addTab(self.tabWhereUsed, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.lblName.setBuddy(self.txtName)
        self.lblDesc.setBuddy(self.txtDesc)
        self.lblMethod.setBuddy(self.txtStrategy)
        self.lblMethod_2.setBuddy(self.txtRelName)
        self.lblMethod_3.setBuddy(self.txtRelName)

        self.retranslateUi(DmMergeRel)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DmMergeRel)

    def retranslateUi(self, DmMergeRel):
        _translate = QtCore.QCoreApplication.translate
        DmMergeRel.setWindowTitle(_translate("DmMergeRel", "Form"))
        self.lblName.setText(_translate("DmMergeRel", "Name:"))
        self.lblDesc.setText(_translate("DmMergeRel", "Description:"))
        self.lblMethod.setText(_translate("DmMergeRel", "Mapping Strategy:"))
        self.lblMethod_2.setText(_translate("DmMergeRel", "Relationship Name:"))
        self.lblMethod_3.setText(_translate("DmMergeRel", "Data Source:"))
        self.grpMatchFromNode.setTitle(_translate("DmMergeRel", "From Node Match Rules"))
        self.btnFromMatchRuleUp.setText(_translate("DmMergeRel", "UP"))
        self.btnFromMatchRuleDown.setText(_translate("DmMergeRel", "DN"))
        self.btnFromMatchRuleAdd.setText(_translate("DmMergeRel", "Add"))
        self.btnFromMatchRuleRemove.setText(_translate("DmMergeRel", "Remove"))
        self.grpMergeRel.setTitle(_translate("DmMergeRel", "To Node Match Rules"))
        self.btnToMatchRuleAdd.setText(_translate("DmMergeRel", "Add"))
        self.btnToMatchRuleRemove.setText(_translate("DmMergeRel", "Remove"))
        self.btnToMatchRuleUp.setText(_translate("DmMergeRel", "UP"))
        self.btnToMatchRuleDown.setText(_translate("DmMergeRel", "DN"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDataMapping), _translate("DmMergeRel", "Node Match Rules"))
        self.grpMergeRel_3.setTitle(_translate("DmMergeRel", "Relationship Match Rules"))
        self.btnAddRelMatchRule.setText(_translate("DmMergeRel", "Add"))
        self.btnRemoveRelMatchRule.setText(_translate("DmMergeRel", "Remove"))
        self.btnRelMatchRuleUp.setText(_translate("DmMergeRel", "UP"))
        self.btnRelMatchRuleDown.setText(_translate("DmMergeRel", "DN"))
        self.grpMergeRel_2.setTitle(_translate("DmMergeRel", "Relationship Merge Rules"))
        self.btnAddRelMergeRule.setText(_translate("DmMergeRel", "Add"))
        self.btnRemoveRelMergeRule.setText(_translate("DmMergeRel", "Remove"))
        self.btnRelMergeRuleUp.setText(_translate("DmMergeRel", "UP"))
        self.btnRelMergeRuleDown.setText(_translate("DmMergeRel", "DN"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("DmMergeRel", "Relationship Match Merge Rules"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDescription), _translate("DmMergeRel", "Description"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWhereUsed), _translate("DmMergeRel", "Where Used"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DmMergeRel = QtWidgets.QWidget()
    ui = Ui_DmMergeRel()
    ui.setupUi(DmMergeRel)
    DmMergeRel.show()
    sys.exit(app.exec_())

