# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\John\Documents\NODEERA\V1\forms\dataMappingTab.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DataMappingTab(object):
    def setupUi(self, DataMappingTab):
        DataMappingTab.setObjectName("DataMappingTab")
        DataMappingTab.resize(907, 858)
        self.verticalLayout = QtWidgets.QVBoxLayout(DataMappingTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frmHeader = QtWidgets.QFrame(DataMappingTab)
        self.frmHeader.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmHeader.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmHeader.setObjectName("frmHeader")
        self.gridLayout = QtWidgets.QGridLayout(self.frmHeader)
        self.gridLayout.setObjectName("gridLayout")
        self.lblName = QtWidgets.QLabel(self.frmHeader)
        self.lblName.setObjectName("lblName")
        self.gridLayout.addWidget(self.lblName, 0, 0, 1, 1)
        self.txtName = QtWidgets.QLineEdit(self.frmHeader)
        self.txtName.setReadOnly(True)
        self.txtName.setObjectName("txtName")
        self.gridLayout.addWidget(self.txtName, 0, 1, 1, 2)
        self.lblDesc = QtWidgets.QLabel(self.frmHeader)
        self.lblDesc.setObjectName("lblDesc")
        self.gridLayout.addWidget(self.lblDesc, 0, 3, 1, 1)
        self.txtDesc = QtWidgets.QLineEdit(self.frmHeader)
        self.txtDesc.setMinimumSize(QtCore.QSize(300, 0))
        self.txtDesc.setReadOnly(True)
        self.txtDesc.setObjectName("txtDesc")
        self.gridLayout.addWidget(self.txtDesc, 0, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(348, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 5, 1, 1)
        self.lblMethod = QtWidgets.QLabel(self.frmHeader)
        self.lblMethod.setObjectName("lblMethod")
        self.gridLayout.addWidget(self.lblMethod, 1, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(348, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 5, 1, 1)
        self.txtStrategy = QtWidgets.QLineEdit(self.frmHeader)
        self.txtStrategy.setReadOnly(True)
        self.txtStrategy.setObjectName("txtStrategy")
        self.gridLayout.addWidget(self.txtStrategy, 1, 2, 1, 3)
        self.verticalLayout.addWidget(self.frmHeader)
        self.tabWidget = QtWidgets.QTabWidget(DataMappingTab)
        self.tabWidget.setObjectName("tabWidget")
        self.tabDataMapping = QtWidgets.QWidget()
        self.tabDataMapping.setObjectName("tabDataMapping")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabDataMapping)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackDataMap = QtWidgets.QStackedWidget(self.tabDataMapping)
        self.stackDataMap.setObjectName("stackDataMap")
        self.mergeNode = QtWidgets.QWidget()
        self.mergeNode.setObjectName("mergeNode")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.mergeNode)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame = QtWidgets.QFrame(self.mergeNode)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.boxTemplate = QtWidgets.QGroupBox(self.frame)
        self.boxTemplate.setObjectName("boxTemplate")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.boxTemplate)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lblTemplate = QtWidgets.QLabel(self.boxTemplate)
        self.lblTemplate.setObjectName("lblTemplate")
        self.horizontalLayout_5.addWidget(self.lblTemplate)
        self.cboTemplate = QtWidgets.QComboBox(self.boxTemplate)
        self.cboTemplate.setMinimumSize(QtCore.QSize(204, 0))
        self.cboTemplate.setObjectName("cboTemplate")
        self.horizontalLayout_5.addWidget(self.cboTemplate)
        self.btnCreateTemplate = QtWidgets.QPushButton(self.boxTemplate)
        self.btnCreateTemplate.setObjectName("btnCreateTemplate")
        self.horizontalLayout_5.addWidget(self.btnCreateTemplate)
        spacerItem2 = QtWidgets.QSpacerItem(49, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.horizontalLayout.addWidget(self.boxTemplate)
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cboDataSource = QtWidgets.QComboBox(self.groupBox)
        self.cboDataSource.setMinimumSize(QtCore.QSize(200, 0))
        self.cboDataSource.setObjectName("cboDataSource")
        self.horizontalLayout_3.addWidget(self.cboDataSource)
        spacerItem3 = QtWidgets.QSpacerItem(179, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.horizontalLayout.addWidget(self.groupBox)
        self.verticalLayout_5.addWidget(self.frame)
        self.groupBoxMatch = QtWidgets.QGroupBox(self.mergeNode)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxMatch.sizePolicy().hasHeightForWidth())
        self.groupBoxMatch.setSizePolicy(sizePolicy)
        self.groupBoxMatch.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBoxMatch.setToolTip("")
        self.groupBoxMatch.setObjectName("groupBoxMatch")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBoxMatch)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridMatchRules = QtWidgets.QTableView(self.groupBoxMatch)
        self.gridMatchRules.setMinimumSize(QtCore.QSize(0, 0))
        self.gridMatchRules.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridMatchRules.setObjectName("gridMatchRules")
        self.gridLayout_2.addWidget(self.gridMatchRules, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.groupBoxMatch)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnMatchRuleAdd = QtWidgets.QPushButton(self.frame_2)
        self.btnMatchRuleAdd.setToolTip("")
        self.btnMatchRuleAdd.setObjectName("btnMatchRuleAdd")
        self.horizontalLayout_2.addWidget(self.btnMatchRuleAdd)
        self.btnMatchRuleRemove = QtWidgets.QPushButton(self.frame_2)
        self.btnMatchRuleRemove.setToolTip("")
        self.btnMatchRuleRemove.setObjectName("btnMatchRuleRemove")
        self.horizontalLayout_2.addWidget(self.btnMatchRuleRemove)
        spacerItem4 = QtWidgets.QSpacerItem(759, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.gridLayout_2.addWidget(self.frame_2, 1, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.groupBoxMatch)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_3.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btnMatchRuleUp = QtWidgets.QToolButton(self.frame_5)
        self.btnMatchRuleUp.setObjectName("btnMatchRuleUp")
        self.verticalLayout_3.addWidget(self.btnMatchRuleUp)
        self.btnMatchRuleDown = QtWidgets.QToolButton(self.frame_5)
        self.btnMatchRuleDown.setObjectName("btnMatchRuleDown")
        self.verticalLayout_3.addWidget(self.btnMatchRuleDown)
        spacerItem5 = QtWidgets.QSpacerItem(20, 243, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.gridLayout_2.addWidget(self.frame_5, 0, 1, 2, 1)
        self.verticalLayout_5.addWidget(self.groupBoxMatch)
        self.groupBox_Merge = QtWidgets.QGroupBox(self.mergeNode)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_Merge.sizePolicy().hasHeightForWidth())
        self.groupBox_Merge.setSizePolicy(sizePolicy)
        self.groupBox_Merge.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_Merge.setToolTip("")
        self.groupBox_Merge.setObjectName("groupBox_Merge")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_Merge)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridMergeRules = QtWidgets.QTableView(self.groupBox_Merge)
        self.gridMergeRules.setMinimumSize(QtCore.QSize(0, 0))
        self.gridMergeRules.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridMergeRules.setObjectName("gridMergeRules")
        self.gridLayout_3.addWidget(self.gridMergeRules, 0, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.groupBox_Merge)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnAddMergeRule = QtWidgets.QPushButton(self.frame_4)
        self.btnAddMergeRule.setToolTip("")
        self.btnAddMergeRule.setObjectName("btnAddMergeRule")
        self.horizontalLayout_4.addWidget(self.btnAddMergeRule)
        self.btnRemoveMergeRule = QtWidgets.QPushButton(self.frame_4)
        self.btnRemoveMergeRule.setToolTip("")
        self.btnRemoveMergeRule.setObjectName("btnRemoveMergeRule")
        self.horizontalLayout_4.addWidget(self.btnRemoveMergeRule)
        spacerItem6 = QtWidgets.QSpacerItem(497, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.gridLayout_3.addWidget(self.frame_4, 1, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.groupBox_Merge)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_4.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_4.setSpacing(3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btnMergeRuleUp = QtWidgets.QToolButton(self.frame_6)
        self.btnMergeRuleUp.setObjectName("btnMergeRuleUp")
        self.verticalLayout_4.addWidget(self.btnMergeRuleUp)
        self.btnMergeRuleDown = QtWidgets.QToolButton(self.frame_6)
        self.btnMergeRuleDown.setObjectName("btnMergeRuleDown")
        self.verticalLayout_4.addWidget(self.btnMergeRuleDown)
        spacerItem7 = QtWidgets.QSpacerItem(20, 207, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem7)
        self.gridLayout_3.addWidget(self.frame_6, 0, 1, 2, 1)
        self.verticalLayout_5.addWidget(self.groupBox_Merge)
        self.stackDataMap.addWidget(self.mergeNode)
        self.mergeRel = QtWidgets.QWidget()
        self.mergeRel.setObjectName("mergeRel")
        self.label = QtWidgets.QLabel(self.mergeRel)
        self.label.setGeometry(QtCore.QRect(100, 30, 121, 16))
        self.label.setObjectName("label")
        self.stackDataMap.addWidget(self.mergeRel)
        self.createNode = QtWidgets.QWidget()
        self.createNode.setObjectName("createNode")
        self.label_2 = QtWidgets.QLabel(self.createNode)
        self.label_2.setGeometry(QtCore.QRect(140, 40, 131, 16))
        self.label_2.setObjectName("label_2")
        self.stackDataMap.addWidget(self.createNode)
        self.verticalLayout_2.addWidget(self.stackDataMap)
        self.tabWidget.addTab(self.tabDataMapping, "")
        self.tabDescription = QtWidgets.QWidget()
        self.tabDescription.setObjectName("tabDescription")
        self.tabWidget.addTab(self.tabDescription, "")
        self.tabWhereUsed = QtWidgets.QWidget()
        self.tabWhereUsed.setObjectName("tabWhereUsed")
        self.tabWidget.addTab(self.tabWhereUsed, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(DataMappingTab)
        self.tabWidget.setCurrentIndex(0)
        self.stackDataMap.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DataMappingTab)

    def retranslateUi(self, DataMappingTab):
        _translate = QtCore.QCoreApplication.translate
        DataMappingTab.setWindowTitle(_translate("DataMappingTab", "Form"))
        self.lblName.setText(_translate("DataMappingTab", "Name:"))
        self.lblDesc.setText(_translate("DataMappingTab", "Description:"))
        self.lblMethod.setText(_translate("DataMappingTab", "Mapping Strategy:"))
        self.boxTemplate.setTitle(_translate("DataMappingTab", "Node Template"))
        self.lblTemplate.setText(_translate("DataMappingTab", "Name:"))
        self.btnCreateTemplate.setText(_translate("DataMappingTab", "Create New Template"))
        self.groupBox.setTitle(_translate("DataMappingTab", "Data Source"))
        self.groupBoxMatch.setTitle(_translate("DataMappingTab", "Match Rules"))
        self.btnMatchRuleAdd.setText(_translate("DataMappingTab", "Add"))
        self.btnMatchRuleRemove.setText(_translate("DataMappingTab", "Remove"))
        self.btnMatchRuleUp.setText(_translate("DataMappingTab", "UP"))
        self.btnMatchRuleDown.setText(_translate("DataMappingTab", "DN"))
        self.groupBox_Merge.setTitle(_translate("DataMappingTab", "Merge Rules"))
        self.btnAddMergeRule.setText(_translate("DataMappingTab", "Add"))
        self.btnRemoveMergeRule.setText(_translate("DataMappingTab", "Remove"))
        self.btnMergeRuleUp.setText(_translate("DataMappingTab", "UP"))
        self.btnMergeRuleDown.setText(_translate("DataMappingTab", "DN"))
        self.label.setText(_translate("DataMappingTab", "merge relationship"))
        self.label_2.setText(_translate("DataMappingTab", "create node"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDataMapping), _translate("DataMappingTab", "Data Mapping"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDescription), _translate("DataMappingTab", "Description"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWhereUsed), _translate("DataMappingTab", "Where Used"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DataMappingTab = QtWidgets.QWidget()
    ui = Ui_DataMappingTab()
    ui.setupUi(DataMappingTab)
    DataMappingTab.show()
    sys.exit(app.exec_())

