# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Jsing\OneDrive\Documents\DEV_LAPTOP_LOCAL_REPO\NODEERA\forms\EditRelWidget.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditRelWidget(object):
    def setupUi(self, EditRelWidget):
        EditRelWidget.setObjectName("EditRelWidget")
        EditRelWidget.resize(853, 522)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(EditRelWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frameLabels = QtWidgets.QFrame(EditRelWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameLabels.sizePolicy().hasHeightForWidth())
        self.frameLabels.setSizePolicy(sizePolicy)
        self.frameLabels.setMinimumSize(QtCore.QSize(375, 0))
        self.frameLabels.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameLabels.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameLabels.setLineWidth(0)
        self.frameLabels.setObjectName("frameLabels")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frameLabels)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.frameLabels)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.lblFromNode = QtWidgets.QLabel(self.frame)
        self.lblFromNode.setObjectName("lblFromNode")
        self.gridLayout.addWidget(self.lblFromNode, 0, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(633, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 2)
        self.cmbFromNode = QtWidgets.QComboBox(self.frame)
        self.cmbFromNode.setMinimumSize(QtCore.QSize(550, 0))
        self.cmbFromNode.setObjectName("cmbFromNode")
        self.gridLayout.addWidget(self.cmbFromNode, 1, 0, 1, 4)
        self.lblRelationship = QtWidgets.QLabel(self.frame)
        self.lblRelationship.setObjectName("lblRelationship")
        self.gridLayout.addWidget(self.lblRelationship, 2, 0, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(611, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 3, 1, 1)
        self.lblToNode = QtWidgets.QLabel(self.frame)
        self.lblToNode.setObjectName("lblToNode")
        self.gridLayout.addWidget(self.lblToNode, 3, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(656, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 3, 1, 1, 3)
        self.cmbToNode = QtWidgets.QComboBox(self.frame)
        self.cmbToNode.setMinimumSize(QtCore.QSize(550, 0))
        self.cmbToNode.setObjectName("cmbToNode")
        self.gridLayout.addWidget(self.cmbToNode, 4, 0, 1, 4)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.frameLabels)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(95, 0))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setLineWidth(0)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout.addWidget(self.frame_2)
        self.verticalLayout_2.addWidget(self.frameLabels)
        self.framePropertys = QtWidgets.QFrame(EditRelWidget)
        self.framePropertys.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.framePropertys.setFrameShadow(QtWidgets.QFrame.Plain)
        self.framePropertys.setLineWidth(0)
        self.framePropertys.setObjectName("framePropertys")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.framePropertys)
        self.horizontalLayout_2.setContentsMargins(0, 2, 0, 0)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridProps = QtWidgets.QTableView(self.framePropertys)
        self.gridProps.setObjectName("gridProps")
        self.horizontalLayout_2.addWidget(self.gridProps)
        self.frame_3 = QtWidgets.QFrame(self.framePropertys)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(95, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setLineWidth(0)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnSetNull = QtWidgets.QPushButton(self.frame_3)
        self.btnSetNull.setObjectName("btnSetNull")
        self.verticalLayout.addWidget(self.btnSetNull)
        self.btnAddNew = QtWidgets.QPushButton(self.frame_3)
        self.btnAddNew.setObjectName("btnAddNew")
        self.verticalLayout.addWidget(self.btnAddNew)
        spacerItem3 = QtWidgets.QSpacerItem(20, 152, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.verticalLayout_2.addWidget(self.framePropertys)

        self.retranslateUi(EditRelWidget)
        QtCore.QMetaObject.connectSlotsByName(EditRelWidget)

    def retranslateUi(self, EditRelWidget):
        _translate = QtCore.QCoreApplication.translate
        EditRelWidget.setWindowTitle(_translate("EditRelWidget", "Form"))
        self.lblFromNode.setText(_translate("EditRelWidget", "From Node:"))
        self.lblRelationship.setText(_translate("EditRelWidget", "Relationship Type:"))
        self.lblToNode.setText(_translate("EditRelWidget", "To Node:"))
        self.btnSetNull.setText(_translate("EditRelWidget", "Set Value Null"))
        self.btnAddNew.setText(_translate("EditRelWidget", "Add New Relationship"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EditRelWidget = QtWidgets.QWidget()
    ui = Ui_EditRelWidget()
    ui.setupUi(EditRelWidget)
    EditRelWidget.show()
    sys.exit(app.exec_())
