# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Jsing\OneDrive\Documents\DEV_LAPTOP_LOCAL_REPO\NODEERA\forms\ForwardEngineerSchemaDlg.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ForwardEngineerSchemaDlg(object):
    def setupUi(self, ForwardEngineerSchemaDlg):
        ForwardEngineerSchemaDlg.setObjectName("ForwardEngineerSchemaDlg")
        ForwardEngineerSchemaDlg.resize(653, 379)
        ForwardEngineerSchemaDlg.setSizeGripEnabled(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(ForwardEngineerSchemaDlg)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(ForwardEngineerSchemaDlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 141))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 141))
        self.groupBox.setObjectName("groupBox")
        self.rbDropFirst = QtWidgets.QRadioButton(self.groupBox)
        self.rbDropFirst.setGeometry(QtCore.QRect(20, 20, 281, 17))
        self.rbDropFirst.setObjectName("rbDropFirst")
        self.rbCreateFirst = QtWidgets.QRadioButton(self.groupBox)
        self.rbCreateFirst.setGeometry(QtCore.QRect(20, 40, 261, 17))
        self.rbCreateFirst.setObjectName("rbCreateFirst")
        self.rbDropCreate = QtWidgets.QRadioButton(self.groupBox)
        self.rbDropCreate.setGeometry(QtCore.QRect(20, 60, 321, 17))
        self.rbDropCreate.setObjectName("rbDropCreate")
        self.rbDropOnly = QtWidgets.QRadioButton(self.groupBox)
        self.rbDropOnly.setGeometry(QtCore.QRect(20, 80, 181, 17))
        self.rbDropOnly.setObjectName("rbDropOnly")
        self.rbCreateOnly = QtWidgets.QRadioButton(self.groupBox)
        self.rbCreateOnly.setGeometry(QtCore.QRect(20, 100, 191, 17))
        self.rbCreateOnly.setObjectName("rbCreateOnly")
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(ForwardEngineerSchemaDlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 121))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 121))
        self.groupBox_2.setObjectName("groupBox_2")
        self.cbNodeKey = QtWidgets.QCheckBox(self.groupBox_2)
        self.cbNodeKey.setGeometry(QtCore.QRect(10, 20, 241, 17))
        self.cbNodeKey.setObjectName("cbNodeKey")
        self.cbNodePropertyUnique = QtWidgets.QCheckBox(self.groupBox_2)
        self.cbNodePropertyUnique.setGeometry(QtCore.QRect(10, 40, 271, 17))
        self.cbNodePropertyUnique.setObjectName("cbNodePropertyUnique")
        self.cbNodePropertyExists = QtWidgets.QCheckBox(self.groupBox_2)
        self.cbNodePropertyExists.setGeometry(QtCore.QRect(10, 60, 271, 17))
        self.cbNodePropertyExists.setObjectName("cbNodePropertyExists")
        self.cbRelPropertyExists = QtWidgets.QCheckBox(self.groupBox_2)
        self.cbRelPropertyExists.setGeometry(QtCore.QRect(10, 80, 281, 17))
        self.cbRelPropertyExists.setObjectName("cbRelPropertyExists")
        self.rbIndexAll = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbIndexAll.setGeometry(QtCore.QRect(330, 40, 221, 17))
        self.rbIndexAll.setObjectName("rbIndexAll")
        self.rbIndexNoConstraint = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbIndexNoConstraint.setGeometry(QtCore.QRect(330, 60, 221, 17))
        self.rbIndexNoConstraint.setObjectName("rbIndexNoConstraint")
        self.cbIndex = QtWidgets.QCheckBox(self.groupBox_2)
        self.cbIndex.setGeometry(QtCore.QRect(310, 20, 161, 17))
        self.cbIndex.setObjectName("cbIndex")
        self.verticalLayout.addWidget(self.groupBox_2)
        self.frame = QtWidgets.QFrame(ForwardEngineerSchemaDlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 43))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 43))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(211, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnGenerate = QtWidgets.QPushButton(self.frame)
        self.btnGenerate.setObjectName("btnGenerate")
        self.horizontalLayout.addWidget(self.btnGenerate)
        spacerItem1 = QtWidgets.QSpacerItem(211, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.frame)
        self.buttonBox = QtWidgets.QDialogButtonBox(ForwardEngineerSchemaDlg)
        self.buttonBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ForwardEngineerSchemaDlg)
        self.buttonBox.accepted.connect(ForwardEngineerSchemaDlg.accept)
        self.buttonBox.rejected.connect(ForwardEngineerSchemaDlg.reject)
        QtCore.QMetaObject.connectSlotsByName(ForwardEngineerSchemaDlg)
        ForwardEngineerSchemaDlg.setTabOrder(self.rbDropFirst, self.rbCreateFirst)
        ForwardEngineerSchemaDlg.setTabOrder(self.rbCreateFirst, self.rbDropCreate)
        ForwardEngineerSchemaDlg.setTabOrder(self.rbDropCreate, self.rbDropOnly)
        ForwardEngineerSchemaDlg.setTabOrder(self.rbDropOnly, self.rbCreateOnly)
        ForwardEngineerSchemaDlg.setTabOrder(self.rbCreateOnly, self.cbNodeKey)
        ForwardEngineerSchemaDlg.setTabOrder(self.cbNodeKey, self.cbNodePropertyUnique)
        ForwardEngineerSchemaDlg.setTabOrder(self.cbNodePropertyUnique, self.cbNodePropertyExists)
        ForwardEngineerSchemaDlg.setTabOrder(self.cbNodePropertyExists, self.cbRelPropertyExists)
        ForwardEngineerSchemaDlg.setTabOrder(self.cbRelPropertyExists, self.cbIndex)
        ForwardEngineerSchemaDlg.setTabOrder(self.cbIndex, self.rbIndexAll)
        ForwardEngineerSchemaDlg.setTabOrder(self.rbIndexAll, self.rbIndexNoConstraint)
        ForwardEngineerSchemaDlg.setTabOrder(self.rbIndexNoConstraint, self.btnGenerate)

    def retranslateUi(self, ForwardEngineerSchemaDlg):
        _translate = QtCore.QCoreApplication.translate
        ForwardEngineerSchemaDlg.setWindowTitle(_translate("ForwardEngineerSchemaDlg", "Generate Schema Object Cypher Statements"))
        self.groupBox.setToolTip(_translate("ForwardEngineerSchemaDlg", "Select how to generate the cypher statements"))
        self.groupBox.setTitle(_translate("ForwardEngineerSchemaDlg", "Generate Options"))
        self.rbDropFirst.setText(_translate("ForwardEngineerSchemaDlg", "Drops first, then Creates"))
        self.rbCreateFirst.setText(_translate("ForwardEngineerSchemaDlg", "Creates first, then Drops"))
        self.rbDropCreate.setText(_translate("ForwardEngineerSchemaDlg", "For each object, Drop then Create"))
        self.rbDropOnly.setText(_translate("ForwardEngineerSchemaDlg", "Drops Only"))
        self.rbCreateOnly.setText(_translate("ForwardEngineerSchemaDlg", "Creates Only"))
        self.groupBox_2.setToolTip(_translate("ForwardEngineerSchemaDlg", "Select which objects to generate"))
        self.groupBox_2.setTitle(_translate("ForwardEngineerSchemaDlg", "Schema Objects"))
        self.cbNodeKey.setText(_translate("ForwardEngineerSchemaDlg", "Node Key Constraint"))
        self.cbNodePropertyUnique.setText(_translate("ForwardEngineerSchemaDlg", "Node Property Unique Constraint"))
        self.cbNodePropertyExists.setText(_translate("ForwardEngineerSchemaDlg", "Node Property Exists Constraint"))
        self.cbRelPropertyExists.setText(_translate("ForwardEngineerSchemaDlg", "Relationship Property Exists Constraint"))
        self.rbIndexAll.setText(_translate("ForwardEngineerSchemaDlg", "All Indexes"))
        self.rbIndexNoConstraint.setText(_translate("ForwardEngineerSchemaDlg", "Non-Constraint Indexes"))
        self.cbIndex.setText(_translate("ForwardEngineerSchemaDlg", "Index"))
        self.btnGenerate.setToolTip(_translate("ForwardEngineerSchemaDlg", "Press to generate the Cypher file"))
        self.btnGenerate.setText(_translate("ForwardEngineerSchemaDlg", "Generate Cypher File"))
        self.buttonBox.setToolTip(_translate("ForwardEngineerSchemaDlg", "Press Close to close the dialog box."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ForwardEngineerSchemaDlg = QtWidgets.QDialog()
    ui = Ui_ForwardEngineerSchemaDlg()
    ui.setupUi(ForwardEngineerSchemaDlg)
    ForwardEngineerSchemaDlg.show()
    sys.exit(app.exec_())
