# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Jsing\OneDrive\Documents\DEV_LAPTOP_LOCAL_REPO\NODEERA\forms\GenerateSchemaDlg.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GenerateSchemaDlg(object):
    def setupUi(self, GenerateSchemaDlg):
        GenerateSchemaDlg.setObjectName("GenerateSchemaDlg")
        GenerateSchemaDlg.resize(588, 380)
        GenerateSchemaDlg.setSizeGripEnabled(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(GenerateSchemaDlg)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(GenerateSchemaDlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 141))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 141))
        self.groupBox.setObjectName("groupBox")
        self.rbDropFirst = QtWidgets.QRadioButton(self.groupBox)
        self.rbDropFirst.setGeometry(QtCore.QRect(20, 20, 281, 17))
        self.rbDropFirst.setObjectName("rbDropFirst")
        self.rbCreateFirst = QtWidgets.QRadioButton(self.groupBox)
        self.rbCreateFirst.setGeometry(QtCore.QRect(20, 40, 261, 17))
        self.rbCreateFirst.setObjectName("rbCreateFirst")
        self.rbDropCreate = QtWidgets.QRadioButton(self.groupBox)
        self.rbDropCreate.setGeometry(QtCore.QRect(20, 60, 261, 17))
        self.rbDropCreate.setObjectName("rbDropCreate")
        self.rbDropOnly = QtWidgets.QRadioButton(self.groupBox)
        self.rbDropOnly.setGeometry(QtCore.QRect(20, 80, 191, 17))
        self.rbDropOnly.setObjectName("rbDropOnly")
        self.rbCreateOnly = QtWidgets.QRadioButton(self.groupBox)
        self.rbCreateOnly.setGeometry(QtCore.QRect(20, 100, 251, 17))
        self.rbCreateOnly.setObjectName("rbCreateOnly")
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(GenerateSchemaDlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 121))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 121))
        self.groupBox_2.setObjectName("groupBox_2")
        self.cbNodeKey = QtWidgets.QCheckBox(self.groupBox_2)
        self.cbNodeKey.setGeometry(QtCore.QRect(10, 20, 241, 17))
        self.cbNodeKey.setObjectName("cbNodeKey")
        self.cbNodePropertyUnique = QtWidgets.QCheckBox(self.groupBox_2)
        self.cbNodePropertyUnique.setGeometry(QtCore.QRect(10, 40, 251, 17))
        self.cbNodePropertyUnique.setObjectName("cbNodePropertyUnique")
        self.cbNodePropertyExists = QtWidgets.QCheckBox(self.groupBox_2)
        self.cbNodePropertyExists.setGeometry(QtCore.QRect(10, 60, 251, 17))
        self.cbNodePropertyExists.setObjectName("cbNodePropertyExists")
        self.cbRelPropertyExists = QtWidgets.QCheckBox(self.groupBox_2)
        self.cbRelPropertyExists.setGeometry(QtCore.QRect(10, 80, 261, 17))
        self.cbRelPropertyExists.setObjectName("cbRelPropertyExists")
        self.cbIndex = QtWidgets.QCheckBox(self.groupBox_2)
        self.cbIndex.setGeometry(QtCore.QRect(290, 20, 181, 17))
        self.cbIndex.setObjectName("cbIndex")
        self.cbUser = QtWidgets.QCheckBox(self.groupBox_2)
        self.cbUser.setGeometry(QtCore.QRect(290, 40, 201, 17))
        self.cbUser.setObjectName("cbUser")
        self.cbRole = QtWidgets.QCheckBox(self.groupBox_2)
        self.cbRole.setGeometry(QtCore.QRect(290, 60, 201, 17))
        self.cbRole.setObjectName("cbRole")
        self.verticalLayout.addWidget(self.groupBox_2)
        self.frame = QtWidgets.QFrame(GenerateSchemaDlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 43))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 43))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(211, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnGenerate = QtWidgets.QPushButton(self.frame)
        self.btnGenerate.setObjectName("btnGenerate")
        self.horizontalLayout.addWidget(self.btnGenerate)
        spacerItem1 = QtWidgets.QSpacerItem(211, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.frame)
        self.buttonBox = QtWidgets.QDialogButtonBox(GenerateSchemaDlg)
        self.buttonBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(GenerateSchemaDlg)
        self.buttonBox.accepted.connect(GenerateSchemaDlg.accept)
        self.buttonBox.rejected.connect(GenerateSchemaDlg.reject)
        QtCore.QMetaObject.connectSlotsByName(GenerateSchemaDlg)

    def retranslateUi(self, GenerateSchemaDlg):
        _translate = QtCore.QCoreApplication.translate
        GenerateSchemaDlg.setWindowTitle(_translate("GenerateSchemaDlg", "Generate Schema Object Cypher Statements"))
        self.groupBox.setToolTip(_translate("GenerateSchemaDlg", "Select how to generate the cypher statements"))
        self.groupBox.setTitle(_translate("GenerateSchemaDlg", "Generate Options"))
        self.rbDropFirst.setText(_translate("GenerateSchemaDlg", "Drops first, then Creates"))
        self.rbCreateFirst.setText(_translate("GenerateSchemaDlg", "Creates first, then Drops"))
        self.rbDropCreate.setText(_translate("GenerateSchemaDlg", "For each object, Drop then Create"))
        self.rbDropOnly.setText(_translate("GenerateSchemaDlg", "Drops Only"))
        self.rbCreateOnly.setText(_translate("GenerateSchemaDlg", "Creates Only"))
        self.groupBox_2.setToolTip(_translate("GenerateSchemaDlg", "Select which objects to generate"))
        self.groupBox_2.setTitle(_translate("GenerateSchemaDlg", "Schema Objects"))
        self.cbNodeKey.setText(_translate("GenerateSchemaDlg", "Node Key Constraint"))
        self.cbNodePropertyUnique.setText(_translate("GenerateSchemaDlg", "Node Property Unique Constraint"))
        self.cbNodePropertyExists.setText(_translate("GenerateSchemaDlg", "Node Property Exists Constraint"))
        self.cbRelPropertyExists.setText(_translate("GenerateSchemaDlg", "Relationship Property Exists Constraint"))
        self.cbIndex.setText(_translate("GenerateSchemaDlg", "Index"))
        self.cbUser.setText(_translate("GenerateSchemaDlg", "User"))
        self.cbRole.setText(_translate("GenerateSchemaDlg", "Role"))
        self.btnGenerate.setToolTip(_translate("GenerateSchemaDlg", "Press to generate the Cypher file"))
        self.btnGenerate.setText(_translate("GenerateSchemaDlg", "Generate Cypher File"))
        self.buttonBox.setToolTip(_translate("GenerateSchemaDlg", "Press Close to close the dialog box."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GenerateSchemaDlg = QtWidgets.QDialog()
    ui = Ui_GenerateSchemaDlg()
    ui.setupUi(GenerateSchemaDlg)
    GenerateSchemaDlg.show()
    sys.exit(app.exec_())
