# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Jsing\OneDrive\Documents\DEV_LAPTOP_LOCAL_REPO\NODEERA\forms\HelpAboutDLG.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_HelpAboutDLG(object):
    def setupUi(self, HelpAboutDLG):
        HelpAboutDLG.setObjectName("HelpAboutDLG")
        HelpAboutDLG.resize(523, 475)
        HelpAboutDLG.setSizeGripEnabled(True)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(HelpAboutDLG)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frameIcon = QtWidgets.QFrame(HelpAboutDLG)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameIcon.sizePolicy().hasHeightForWidth())
        self.frameIcon.setSizePolicy(sizePolicy)
        self.frameIcon.setMinimumSize(QtCore.QSize(0, 60))
        self.frameIcon.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameIcon.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameIcon.setObjectName("frameIcon")
        self.lblIcon = QtWidgets.QLabel(self.frameIcon)
        self.lblIcon.setGeometry(QtCore.QRect(10, 0, 441, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblIcon.sizePolicy().hasHeightForWidth())
        self.lblIcon.setSizePolicy(sizePolicy)
        self.lblIcon.setMinimumSize(QtCore.QSize(0, 60))
        self.lblIcon.setText("")
        self.lblIcon.setScaledContents(False)
        self.lblIcon.setObjectName("lblIcon")
        self.verticalLayout_2.addWidget(self.frameIcon)
        self.frame = QtWidgets.QFrame(HelpAboutDLG)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.txtProduct = QtWidgets.QLineEdit(self.frame_2)
        self.txtProduct.setReadOnly(True)
        self.txtProduct.setObjectName("txtProduct")
        self.gridLayout.addWidget(self.txtProduct, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(203, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.txtVersion = QtWidgets.QLineEdit(self.frame_2)
        self.txtVersion.setReadOnly(True)
        self.txtVersion.setObjectName("txtVersion")
        self.gridLayout.addWidget(self.txtVersion, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(203, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.frame_2)
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.txtAbout = QtWidgets.QTextEdit(self.groupBox)
        self.txtAbout.setReadOnly(True)
        self.txtAbout.setObjectName("txtAbout")
        self.gridLayout_2.addWidget(self.txtAbout, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(HelpAboutDLG)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(196, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.btnClose = QtWidgets.QPushButton(self.frame_3)
        self.btnClose.setObjectName("btnClose")
        self.horizontalLayout.addWidget(self.btnClose)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.label_2.setBuddy(self.txtProduct)
        self.label_3.setBuddy(self.txtVersion)

        self.retranslateUi(HelpAboutDLG)
        QtCore.QMetaObject.connectSlotsByName(HelpAboutDLG)

    def retranslateUi(self, HelpAboutDLG):
        _translate = QtCore.QCoreApplication.translate
        HelpAboutDLG.setWindowTitle(_translate("HelpAboutDLG", "About NodeEra"))
        self.label_2.setText(_translate("HelpAboutDLG", "Product:"))
        self.label_3.setText(_translate("HelpAboutDLG", "Version:"))
        self.groupBox.setTitle(_translate("HelpAboutDLG", "About"))
        self.btnClose.setText(_translate("HelpAboutDLG", "Close"))

import icons.icons_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HelpAboutDLG = QtWidgets.QDialog()
    ui = Ui_HelpAboutDLG()
    ui.setupUi(HelpAboutDLG)
    HelpAboutDLG.show()
    sys.exit(app.exec_())

