# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Jsing\OneDrive\Documents\DEV_LAPTOP_LOCAL_REPO\NODEERA\forms\IRPropertyBox.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IRPropertyBox(object):
    def setupUi(self, IRPropertyBox):
        IRPropertyBox.setObjectName("IRPropertyBox")
        IRPropertyBox.setWindowModality(QtCore.Qt.ApplicationModal)
        IRPropertyBox.resize(881, 510)
        IRPropertyBox.setSizeGripEnabled(True)
        self.gridLayout = QtWidgets.QGridLayout(IRPropertyBox)
        self.gridLayout.setObjectName("gridLayout")
        self.tabRelInspector = QtWidgets.QTabWidget(IRPropertyBox)
        self.tabRelInspector.setObjectName("tabRelInspector")
        self.tabDataValues = QtWidgets.QWidget()
        self.tabDataValues.setObjectName("tabDataValues")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tabDataValues)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_6 = QtWidgets.QFrame(self.tabDataValues)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lblRelName = QtWidgets.QLabel(self.frame_6)
        self.lblRelName.setObjectName("lblRelName")
        self.gridLayout_2.addWidget(self.lblRelName, 0, 0, 1, 1)
        self.cboRelName = QtWidgets.QComboBox(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboRelName.sizePolicy().hasHeightForWidth())
        self.cboRelName.setSizePolicy(sizePolicy)
        self.cboRelName.setMinimumSize(QtCore.QSize(200, 0))
        self.cboRelName.setEditable(True)
        self.cboRelName.setObjectName("cboRelName")
        self.gridLayout_2.addWidget(self.cboRelName, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(141, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 2, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.frame_6)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.cboFromNode = QtWidgets.QComboBox(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboFromNode.sizePolicy().hasHeightForWidth())
        self.cboFromNode.setSizePolicy(sizePolicy)
        self.cboFromNode.setMinimumSize(QtCore.QSize(200, 0))
        self.cboFromNode.setObjectName("cboFromNode")
        self.gridLayout_2.addWidget(self.cboFromNode, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_6)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 2, 1, 1)
        self.txtFromTemplate = QtWidgets.QLineEdit(self.frame_6)
        self.txtFromTemplate.setMinimumSize(QtCore.QSize(200, 0))
        self.txtFromTemplate.setReadOnly(True)
        self.txtFromTemplate.setObjectName("txtFromTemplate")
        self.gridLayout_2.addWidget(self.txtFromTemplate, 1, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.cboToNode = QtWidgets.QComboBox(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboToNode.sizePolicy().hasHeightForWidth())
        self.cboToNode.setSizePolicy(sizePolicy)
        self.cboToNode.setMinimumSize(QtCore.QSize(200, 0))
        self.cboToNode.setObjectName("cboToNode")
        self.gridLayout_2.addWidget(self.cboToNode, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_6)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 2, 1, 1)
        self.txtToTemplate = QtWidgets.QLineEdit(self.frame_6)
        self.txtToTemplate.setMinimumSize(QtCore.QSize(200, 0))
        self.txtToTemplate.setReadOnly(True)
        self.txtToTemplate.setObjectName("txtToTemplate")
        self.gridLayout_2.addWidget(self.txtToTemplate, 2, 3, 1, 1)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.groupBox_Properties = QtWidgets.QGroupBox(self.tabDataValues)
        self.groupBox_Properties.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_Properties.setToolTip("")
        self.groupBox_Properties.setObjectName("groupBox_Properties")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_Properties)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setHorizontalSpacing(0)
        self.gridLayout_3.setVerticalSpacing(2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridProps = QtWidgets.QTableView(self.groupBox_Properties)
        self.gridProps.setMinimumSize(QtCore.QSize(0, 0))
        self.gridProps.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridProps.setObjectName("gridProps")
        self.gridLayout_3.addWidget(self.gridProps, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.groupBox_Properties)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setContentsMargins(1, 1, -1, 1)
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_3.addWidget(self.frame_3, 0, 1, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.groupBox_Properties)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnPropUp = QtWidgets.QToolButton(self.frame_5)
        self.btnPropUp.setObjectName("btnPropUp")
        self.verticalLayout.addWidget(self.btnPropUp)
        self.btnPropDown = QtWidgets.QToolButton(self.frame_5)
        self.btnPropDown.setObjectName("btnPropDown")
        self.verticalLayout.addWidget(self.btnPropDown)
        spacerItem1 = QtWidgets.QSpacerItem(20, 139, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout_3.addWidget(self.frame_5, 0, 2, 2, 1)
        self.frame_2 = QtWidgets.QFrame(self.groupBox_Properties)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnPropAdd = QtWidgets.QPushButton(self.frame_2)
        self.btnPropAdd.setToolTip("")
        self.btnPropAdd.setObjectName("btnPropAdd")
        self.horizontalLayout_4.addWidget(self.btnPropAdd)
        self.btnPropRemove = QtWidgets.QPushButton(self.frame_2)
        self.btnPropRemove.setToolTip("")
        self.btnPropRemove.setObjectName("btnPropRemove")
        self.horizontalLayout_4.addWidget(self.btnPropRemove)
        self.btnSetNull = QtWidgets.QPushButton(self.frame_2)
        self.btnSetNull.setObjectName("btnSetNull")
        self.horizontalLayout_4.addWidget(self.btnSetNull)
        spacerItem2 = QtWidgets.QSpacerItem(328, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.gridLayout_3.addWidget(self.frame_2, 2, 0, 1, 3)
        self.verticalLayout_3.addWidget(self.groupBox_Properties)
        self.tabRelInspector.addTab(self.tabDataValues, "")
        self.tabDescription = QtWidgets.QWidget()
        self.tabDescription.setObjectName("tabDescription")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tabDescription)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gboxIDs = QtWidgets.QGroupBox(self.tabDescription)
        self.gboxIDs.setMinimumSize(QtCore.QSize(0, 81))
        self.gboxIDs.setMaximumSize(QtCore.QSize(16777215, 81))
        self.gboxIDs.setObjectName("gboxIDs")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gboxIDs)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lblNZID = QtWidgets.QLabel(self.gboxIDs)
        self.lblNZID.setObjectName("lblNZID")
        self.gridLayout_5.addWidget(self.lblNZID, 0, 0, 1, 1)
        self.EditNZID = QtWidgets.QLineEdit(self.gboxIDs)
        self.EditNZID.setObjectName("EditNZID")
        self.gridLayout_5.addWidget(self.EditNZID, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gboxIDs)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 1, 0, 1, 1)
        self.editNeoID = QtWidgets.QLineEdit(self.gboxIDs)
        self.editNeoID.setReadOnly(True)
        self.editNeoID.setObjectName("editNeoID")
        self.gridLayout_5.addWidget(self.editNeoID, 1, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.gboxIDs)
        self.grpDescription = QtWidgets.QGroupBox(self.tabDescription)
        self.grpDescription.setObjectName("grpDescription")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.grpDescription)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.brwsrGeneratedDesc = QtWidgets.QTextBrowser(self.grpDescription)
        self.brwsrGeneratedDesc.setFrameShape(QtWidgets.QFrame.Box)
        self.brwsrGeneratedDesc.setFrameShadow(QtWidgets.QFrame.Plain)
        self.brwsrGeneratedDesc.setObjectName("brwsrGeneratedDesc")
        self.gridLayout_4.addWidget(self.brwsrGeneratedDesc, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.grpDescription)
        self.tabRelInspector.addTab(self.tabDescription, "")
        self.gridLayout.addWidget(self.tabRelInspector, 1, 0, 1, 1)
        self.frame = QtWidgets.QFrame(IRPropertyBox)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(174, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.okButton = QtWidgets.QPushButton(self.frame)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout_3.addWidget(self.okButton)
        self.cancelButton = QtWidgets.QPushButton(self.frame)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_3.addWidget(self.cancelButton)
        spacerItem4 = QtWidgets.QSpacerItem(173, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.gridLayout.addWidget(self.frame, 2, 0, 1, 1)
        self.gboxTemplate = QtWidgets.QFrame(IRPropertyBox)
        self.gboxTemplate.setObjectName("gboxTemplate")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.gboxTemplate)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblTemplate = QtWidgets.QLabel(self.gboxTemplate)
        self.lblTemplate.setObjectName("lblTemplate")
        self.horizontalLayout.addWidget(self.lblTemplate)
        self.cboTemplate = QtWidgets.QComboBox(self.gboxTemplate)
        self.cboTemplate.setMinimumSize(QtCore.QSize(204, 0))
        self.cboTemplate.setObjectName("cboTemplate")
        self.horizontalLayout.addWidget(self.cboTemplate)
        spacerItem5 = QtWidgets.QSpacerItem(79, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.btnCreateTemplate = QtWidgets.QPushButton(self.gboxTemplate)
        self.btnCreateTemplate.setObjectName("btnCreateTemplate")
        self.horizontalLayout.addWidget(self.btnCreateTemplate)
        self.gridLayout.addWidget(self.gboxTemplate, 0, 0, 1, 1)
        self.lblRelName.setBuddy(self.cboRelName)
        self.label_2.setBuddy(self.cboFromNode)
        self.label_4.setBuddy(self.txtFromTemplate)
        self.label_3.setBuddy(self.cboToNode)
        self.label_5.setBuddy(self.txtToTemplate)
        self.lblNZID.setBuddy(self.EditNZID)
        self.label.setBuddy(self.editNeoID)

        self.retranslateUi(IRPropertyBox)
        self.tabRelInspector.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(IRPropertyBox)
        IRPropertyBox.setTabOrder(self.cboTemplate, self.btnCreateTemplate)
        IRPropertyBox.setTabOrder(self.btnCreateTemplate, self.tabRelInspector)
        IRPropertyBox.setTabOrder(self.tabRelInspector, self.cboRelName)
        IRPropertyBox.setTabOrder(self.cboRelName, self.cboFromNode)
        IRPropertyBox.setTabOrder(self.cboFromNode, self.txtFromTemplate)
        IRPropertyBox.setTabOrder(self.txtFromTemplate, self.cboToNode)
        IRPropertyBox.setTabOrder(self.cboToNode, self.txtToTemplate)
        IRPropertyBox.setTabOrder(self.txtToTemplate, self.gridProps)
        IRPropertyBox.setTabOrder(self.gridProps, self.btnPropUp)
        IRPropertyBox.setTabOrder(self.btnPropUp, self.btnPropDown)
        IRPropertyBox.setTabOrder(self.btnPropDown, self.btnPropAdd)
        IRPropertyBox.setTabOrder(self.btnPropAdd, self.btnPropRemove)
        IRPropertyBox.setTabOrder(self.btnPropRemove, self.btnSetNull)
        IRPropertyBox.setTabOrder(self.btnSetNull, self.okButton)
        IRPropertyBox.setTabOrder(self.okButton, self.cancelButton)
        IRPropertyBox.setTabOrder(self.cancelButton, self.EditNZID)
        IRPropertyBox.setTabOrder(self.EditNZID, self.editNeoID)
        IRPropertyBox.setTabOrder(self.editNeoID, self.brwsrGeneratedDesc)

    def retranslateUi(self, IRPropertyBox):
        _translate = QtCore.QCoreApplication.translate
        IRPropertyBox.setWindowTitle(_translate("IRPropertyBox", "Instance Relationship"))
        self.lblRelName.setText(_translate("IRPropertyBox", "Relationship Type:"))
        self.label_2.setText(_translate("IRPropertyBox", "From Node:"))
        self.label_4.setText(_translate("IRPropertyBox", "From Node Template:"))
        self.label_3.setText(_translate("IRPropertyBox", "To Node:"))
        self.label_5.setText(_translate("IRPropertyBox", "To Node Template:"))
        self.groupBox_Properties.setTitle(_translate("IRPropertyBox", "Properties"))
        self.btnPropUp.setText(_translate("IRPropertyBox", "UP"))
        self.btnPropDown.setText(_translate("IRPropertyBox", "DN"))
        self.btnPropAdd.setText(_translate("IRPropertyBox", "Add"))
        self.btnPropRemove.setText(_translate("IRPropertyBox", "Remove"))
        self.btnSetNull.setText(_translate("IRPropertyBox", "Set Value Null"))
        self.tabRelInspector.setTabText(self.tabRelInspector.indexOf(self.tabDataValues), _translate("IRPropertyBox", "Definition"))
        self.gboxIDs.setTitle(_translate("IRPropertyBox", "Relationship ID"))
        self.lblNZID.setText(_translate("IRPropertyBox", "NZID :"))
        self.label.setText(_translate("IRPropertyBox", "Neo4j ID:"))
        self.grpDescription.setTitle(_translate("IRPropertyBox", "Description from Templates"))
        self.tabRelInspector.setTabText(self.tabRelInspector.indexOf(self.tabDescription), _translate("IRPropertyBox", "Description"))
        self.okButton.setText(_translate("IRPropertyBox", "&OK"))
        self.cancelButton.setText(_translate("IRPropertyBox", "&Cancel"))
        self.lblTemplate.setText(_translate("IRPropertyBox", "Relationship Template Name:"))
        self.btnCreateTemplate.setText(_translate("IRPropertyBox", "Create Template"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    IRPropertyBox = QtWidgets.QDialog()
    ui = Ui_IRPropertyBox()
    ui.setupUi(IRPropertyBox)
    IRPropertyBox.show()
    sys.exit(app.exec_())
