# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Jsing\OneDrive\Documents\DEV_LAPTOP_LOCAL_REPO\NODEERA\forms\INPropertyBox.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_INPropertyBox(object):
    def setupUi(self, INPropertyBox):
        INPropertyBox.setObjectName("INPropertyBox")
        INPropertyBox.setWindowModality(QtCore.Qt.ApplicationModal)
        INPropertyBox.resize(762, 669)
        INPropertyBox.setSizeGripEnabled(True)
        self.gridLayout_3 = QtWidgets.QGridLayout(INPropertyBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setObjectName("hboxlayout")
        spacerItem = QtWidgets.QSpacerItem(71, 31, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.okButton = QtWidgets.QPushButton(INPropertyBox)
        self.okButton.setObjectName("okButton")
        self.hboxlayout.addWidget(self.okButton)
        self.cancelButton = QtWidgets.QPushButton(INPropertyBox)
        self.cancelButton.setObjectName("cancelButton")
        self.hboxlayout.addWidget(self.cancelButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem1)
        self.gridLayout_3.addLayout(self.hboxlayout, 2, 0, 1, 1)
        self.tabNodeInspector = QtWidgets.QTabWidget(INPropertyBox)
        self.tabNodeInspector.setObjectName("tabNodeInspector")
        self.tabData = QtWidgets.QWidget()
        self.tabData.setObjectName("tabData")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tabData)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_Labels = QtWidgets.QGroupBox(self.tabData)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_Labels.sizePolicy().hasHeightForWidth())
        self.groupBox_Labels.setSizePolicy(sizePolicy)
        self.groupBox_Labels.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_Labels.setToolTip("")
        self.groupBox_Labels.setObjectName("groupBox_Labels")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_Labels)
        self.verticalLayout_4.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_4.setSpacing(1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_6 = QtWidgets.QFrame(self.groupBox_Labels)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_5.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_5.setSpacing(1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gridLabels = QtWidgets.QTableView(self.frame_6)
        self.gridLabels.setMinimumSize(QtCore.QSize(0, 0))
        self.gridLabels.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridLabels.setObjectName("gridLabels")
        self.horizontalLayout_5.addWidget(self.gridLabels)
        self.frame = QtWidgets.QFrame(self.frame_6)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnLabelUp = QtWidgets.QToolButton(self.frame)
        self.btnLabelUp.setObjectName("btnLabelUp")
        self.verticalLayout.addWidget(self.btnLabelUp)
        self.btnLabelDown = QtWidgets.QToolButton(self.frame)
        self.btnLabelDown.setObjectName("btnLabelDown")
        self.verticalLayout.addWidget(self.btnLabelDown)
        spacerItem2 = QtWidgets.QSpacerItem(20, 81, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_5.addWidget(self.frame)
        self.verticalLayout_4.addWidget(self.frame_6)
        self.frame_2 = QtWidgets.QFrame(self.groupBox_Labels)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnLabelAdd = QtWidgets.QPushButton(self.frame_2)
        self.btnLabelAdd.setToolTip("")
        self.btnLabelAdd.setObjectName("btnLabelAdd")
        self.horizontalLayout.addWidget(self.btnLabelAdd)
        self.btnLabelRemove = QtWidgets.QPushButton(self.frame_2)
        self.btnLabelRemove.setToolTip("")
        self.btnLabelRemove.setObjectName("btnLabelRemove")
        self.horizontalLayout.addWidget(self.btnLabelRemove)
        spacerItem3 = QtWidgets.QSpacerItem(397, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_4.addWidget(self.frame_2)
        self.verticalLayout_5.addWidget(self.groupBox_Labels)
        self.groupBox_Properties = QtWidgets.QGroupBox(self.tabData)
        self.groupBox_Properties.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_Properties.setToolTip("")
        self.groupBox_Properties.setObjectName("groupBox_Properties")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_Properties)
        self.verticalLayout_3.setContentsMargins(1, 1, 1, 0)
        self.verticalLayout_3.setSpacing(1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_5 = QtWidgets.QFrame(self.groupBox_Properties)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridProps = QtWidgets.QTableView(self.frame_5)
        self.gridProps.setMinimumSize(QtCore.QSize(0, 0))
        self.gridProps.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridProps.setObjectName("gridProps")
        self.horizontalLayout_4.addWidget(self.gridProps)
        self.frame_3 = QtWidgets.QFrame(self.frame_5)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnPropUp = QtWidgets.QToolButton(self.frame_3)
        self.btnPropUp.setObjectName("btnPropUp")
        self.verticalLayout_2.addWidget(self.btnPropUp)
        self.btnPropDown = QtWidgets.QToolButton(self.frame_3)
        self.btnPropDown.setObjectName("btnPropDown")
        self.verticalLayout_2.addWidget(self.btnPropDown)
        spacerItem4 = QtWidgets.QSpacerItem(20, 121, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.horizontalLayout_4.addWidget(self.frame_3)
        self.verticalLayout_3.addWidget(self.frame_5)
        self.frame_4 = QtWidgets.QFrame(self.groupBox_Properties)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnPropAdd = QtWidgets.QPushButton(self.frame_4)
        self.btnPropAdd.setToolTip("")
        self.btnPropAdd.setObjectName("btnPropAdd")
        self.horizontalLayout_2.addWidget(self.btnPropAdd)
        self.btnPropRemove = QtWidgets.QPushButton(self.frame_4)
        self.btnPropRemove.setToolTip("")
        self.btnPropRemove.setObjectName("btnPropRemove")
        self.horizontalLayout_2.addWidget(self.btnPropRemove)
        self.btnMakeNull = QtWidgets.QPushButton(self.frame_4)
        self.btnMakeNull.setObjectName("btnMakeNull")
        self.horizontalLayout_2.addWidget(self.btnMakeNull)
        spacerItem5 = QtWidgets.QSpacerItem(286, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.verticalLayout_5.addWidget(self.groupBox_Properties)
        self.tabNodeInspector.addTab(self.tabData, "")
        self.tabDescription = QtWidgets.QWidget()
        self.tabDescription.setObjectName("tabDescription")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tabDescription)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gboxIDs = QtWidgets.QGroupBox(self.tabDescription)
        self.gboxIDs.setObjectName("gboxIDs")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gboxIDs)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.gboxIDs)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.editNZID = QtWidgets.QLineEdit(self.gboxIDs)
        self.editNZID.setAcceptDrops(False)
        self.editNZID.setReadOnly(False)
        self.editNZID.setObjectName("editNZID")
        self.gridLayout_2.addWidget(self.editNZID, 0, 1, 2, 1)
        spacerItem6 = QtWidgets.QSpacerItem(318, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 0, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(318, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 1, 2, 2, 1)
        self.label_2 = QtWidgets.QLabel(self.gboxIDs)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.editNeoID = QtWidgets.QLineEdit(self.gboxIDs)
        self.editNeoID.setReadOnly(False)
        self.editNeoID.setObjectName("editNeoID")
        self.gridLayout_2.addWidget(self.editNeoID, 2, 1, 1, 1)
        self.verticalLayout_6.addWidget(self.gboxIDs)
        self.boxDescription = QtWidgets.QGroupBox(self.tabDescription)
        self.boxDescription.setObjectName("boxDescription")
        self.gridLayout = QtWidgets.QGridLayout(self.boxDescription)
        self.gridLayout.setObjectName("gridLayout")
        self.brwsrGeneratedDesc = QtWidgets.QTextBrowser(self.boxDescription)
        self.brwsrGeneratedDesc.setReadOnly(True)
        self.brwsrGeneratedDesc.setObjectName("brwsrGeneratedDesc")
        self.gridLayout.addWidget(self.brwsrGeneratedDesc, 0, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.boxDescription)
        self.tabNodeInspector.addTab(self.tabDescription, "")
        self.gridLayout_3.addWidget(self.tabNodeInspector, 1, 0, 1, 1)
        self.boxTemplate = QtWidgets.QFrame(INPropertyBox)
        self.boxTemplate.setObjectName("boxTemplate")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.boxTemplate)
        self.horizontalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblTemplate = QtWidgets.QLabel(self.boxTemplate)
        self.lblTemplate.setObjectName("lblTemplate")
        self.horizontalLayout_3.addWidget(self.lblTemplate)
        self.cboTemplate = QtWidgets.QComboBox(self.boxTemplate)
        self.cboTemplate.setMinimumSize(QtCore.QSize(204, 0))
        self.cboTemplate.setObjectName("cboTemplate")
        self.horizontalLayout_3.addWidget(self.cboTemplate)
        spacerItem8 = QtWidgets.QSpacerItem(49, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.btnCreateTemplate = QtWidgets.QPushButton(self.boxTemplate)
        self.btnCreateTemplate.setObjectName("btnCreateTemplate")
        self.horizontalLayout_3.addWidget(self.btnCreateTemplate)
        self.gridLayout_3.addWidget(self.boxTemplate, 0, 0, 1, 1)
        self.label.setBuddy(self.editNZID)
        self.label_2.setBuddy(self.editNeoID)

        self.retranslateUi(INPropertyBox)
        self.tabNodeInspector.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(INPropertyBox)
        INPropertyBox.setTabOrder(self.cboTemplate, self.btnCreateTemplate)
        INPropertyBox.setTabOrder(self.btnCreateTemplate, self.tabNodeInspector)
        INPropertyBox.setTabOrder(self.tabNodeInspector, self.gridLabels)
        INPropertyBox.setTabOrder(self.gridLabels, self.btnLabelUp)
        INPropertyBox.setTabOrder(self.btnLabelUp, self.btnLabelDown)
        INPropertyBox.setTabOrder(self.btnLabelDown, self.btnLabelAdd)
        INPropertyBox.setTabOrder(self.btnLabelAdd, self.btnLabelRemove)
        INPropertyBox.setTabOrder(self.btnLabelRemove, self.gridProps)
        INPropertyBox.setTabOrder(self.gridProps, self.btnPropUp)
        INPropertyBox.setTabOrder(self.btnPropUp, self.btnPropDown)
        INPropertyBox.setTabOrder(self.btnPropDown, self.btnPropAdd)
        INPropertyBox.setTabOrder(self.btnPropAdd, self.btnPropRemove)
        INPropertyBox.setTabOrder(self.btnPropRemove, self.btnMakeNull)
        INPropertyBox.setTabOrder(self.btnMakeNull, self.okButton)
        INPropertyBox.setTabOrder(self.okButton, self.cancelButton)
        INPropertyBox.setTabOrder(self.cancelButton, self.editNZID)
        INPropertyBox.setTabOrder(self.editNZID, self.editNeoID)
        INPropertyBox.setTabOrder(self.editNeoID, self.brwsrGeneratedDesc)

    def retranslateUi(self, INPropertyBox):
        _translate = QtCore.QCoreApplication.translate
        INPropertyBox.setWindowTitle(_translate("INPropertyBox", "Instance Node Inspector"))
        self.okButton.setText(_translate("INPropertyBox", "&OK"))
        self.cancelButton.setText(_translate("INPropertyBox", "&Cancel"))
        self.groupBox_Labels.setTitle(_translate("INPropertyBox", "Labels"))
        self.btnLabelUp.setText(_translate("INPropertyBox", "UP"))
        self.btnLabelDown.setText(_translate("INPropertyBox", "DN"))
        self.btnLabelAdd.setText(_translate("INPropertyBox", "Add"))
        self.btnLabelRemove.setText(_translate("INPropertyBox", "Remove"))
        self.groupBox_Properties.setTitle(_translate("INPropertyBox", "Properties"))
        self.btnPropUp.setText(_translate("INPropertyBox", "UP"))
        self.btnPropDown.setText(_translate("INPropertyBox", "DN"))
        self.btnPropAdd.setText(_translate("INPropertyBox", "Add"))
        self.btnPropRemove.setText(_translate("INPropertyBox", "Remove"))
        self.btnMakeNull.setText(_translate("INPropertyBox", "Set Value Null"))
        self.tabNodeInspector.setTabText(self.tabNodeInspector.indexOf(self.tabData), _translate("INPropertyBox", "Definition"))
        self.gboxIDs.setTitle(_translate("INPropertyBox", "Node IDs"))
        self.label.setText(_translate("INPropertyBox", "NZID :"))
        self.label_2.setText(_translate("INPropertyBox", "Neo4j ID:"))
        self.boxDescription.setTitle(_translate("INPropertyBox", "Description from template"))
        self.tabNodeInspector.setTabText(self.tabNodeInspector.indexOf(self.tabDescription), _translate("INPropertyBox", "Description"))
        self.lblTemplate.setText(_translate("INPropertyBox", "Node Template Name:"))
        self.btnCreateTemplate.setText(_translate("INPropertyBox", "Create New Template"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    INPropertyBox = QtWidgets.QDialog()
    ui = Ui_INPropertyBox()
    ui.setupUi(INPropertyBox)
    INPropertyBox.show()
    sys.exit(app.exec_())
