# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Jsing\OneDrive\Documents\DEV_LAPTOP_LOCAL_REPO\NODEERA\forms\LicenseMgtDLG.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LicenseMgtDLG(object):
    def setupUi(self, LicenseMgtDLG):
        LicenseMgtDLG.setObjectName("LicenseMgtDLG")
        LicenseMgtDLG.resize(592, 354)
        LicenseMgtDLG.setSizeGripEnabled(True)
        self.gridLayout = QtWidgets.QGridLayout(LicenseMgtDLG)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(LicenseMgtDLG)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 4)
        spacerItem = QtWidgets.QSpacerItem(244, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.lblProductName = QtWidgets.QLabel(self.frame_3)
        self.lblProductName.setText("")
        self.lblProductName.setObjectName("lblProductName")
        self.gridLayout_2.addWidget(self.lblProductName, 1, 2, 1, 3)
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.lblLicensedTo = QtWidgets.QLabel(self.frame_3)
        self.lblLicensedTo.setText("")
        self.lblLicensedTo.setObjectName("lblLicensedTo")
        self.gridLayout_2.addWidget(self.lblLicensedTo, 2, 2, 1, 3)
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 2)
        self.lblLicensedToEmail = QtWidgets.QLabel(self.frame_3)
        self.lblLicensedToEmail.setText("")
        self.lblLicensedToEmail.setObjectName("lblLicensedToEmail")
        self.gridLayout_2.addWidget(self.lblLicensedToEmail, 3, 2, 1, 3)
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 4, 0, 1, 1)
        self.txtLicenseKey = QtWidgets.QLineEdit(self.frame_3)
        self.txtLicenseKey.setObjectName("txtLicenseKey")
        self.gridLayout_2.addWidget(self.txtLicenseKey, 4, 1, 1, 4)
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 5, 0, 1, 1)
        self.lblExpiration = QtWidgets.QLabel(self.frame_3)
        self.lblExpiration.setText("")
        self.lblExpiration.setObjectName("lblExpiration")
        self.gridLayout_2.addWidget(self.lblExpiration, 5, 2, 1, 3)
        self.label_7 = QtWidgets.QLabel(self.frame_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 6, 0, 1, 1)
        self.lblLicenseStatus = QtWidgets.QLabel(self.frame_3)
        self.lblLicenseStatus.setText("")
        self.lblLicenseStatus.setObjectName("lblLicenseStatus")
        self.gridLayout_2.addWidget(self.lblLicenseStatus, 6, 2, 1, 3)
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 7, 0, 1, 3)
        self.lblCurrentVersion = QtWidgets.QLabel(self.frame_3)
        self.lblCurrentVersion.setText("")
        self.lblCurrentVersion.setObjectName("lblCurrentVersion")
        self.gridLayout_2.addWidget(self.lblCurrentVersion, 7, 4, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 8, 0, 1, 3)
        self.lblAvailableVersion = QtWidgets.QLabel(self.frame_3)
        self.lblAvailableVersion.setText("")
        self.lblAvailableVersion.setObjectName("lblAvailableVersion")
        self.gridLayout_2.addWidget(self.lblAvailableVersion, 8, 3, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 302, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 9, 0, 1, 2)
        self.horizontalLayout.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnCheck = QtWidgets.QPushButton(self.frame_2)
        self.btnCheck.setObjectName("btnCheck")
        self.verticalLayout.addWidget(self.btnCheck)
        self.btnActivateLicKey = QtWidgets.QPushButton(self.frame_2)
        self.btnActivateLicKey.setObjectName("btnActivateLicKey")
        self.verticalLayout.addWidget(self.btnActivateLicKey)
        self.btnDeactivateLicKey = QtWidgets.QPushButton(self.frame_2)
        self.btnDeactivateLicKey.setObjectName("btnDeactivateLicKey")
        self.verticalLayout.addWidget(self.btnDeactivateLicKey)
        spacerItem2 = QtWidgets.QSpacerItem(20, 223, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.lblProgress = QtWidgets.QLabel(self.frame_2)
        self.lblProgress.setFrameShape(QtWidgets.QFrame.Box)
        self.lblProgress.setText("")
        self.lblProgress.setObjectName("lblProgress")
        self.verticalLayout.addWidget(self.lblProgress)
        self.horizontalLayout.addWidget(self.frame_2)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(LicenseMgtDLG)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(255, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.btnClose = QtWidgets.QPushButton(self.frame_4)
        self.btnClose.setObjectName("btnClose")
        self.horizontalLayout_2.addWidget(self.btnClose)
        spacerItem4 = QtWidgets.QSpacerItem(255, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.gridLayout.addWidget(self.frame_4, 1, 0, 1, 1)
        self.label_5.setBuddy(self.txtLicenseKey)

        self.retranslateUi(LicenseMgtDLG)
        QtCore.QMetaObject.connectSlotsByName(LicenseMgtDLG)
        LicenseMgtDLG.setTabOrder(self.txtLicenseKey, self.btnCheck)
        LicenseMgtDLG.setTabOrder(self.btnCheck, self.btnActivateLicKey)
        LicenseMgtDLG.setTabOrder(self.btnActivateLicKey, self.btnDeactivateLicKey)
        LicenseMgtDLG.setTabOrder(self.btnDeactivateLicKey, self.btnClose)

    def retranslateUi(self, LicenseMgtDLG):
        _translate = QtCore.QCoreApplication.translate
        LicenseMgtDLG.setWindowTitle(_translate("LicenseMgtDLG", "License Management"))
        self.label.setText(_translate("LicenseMgtDLG", "NodeEra License"))
        self.label_2.setText(_translate("LicenseMgtDLG", "Product Name:"))
        self.label_3.setText(_translate("LicenseMgtDLG", "Licensed To:"))
        self.label_4.setText(_translate("LicenseMgtDLG", "Licensed To Email:"))
        self.label_5.setText(_translate("LicenseMgtDLG", "License Key:"))
        self.label_6.setText(_translate("LicenseMgtDLG", "Expiration Date: "))
        self.label_7.setText(_translate("LicenseMgtDLG", "Status: "))
        self.label_8.setText(_translate("LicenseMgtDLG", "Currently Installed Version:"))
        self.label_9.setText(_translate("LicenseMgtDLG", "Latest Available Version:"))
        self.btnCheck.setText(_translate("LicenseMgtDLG", "Check Version"))
        self.btnActivateLicKey.setText(_translate("LicenseMgtDLG", "Activate License Key..."))
        self.btnDeactivateLicKey.setText(_translate("LicenseMgtDLG", "Deactivate License Key..."))
        self.btnClose.setText(_translate("LicenseMgtDLG", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LicenseMgtDLG = QtWidgets.QDialog()
    ui = Ui_LicenseMgtDLG()
    ui.setupUi(LicenseMgtDLG)
    LicenseMgtDLG.show()
    sys.exit(app.exec_())
