# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Jsing\OneDrive\Documents\DEV_LAPTOP_LOCAL_REPO\NODEERA\forms\main.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NodeeraMain(object):
    def setupUi(self, NodeeraMain):
        NodeeraMain.setObjectName("NodeeraMain")
        NodeeraMain.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/FILE/FILE/logo32x32.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        NodeeraMain.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(NodeeraMain)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stackedPageItems = QtWidgets.QStackedWidget(self.centralWidget)
        self.stackedPageItems.setObjectName("stackedPageItems")
        self.horizontalLayout.addWidget(self.stackedPageItems)
        NodeeraMain.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(NodeeraMain)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuNeo = QtWidgets.QMenu(self.menuBar)
        self.menuNeo.setObjectName("menuNeo")
        self.menuSettings = QtWidgets.QMenu(self.menuBar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuProject = QtWidgets.QMenu(self.menuBar)
        self.menuProject.setObjectName("menuProject")
        self.menuRecent_Projects = QtWidgets.QMenu(self.menuProject)
        self.menuRecent_Projects.setObjectName("menuRecent_Projects")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        NodeeraMain.setMenuBar(self.menuBar)
        self.tbConnection = QtWidgets.QToolBar(NodeeraMain)
        self.tbConnection.setMovable(False)
        self.tbConnection.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbConnection.setFloatable(False)
        self.tbConnection.setObjectName("tbConnection")
        NodeeraMain.addToolBar(QtCore.Qt.TopToolBarArea, self.tbConnection)
        self.statusBar = QtWidgets.QStatusBar(NodeeraMain)
        self.statusBar.setObjectName("statusBar")
        NodeeraMain.setStatusBar(self.statusBar)
        self.actionOpen_Connection = QtWidgets.QAction(NodeeraMain)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:\\Users\\Jsing\\OneDrive\\Documents\\DEV_LAPTOP_LOCAL_REPO\\NODEERA\\forms\\../../icons/RUN and DATA TAB/Disconnected.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_Connection.setIcon(icon1)
        self.actionOpen_Connection.setObjectName("actionOpen_Connection")
        self.actionClose_Connection = QtWidgets.QAction(NodeeraMain)
        self.actionClose_Connection.setObjectName("actionClose_Connection")
        self.actionNeo4j_Connection_Manager = QtWidgets.QAction(NodeeraMain)
        self.actionNeo4j_Connection_Manager.setObjectName("actionNeo4j_Connection_Manager")
        self.actionExit = QtWidgets.QAction(NodeeraMain)
        self.actionExit.setObjectName("actionExit")
        self.actionSystem_Preferences = QtWidgets.QAction(NodeeraMain)
        self.actionSystem_Preferences.setObjectName("actionSystem_Preferences")
        self.actionNewProject = QtWidgets.QAction(NodeeraMain)
        self.actionNewProject.setObjectName("actionNewProject")
        self.actionOpenProject = QtWidgets.QAction(NodeeraMain)
        self.actionOpenProject.setObjectName("actionOpenProject")
        self.actionSaveProject = QtWidgets.QAction(NodeeraMain)
        self.actionSaveProject.setObjectName("actionSaveProject")
        self.actionSaveProjectAs = QtWidgets.QAction(NodeeraMain)
        self.actionSaveProjectAs.setObjectName("actionSaveProjectAs")
        self.actionReverse_Engineer = QtWidgets.QAction(NodeeraMain)
        self.actionReverse_Engineer.setObjectName("actionReverse_Engineer")
        self.actionProjectProperties = QtWidgets.QAction(NodeeraMain)
        self.actionProjectProperties.setObjectName("actionProjectProperties")
        self.actionOnline_Help = QtWidgets.QAction(NodeeraMain)
        self.actionOnline_Help.setObjectName("actionOnline_Help")
        self.actionAbout = QtWidgets.QAction(NodeeraMain)
        self.actionAbout.setObjectName("actionAbout")
        self.actionGenerate_Schema = QtWidgets.QAction(NodeeraMain)
        self.actionGenerate_Schema.setObjectName("actionGenerate_Schema")
        self.actionForward_Engineer = QtWidgets.QAction(NodeeraMain)
        self.actionForward_Engineer.setObjectName("actionForward_Engineer")
        self.actionLicense_Management = QtWidgets.QAction(NodeeraMain)
        self.actionLicense_Management.setObjectName("actionLicense_Management")
        self.actionGenerate_Reports = QtWidgets.QAction(NodeeraMain)
        self.actionGenerate_Reports.setObjectName("actionGenerate_Reports")
        self.actionReset_User_Password = QtWidgets.QAction(NodeeraMain)
        self.actionReset_User_Password.setObjectName("actionReset_User_Password")
        self.actionRecent1 = QtWidgets.QAction(NodeeraMain)
        self.actionRecent1.setObjectName("actionRecent1")
        self.menuNeo.addAction(self.actionOpen_Connection)
        self.menuNeo.addAction(self.actionClose_Connection)
        self.menuNeo.addSeparator()
        self.menuNeo.addAction(self.actionGenerate_Schema)
        self.menuNeo.addAction(self.actionReset_User_Password)
        self.menuNeo.addSeparator()
        self.menuNeo.addAction(self.actionNeo4j_Connection_Manager)
        self.menuNeo.addSeparator()
        self.menuNeo.addAction(self.actionExit)
        self.menuSettings.addAction(self.actionSystem_Preferences)
        self.menuSettings.addAction(self.actionLicense_Management)
        self.menuProject.addAction(self.actionNewProject)
        self.menuProject.addAction(self.actionOpenProject)
        self.menuProject.addAction(self.menuRecent_Projects.menuAction())
        self.menuProject.addSeparator()
        self.menuProject.addAction(self.actionSaveProject)
        self.menuProject.addAction(self.actionSaveProjectAs)
        self.menuProject.addSeparator()
        self.menuProject.addAction(self.actionReverse_Engineer)
        self.menuProject.addAction(self.actionForward_Engineer)
        self.menuProject.addAction(self.actionGenerate_Reports)
        self.menuProject.addSeparator()
        self.menuProject.addAction(self.actionProjectProperties)
        self.menuHelp.addAction(self.actionOnline_Help)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuBar.addAction(self.menuNeo.menuAction())
        self.menuBar.addAction(self.menuProject.menuAction())
        self.menuBar.addAction(self.menuSettings.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.tbConnection.addAction(self.actionOpen_Connection)
        self.tbConnection.addSeparator()

        self.retranslateUi(NodeeraMain)
        self.stackedPageItems.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(NodeeraMain)

    def retranslateUi(self, NodeeraMain):
        _translate = QtCore.QCoreApplication.translate
        NodeeraMain.setWindowTitle(_translate("NodeeraMain", "NodeEra"))
        self.menuNeo.setTitle(_translate("NodeeraMain", "Schema"))
        self.menuSettings.setTitle(_translate("NodeeraMain", "Settings"))
        self.menuProject.setTitle(_translate("NodeeraMain", "Project"))
        self.menuRecent_Projects.setTitle(_translate("NodeeraMain", "Recent Projects"))
        self.menuHelp.setTitle(_translate("NodeeraMain", "Help"))
        self.tbConnection.setWindowTitle(_translate("NodeeraMain", "toolBar"))
        self.actionOpen_Connection.setText(_translate("NodeeraMain", "Open Connection..."))
        self.actionClose_Connection.setText(_translate("NodeeraMain", "Close Connection"))
        self.actionNeo4j_Connection_Manager.setText(_translate("NodeeraMain", "Neo4j Connection Manager..."))
        self.actionExit.setText(_translate("NodeeraMain", "Exit"))
        self.actionExit.setShortcut(_translate("NodeeraMain", "Ctrl+X"))
        self.actionSystem_Preferences.setText(_translate("NodeeraMain", "System Preferences..."))
        self.actionNewProject.setText(_translate("NodeeraMain", "New"))
        self.actionOpenProject.setText(_translate("NodeeraMain", "Open..."))
        self.actionOpenProject.setShortcut(_translate("NodeeraMain", "Ctrl+O"))
        self.actionSaveProject.setText(_translate("NodeeraMain", "Save"))
        self.actionSaveProject.setShortcut(_translate("NodeeraMain", "Ctrl+S"))
        self.actionSaveProjectAs.setText(_translate("NodeeraMain", "Save As..."))
        self.actionSaveProjectAs.setShortcut(_translate("NodeeraMain", "Ctrl+A"))
        self.actionReverse_Engineer.setText(_translate("NodeeraMain", "Reverse Engineer..."))
        self.actionProjectProperties.setText(_translate("NodeeraMain", "Properties..."))
        self.actionOnline_Help.setText(_translate("NodeeraMain", "Online Help..."))
        self.actionAbout.setText(_translate("NodeeraMain", "About..."))
        self.actionGenerate_Schema.setText(_translate("NodeeraMain", "Generate Schema..."))
        self.actionForward_Engineer.setText(_translate("NodeeraMain", "Forward Engineer..."))
        self.actionLicense_Management.setText(_translate("NodeeraMain", "License Management..."))
        self.actionGenerate_Reports.setText(_translate("NodeeraMain", "Generate HTML Dictionary..."))
        self.actionReset_User_Password.setText(_translate("NodeeraMain", "Reset User Password..."))
        self.actionRecent1.setText(_translate("NodeeraMain", "Recent1"))
import icons.icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NodeeraMain = QtWidgets.QMainWindow()
    ui = Ui_NodeeraMain()
    ui.setupUi(NodeeraMain)
    NodeeraMain.show()
    sys.exit(app.exec_())
