# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Jsing\OneDrive\Documents\DEV_LAPTOP_LOCAL_REPO\NODEERA\forms\NodePropertyBox.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NodePropertyBox(object):
    def setupUi(self, NodePropertyBox):
        NodePropertyBox.setObjectName("NodePropertyBox")
        NodePropertyBox.setWindowModality(QtCore.Qt.ApplicationModal)
        NodePropertyBox.resize(1290, 698)
        NodePropertyBox.setSizeGripEnabled(True)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(NodePropertyBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_5 = QtWidgets.QFrame(NodePropertyBox)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_5)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.editName = QtWidgets.QLineEdit(self.frame_5)
        self.editName.setObjectName("editName")
        self.horizontalLayout_3.addWidget(self.editName)
        spacerItem = QtWidgets.QSpacerItem(68, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_3.addWidget(self.frame_5)
        self.tabNodeTemplate = QtWidgets.QTabWidget(NodePropertyBox)
        self.tabNodeTemplate.setObjectName("tabNodeTemplate")
        self.tabDefinition = QtWidgets.QWidget()
        self.tabDefinition.setObjectName("tabDefinition")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tabDefinition)
        self.horizontalLayout_4.setContentsMargins(-1, 6, -1, 1)
        self.horizontalLayout_4.setSpacing(1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.splitter = QtWidgets.QSplitter(self.tabDefinition)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.groupBox_Labels = QtWidgets.QGroupBox(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_Labels.sizePolicy().hasHeightForWidth())
        self.groupBox_Labels.setSizePolicy(sizePolicy)
        self.groupBox_Labels.setMinimumSize(QtCore.QSize(0, 180))
        self.groupBox_Labels.setToolTip("")
        self.groupBox_Labels.setObjectName("groupBox_Labels")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_Labels)
        self.gridLayout_2.setContentsMargins(-1, 3, -1, 1)
        self.gridLayout_2.setSpacing(1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.groupBox_Labels)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLabels = QtWidgets.QTableView(self.frame_2)
        self.gridLabels.setMinimumSize(QtCore.QSize(0, 0))
        self.gridLabels.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridLabels.setObjectName("gridLabels")
        self.horizontalLayout.addWidget(self.gridLabels)
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnLabelUp = QtWidgets.QToolButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLabelUp.sizePolicy().hasHeightForWidth())
        self.btnLabelUp.setSizePolicy(sizePolicy)
        self.btnLabelUp.setObjectName("btnLabelUp")
        self.verticalLayout.addWidget(self.btnLabelUp)
        self.btnLabelDown = QtWidgets.QToolButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLabelDown.sizePolicy().hasHeightForWidth())
        self.btnLabelDown.setSizePolicy(sizePolicy)
        self.btnLabelDown.setObjectName("btnLabelDown")
        self.verticalLayout.addWidget(self.btnLabelDown)
        self.btnLabelAdd = QtWidgets.QPushButton(self.frame)
        self.btnLabelAdd.setToolTip("")
        self.btnLabelAdd.setObjectName("btnLabelAdd")
        self.verticalLayout.addWidget(self.btnLabelAdd)
        self.btnLabelRemove = QtWidgets.QPushButton(self.frame)
        self.btnLabelRemove.setToolTip("")
        self.btnLabelRemove.setObjectName("btnLabelRemove")
        self.verticalLayout.addWidget(self.btnLabelRemove)
        spacerItem1 = QtWidgets.QSpacerItem(20, 208, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout.addWidget(self.frame)
        self.gridLayout_2.addWidget(self.frame_2, 0, 0, 1, 1)
        self.groupBox_Properties = QtWidgets.QGroupBox(self.splitter)
        self.groupBox_Properties.setMinimumSize(QtCore.QSize(0, 180))
        self.groupBox_Properties.setToolTip("")
        self.groupBox_Properties.setObjectName("groupBox_Properties")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_Properties)
        self.gridLayout_3.setContentsMargins(-1, 1, -1, 1)
        self.gridLayout_3.setSpacing(1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_8 = QtWidgets.QFrame(self.groupBox_Properties)
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_2.setSpacing(1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridProps = QtWidgets.QTableView(self.frame_8)
        self.gridProps.setMinimumSize(QtCore.QSize(0, 0))
        self.gridProps.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridProps.setObjectName("gridProps")
        self.horizontalLayout_2.addWidget(self.gridProps)
        self.frame_3 = QtWidgets.QFrame(self.frame_8)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnPropUp = QtWidgets.QToolButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPropUp.sizePolicy().hasHeightForWidth())
        self.btnPropUp.setSizePolicy(sizePolicy)
        self.btnPropUp.setObjectName("btnPropUp")
        self.verticalLayout_2.addWidget(self.btnPropUp)
        self.btnPropDown = QtWidgets.QToolButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPropDown.sizePolicy().hasHeightForWidth())
        self.btnPropDown.setSizePolicy(sizePolicy)
        self.btnPropDown.setObjectName("btnPropDown")
        self.verticalLayout_2.addWidget(self.btnPropDown)
        self.btnPropAdd = QtWidgets.QPushButton(self.frame_3)
        self.btnPropAdd.setToolTip("")
        self.btnPropAdd.setObjectName("btnPropAdd")
        self.verticalLayout_2.addWidget(self.btnPropAdd)
        self.btnPropRemove = QtWidgets.QPushButton(self.frame_3)
        self.btnPropRemove.setToolTip("")
        self.btnPropRemove.setObjectName("btnPropRemove")
        self.verticalLayout_2.addWidget(self.btnPropRemove)
        self.btnSetDefaultNull = QtWidgets.QPushButton(self.frame_3)
        self.btnSetDefaultNull.setObjectName("btnSetDefaultNull")
        self.verticalLayout_2.addWidget(self.btnSetDefaultNull)
        spacerItem2 = QtWidgets.QSpacerItem(20, 89, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.gridLayout_3.addWidget(self.frame_8, 0, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.splitter)
        self.tabNodeTemplate.addTab(self.tabDefinition, "")
        self.tabConstraint = QtWidgets.QWidget()
        self.tabConstraint.setObjectName("tabConstraint")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tabConstraint)
        self.verticalLayout_10.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_10.setSpacing(5)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.groupBox = QtWidgets.QGroupBox(self.tabConstraint)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_6.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_6.setSpacing(1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.gridConstraints = QtWidgets.QTableView(self.groupBox)
        self.gridConstraints.setObjectName("gridConstraints")
        self.horizontalLayout_6.addWidget(self.gridConstraints)
        self.frame_4 = QtWidgets.QFrame(self.groupBox)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.btnAddConstraint = QtWidgets.QPushButton(self.frame_4)
        self.btnAddConstraint.setObjectName("btnAddConstraint")
        self.verticalLayout_8.addWidget(self.btnAddConstraint)
        self.btnRemoveConstraint = QtWidgets.QPushButton(self.frame_4)
        self.btnRemoveConstraint.setObjectName("btnRemoveConstraint")
        self.verticalLayout_8.addWidget(self.btnRemoveConstraint)
        spacerItem3 = QtWidgets.QSpacerItem(20, 179, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem3)
        self.horizontalLayout_6.addWidget(self.frame_4)
        self.verticalLayout_10.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tabConstraint)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_7.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.gridIndex = QtWidgets.QTableView(self.groupBox_2)
        self.gridIndex.setObjectName("gridIndex")
        self.horizontalLayout_7.addWidget(self.gridIndex)
        self.frame_9 = QtWidgets.QFrame(self.groupBox_2)
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.btnAddIndex = QtWidgets.QPushButton(self.frame_9)
        self.btnAddIndex.setObjectName("btnAddIndex")
        self.verticalLayout_9.addWidget(self.btnAddIndex)
        self.btnRemoveIndex = QtWidgets.QPushButton(self.frame_9)
        self.btnRemoveIndex.setObjectName("btnRemoveIndex")
        self.verticalLayout_9.addWidget(self.btnRemoveIndex)
        spacerItem4 = QtWidgets.QSpacerItem(20, 179, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem4)
        self.horizontalLayout_7.addWidget(self.frame_9)
        self.verticalLayout_10.addWidget(self.groupBox_2)
        self.tabNodeTemplate.addTab(self.tabConstraint, "")
        self.tabDescription = QtWidgets.QWidget()
        self.tabDescription.setObjectName("tabDescription")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.tabDescription)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_2 = QtWidgets.QLabel(self.tabDescription)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_11.addWidget(self.label_2)
        self.editDescription = QtWidgets.QPlainTextEdit(self.tabDescription)
        self.editDescription.setMaximumSize(QtCore.QSize(16777215, 100))
        self.editDescription.setObjectName("editDescription")
        self.verticalLayout_11.addWidget(self.editDescription)
        self.label_4 = QtWidgets.QLabel(self.tabDescription)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_11.addWidget(self.label_4)
        self.brwsrGenDescription = QtWidgets.QTextBrowser(self.tabDescription)
        self.brwsrGenDescription.setObjectName("brwsrGenDescription")
        self.verticalLayout_11.addWidget(self.brwsrGenDescription)
        self.tabNodeTemplate.addTab(self.tabDescription, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.grpboxTemplateFormat = QtWidgets.QGroupBox(self.tab)
        self.grpboxTemplateFormat.setObjectName("grpboxTemplateFormat")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.grpboxTemplateFormat)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.rbTemplateDefaultFormat = QtWidgets.QRadioButton(self.grpboxTemplateFormat)
        self.rbTemplateDefaultFormat.setMinimumSize(QtCore.QSize(110, 0))
        self.rbTemplateDefaultFormat.setChecked(True)
        self.rbTemplateDefaultFormat.setObjectName("rbTemplateDefaultFormat")
        self.horizontalLayout_8.addWidget(self.rbTemplateDefaultFormat)
        self.rbTemplateCustomFormat = QtWidgets.QRadioButton(self.grpboxTemplateFormat)
        self.rbTemplateCustomFormat.setMinimumSize(QtCore.QSize(110, 0))
        self.rbTemplateCustomFormat.setObjectName("rbTemplateCustomFormat")
        self.horizontalLayout_8.addWidget(self.rbTemplateCustomFormat)
        self.btnDefineTemplateFormat = QtWidgets.QPushButton(self.grpboxTemplateFormat)
        self.btnDefineTemplateFormat.setObjectName("btnDefineTemplateFormat")
        self.horizontalLayout_8.addWidget(self.btnDefineTemplateFormat)
        spacerItem5 = QtWidgets.QSpacerItem(162, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.gridLayout.addWidget(self.grpboxTemplateFormat, 0, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(537, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 0, 1, 1, 1)
        self.grpboxInstanceFormat = QtWidgets.QGroupBox(self.tab)
        self.grpboxInstanceFormat.setObjectName("grpboxInstanceFormat")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.grpboxInstanceFormat)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.rbInstanceDefaultFormat = QtWidgets.QRadioButton(self.grpboxInstanceFormat)
        self.rbInstanceDefaultFormat.setMinimumSize(QtCore.QSize(110, 0))
        self.rbInstanceDefaultFormat.setChecked(True)
        self.rbInstanceDefaultFormat.setObjectName("rbInstanceDefaultFormat")
        self.horizontalLayout_9.addWidget(self.rbInstanceDefaultFormat)
        self.rbInstanceCustomFormat = QtWidgets.QRadioButton(self.grpboxInstanceFormat)
        self.rbInstanceCustomFormat.setMinimumSize(QtCore.QSize(110, 0))
        self.rbInstanceCustomFormat.setObjectName("rbInstanceCustomFormat")
        self.horizontalLayout_9.addWidget(self.rbInstanceCustomFormat)
        self.btnDefineInstanceFormat = QtWidgets.QPushButton(self.grpboxInstanceFormat)
        self.btnDefineInstanceFormat.setObjectName("btnDefineInstanceFormat")
        self.horizontalLayout_9.addWidget(self.btnDefineInstanceFormat)
        spacerItem7 = QtWidgets.QSpacerItem(162, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.gridLayout.addWidget(self.grpboxInstanceFormat, 1, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(537, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 1, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 462, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem9, 2, 0, 1, 1)
        self.tabNodeTemplate.addTab(self.tab, "")
        self.tabDataGrid = QtWidgets.QWidget()
        self.tabDataGrid.setObjectName("tabDataGrid")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tabDataGrid)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.dataTabFrame = QtWidgets.QFrame(self.tabDataGrid)
        self.dataTabFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.dataTabFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.dataTabFrame.setObjectName("dataTabFrame")
        self.verticalLayout_7.addWidget(self.dataTabFrame)
        self.tabNodeTemplate.addTab(self.tabDataGrid, "")
        self.verticalLayout_3.addWidget(self.tabNodeTemplate)
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setObjectName("hboxlayout")
        spacerItem10 = QtWidgets.QSpacerItem(71, 31, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem10)
        self.okButton = QtWidgets.QPushButton(NodePropertyBox)
        self.okButton.setObjectName("okButton")
        self.hboxlayout.addWidget(self.okButton)
        self.cancelButton = QtWidgets.QPushButton(NodePropertyBox)
        self.cancelButton.setObjectName("cancelButton")
        self.hboxlayout.addWidget(self.cancelButton)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem11)
        self.verticalLayout_3.addLayout(self.hboxlayout)
        self.label.setBuddy(self.editName)
        self.label_2.setBuddy(self.editDescription)

        self.retranslateUi(NodePropertyBox)
        self.tabNodeTemplate.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(NodePropertyBox)
        NodePropertyBox.setTabOrder(self.editName, self.tabNodeTemplate)
        NodePropertyBox.setTabOrder(self.tabNodeTemplate, self.gridLabels)
        NodePropertyBox.setTabOrder(self.gridLabels, self.btnLabelUp)
        NodePropertyBox.setTabOrder(self.btnLabelUp, self.btnLabelDown)
        NodePropertyBox.setTabOrder(self.btnLabelDown, self.gridProps)
        NodePropertyBox.setTabOrder(self.gridProps, self.btnPropUp)
        NodePropertyBox.setTabOrder(self.btnPropUp, self.btnPropDown)
        NodePropertyBox.setTabOrder(self.btnPropDown, self.btnPropAdd)
        NodePropertyBox.setTabOrder(self.btnPropAdd, self.btnPropRemove)
        NodePropertyBox.setTabOrder(self.btnPropRemove, self.gridConstraints)
        NodePropertyBox.setTabOrder(self.gridConstraints, self.btnAddConstraint)
        NodePropertyBox.setTabOrder(self.btnAddConstraint, self.btnRemoveConstraint)
        NodePropertyBox.setTabOrder(self.btnRemoveConstraint, self.gridIndex)
        NodePropertyBox.setTabOrder(self.gridIndex, self.btnAddIndex)
        NodePropertyBox.setTabOrder(self.btnAddIndex, self.btnRemoveIndex)
        NodePropertyBox.setTabOrder(self.btnRemoveIndex, self.editDescription)
        NodePropertyBox.setTabOrder(self.editDescription, self.brwsrGenDescription)
        NodePropertyBox.setTabOrder(self.brwsrGenDescription, self.rbTemplateDefaultFormat)
        NodePropertyBox.setTabOrder(self.rbTemplateDefaultFormat, self.rbTemplateCustomFormat)
        NodePropertyBox.setTabOrder(self.rbTemplateCustomFormat, self.btnDefineTemplateFormat)
        NodePropertyBox.setTabOrder(self.btnDefineTemplateFormat, self.rbInstanceDefaultFormat)
        NodePropertyBox.setTabOrder(self.rbInstanceDefaultFormat, self.rbInstanceCustomFormat)
        NodePropertyBox.setTabOrder(self.rbInstanceCustomFormat, self.btnDefineInstanceFormat)
        NodePropertyBox.setTabOrder(self.btnDefineInstanceFormat, self.okButton)
        NodePropertyBox.setTabOrder(self.okButton, self.cancelButton)

    def retranslateUi(self, NodePropertyBox):
        _translate = QtCore.QCoreApplication.translate
        NodePropertyBox.setWindowTitle(_translate("NodePropertyBox", "Node Template Editor"))
        self.label.setText(_translate("NodePropertyBox", "Name:"))
        self.groupBox_Labels.setTitle(_translate("NodePropertyBox", "Labels"))
        self.btnLabelUp.setText(_translate("NodePropertyBox", "Up"))
        self.btnLabelDown.setText(_translate("NodePropertyBox", "Down"))
        self.btnLabelAdd.setText(_translate("NodePropertyBox", "Add"))
        self.btnLabelRemove.setText(_translate("NodePropertyBox", "Remove"))
        self.groupBox_Properties.setTitle(_translate("NodePropertyBox", "Properties"))
        self.btnPropUp.setText(_translate("NodePropertyBox", "Up"))
        self.btnPropDown.setText(_translate("NodePropertyBox", "Down"))
        self.btnPropAdd.setText(_translate("NodePropertyBox", "Add"))
        self.btnPropRemove.setText(_translate("NodePropertyBox", "Remove"))
        self.btnSetDefaultNull.setText(_translate("NodePropertyBox", "Set Default Null"))
        self.tabNodeTemplate.setTabText(self.tabNodeTemplate.indexOf(self.tabDefinition), _translate("NodePropertyBox", "Definition"))
        self.groupBox.setTitle(_translate("NodePropertyBox", "Constraints"))
        self.btnAddConstraint.setText(_translate("NodePropertyBox", "Add"))
        self.btnRemoveConstraint.setText(_translate("NodePropertyBox", "Remove"))
        self.groupBox_2.setTitle(_translate("NodePropertyBox", "Indexes"))
        self.btnAddIndex.setText(_translate("NodePropertyBox", "Add"))
        self.btnRemoveIndex.setText(_translate("NodePropertyBox", "Remove"))
        self.tabNodeTemplate.setTabText(self.tabNodeTemplate.indexOf(self.tabConstraint), _translate("NodePropertyBox", "Constraints"))
        self.label_2.setText(_translate("NodePropertyBox", "Description:"))
        self.label_4.setText(_translate("NodePropertyBox", "Generated Description:"))
        self.tabNodeTemplate.setTabText(self.tabNodeTemplate.indexOf(self.tabDescription), _translate("NodePropertyBox", "Description"))
        self.grpboxTemplateFormat.setTitle(_translate("NodePropertyBox", "Node Template Format"))
        self.rbTemplateDefaultFormat.setText(_translate("NodePropertyBox", "Default Format"))
        self.rbTemplateCustomFormat.setText(_translate("NodePropertyBox", "Custom Format"))
        self.btnDefineTemplateFormat.setText(_translate("NodePropertyBox", "Define Format"))
        self.grpboxInstanceFormat.setTitle(_translate("NodePropertyBox", "Instance Node Format"))
        self.rbInstanceDefaultFormat.setText(_translate("NodePropertyBox", "Default Format"))
        self.rbInstanceCustomFormat.setText(_translate("NodePropertyBox", "Custom Format"))
        self.btnDefineInstanceFormat.setText(_translate("NodePropertyBox", "Define Format"))
        self.tabNodeTemplate.setTabText(self.tabNodeTemplate.indexOf(self.tab), _translate("NodePropertyBox", "Formats"))
        self.tabNodeTemplate.setTabText(self.tabNodeTemplate.indexOf(self.tabDataGrid), _translate("NodePropertyBox", "Data"))
        self.okButton.setText(_translate("NodePropertyBox", "&OK"))
        self.cancelButton.setText(_translate("NodePropertyBox", "&Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NodePropertyBox = QtWidgets.QDialog()
    ui = Ui_NodePropertyBox()
    ui.setupUi(NodePropertyBox)
    NodePropertyBox.show()
    sys.exit(app.exec_())
