# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Jsing\OneDrive\Documents\GIT\NODEERA\forms\OnlineHelpDLG.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OnlineHelpDLG(object):
    def setupUi(self, OnlineHelpDLG):
        OnlineHelpDLG.setObjectName("OnlineHelpDLG")
        OnlineHelpDLG.resize(355, 298)
        OnlineHelpDLG.setSizeGripEnabled(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(OnlineHelpDLG)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(OnlineHelpDLG)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.txtHelp = QtWidgets.QTextBrowser(OnlineHelpDLG)
        self.txtHelp.setObjectName("txtHelp")
        self.verticalLayout.addWidget(self.txtHelp)
        self.frame = QtWidgets.QFrame(OnlineHelpDLG)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(72, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnHelp = QtWidgets.QPushButton(self.frame)
        self.btnHelp.setObjectName("btnHelp")
        self.horizontalLayout.addWidget(self.btnHelp)
        self.btnClose = QtWidgets.QPushButton(self.frame)
        self.btnClose.setObjectName("btnClose")
        self.horizontalLayout.addWidget(self.btnClose)
        spacerItem1 = QtWidgets.QSpacerItem(71, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(OnlineHelpDLG)
        QtCore.QMetaObject.connectSlotsByName(OnlineHelpDLG)

    def retranslateUi(self, OnlineHelpDLG):
        _translate = QtCore.QCoreApplication.translate
        OnlineHelpDLG.setWindowTitle(_translate("OnlineHelpDLG", "Online Help"))
        self.label.setText(_translate("OnlineHelpDLG", "NodeEra Help"))
        self.btnHelp.setText(_translate("OnlineHelpDLG", "Online Help..."))
        self.btnClose.setText(_translate("OnlineHelpDLG", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OnlineHelpDLG = QtWidgets.QDialog()
    ui = Ui_OnlineHelpDLG()
    ui.setupUi(OnlineHelpDLG)
    OnlineHelpDLG.show()
    sys.exit(app.exec_())
