# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Jsing\OneDrive\Documents\DEV_LAPTOP_LOCAL_REPO\NODEERA\forms\projectPageWidget.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProjectPageWidget(object):
    def setupUi(self, ProjectPageWidget):
        ProjectPageWidget.setObjectName("ProjectPageWidget")
        ProjectPageWidget.resize(1062, 722)
        self.gridLayout = QtWidgets.QGridLayout(ProjectPageWidget)
        self.gridLayout.setContentsMargins(-1, 2, -1, 2)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(ProjectPageWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.frame = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.editNeo4j = QtWidgets.QLineEdit(self.frame)
        self.editNeo4j.setReadOnly(True)
        self.editNeo4j.setObjectName("editNeo4j")
        self.verticalLayout.addWidget(self.editNeo4j)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnSave = QtWidgets.QToolButton(self.frame_2)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/FILE/FILE/Save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSave.setIcon(icon)
        self.btnSave.setIconSize(QtCore.QSize(32, 32))
        self.btnSave.setAutoRaise(True)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout_2.addWidget(self.btnSave)
        self.btnSaveAs = QtWidgets.QToolButton(self.frame_2)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/FILE/FILE/Saveas.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSaveAs.setIcon(icon1)
        self.btnSaveAs.setIconSize(QtCore.QSize(32, 32))
        self.btnSaveAs.setAutoRaise(True)
        self.btnSaveAs.setObjectName("btnSaveAs")
        self.horizontalLayout_2.addWidget(self.btnSaveAs)
        self.btnCloseProject = QtWidgets.QToolButton(self.frame_2)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/FILE/FILE/Close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCloseProject.setIcon(icon2)
        self.btnCloseProject.setIconSize(QtCore.QSize(32, 32))
        self.btnCloseProject.setAutoRaise(True)
        self.btnCloseProject.setObjectName("btnCloseProject")
        self.horizontalLayout_2.addWidget(self.btnCloseProject)
        spacerItem = QtWidgets.QSpacerItem(183, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.cbSyncMode = QtWidgets.QCheckBox(self.frame_2)
        self.cbSyncMode.setObjectName("cbSyncMode")
        self.horizontalLayout_2.addWidget(self.cbSyncMode)
        self.verticalLayout.addWidget(self.frame_2)
        self.tvProject = QtWidgets.QTreeWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tvProject.sizePolicy().hasHeightForWidth())
        self.tvProject.setSizePolicy(sizePolicy)
        self.tvProject.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tvProject.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tvProject.setObjectName("tvProject")
        self.tvProject.headerItem().setText(0, "1")
        self.verticalLayout.addWidget(self.tvProject)
        self.frameTab = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(90)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameTab.sizePolicy().hasHeightForWidth())
        self.frameTab.setSizePolicy(sizePolicy)
        self.frameTab.setFrameShape(QtWidgets.QFrame.Panel)
        self.frameTab.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frameTab.setObjectName("frameTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frameTab)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabProject = QtWidgets.QTabWidget(self.frameTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabProject.sizePolicy().hasHeightForWidth())
        self.tabProject.setSizePolicy(sizePolicy)
        self.tabProject.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabProject.setTabsClosable(True)
        self.tabProject.setMovable(True)
        self.tabProject.setObjectName("tabProject")
        self.gridLayout_2.addWidget(self.tabProject, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)

        self.retranslateUi(ProjectPageWidget)
        QtCore.QMetaObject.connectSlotsByName(ProjectPageWidget)
        ProjectPageWidget.setTabOrder(self.editNeo4j, self.btnSave)
        ProjectPageWidget.setTabOrder(self.btnSave, self.btnSaveAs)
        ProjectPageWidget.setTabOrder(self.btnSaveAs, self.btnCloseProject)
        ProjectPageWidget.setTabOrder(self.btnCloseProject, self.cbSyncMode)
        ProjectPageWidget.setTabOrder(self.cbSyncMode, self.tvProject)
        ProjectPageWidget.setTabOrder(self.tvProject, self.tabProject)

    def retranslateUi(self, ProjectPageWidget):
        _translate = QtCore.QCoreApplication.translate
        ProjectPageWidget.setWindowTitle(_translate("ProjectPageWidget", "Form"))
        self.btnSave.setToolTip(_translate("ProjectPageWidget", "Save Project"))
        self.btnSave.setText(_translate("ProjectPageWidget", "Save"))
        self.btnSaveAs.setToolTip(_translate("ProjectPageWidget", "Save Project As..."))
        self.btnSaveAs.setText(_translate("ProjectPageWidget", "Save As"))
        self.btnCloseProject.setToolTip(_translate("ProjectPageWidget", "Close Project"))
        self.btnCloseProject.setText(_translate("ProjectPageWidget", "..."))
        self.cbSyncMode.setText(_translate("ProjectPageWidget", "Sync To DB"))
import icons.icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ProjectPageWidget = QtWidgets.QWidget()
    ui = Ui_ProjectPageWidget()
    ui.setupUi(ProjectPageWidget)
    ProjectPageWidget.show()
    sys.exit(app.exec_())
