# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Jsing\OneDrive\Documents\DEV_LAPTOP_LOCAL_REPO\NODEERA\forms\PathTemplateTab.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PathTemplateTab(object):
    def setupUi(self, PathTemplateTab):
        PathTemplateTab.setObjectName("PathTemplateTab")
        PathTemplateTab.resize(894, 573)
        self.gridLayout_2 = QtWidgets.QGridLayout(PathTemplateTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabPathTemplate = QtWidgets.QTabWidget(PathTemplateTab)
        self.tabPathTemplate.setObjectName("tabPathTemplate")
        self.tabDesign = QtWidgets.QWidget()
        self.tabDesign.setObjectName("tabDesign")
        self.gridLayout = QtWidgets.QGridLayout(self.tabDesign)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(self.tabDesign)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.framePath = QtWidgets.QFrame(self.splitter)
        self.framePath.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framePath.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framePath.setObjectName("framePath")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.framePath)
        self.horizontalLayout_3.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_3.setSpacing(1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.splitter_2 = QtWidgets.QSplitter(self.framePath)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.tvPath = QtWidgets.QTreeWidget(self.splitter_2)
        self.tvPath.setProperty("showDropIndicator", False)
        self.tvPath.setAnimated(True)
        self.tvPath.setObjectName("tvPath")
        self.tvPath.headerItem().setText(0, "1")
        self.frmMetaBox = QtWidgets.QFrame(self.splitter_2)
        self.frmMetaBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmMetaBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmMetaBox.setObjectName("frmMetaBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frmMetaBox)
        self.verticalLayout_3.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_3.setSpacing(1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lblMetaHeader = QtWidgets.QLabel(self.frmMetaBox)
        self.lblMetaHeader.setAlignment(QtCore.Qt.AlignCenter)
        self.lblMetaHeader.setObjectName("lblMetaHeader")
        self.verticalLayout_3.addWidget(self.lblMetaHeader)
        self.gridMetaBox = QtWidgets.QTableView(self.frmMetaBox)
        self.gridMetaBox.setObjectName("gridMetaBox")
        self.gridMetaBox.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.gridMetaBox)
        self.horizontalLayout_3.addWidget(self.splitter_2)
        self.frameOutput = QtWidgets.QFrame(self.splitter)
        self.frameOutput.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameOutput.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameOutput.setObjectName("frameOutput")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frameOutput)
        self.verticalLayout_2.setContentsMargins(1, 1, 1, 3)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridOutput = QtWidgets.QTableView(self.frameOutput)
        self.gridOutput.setObjectName("gridOutput")
        self.verticalLayout_2.addWidget(self.gridOutput)
        self.frame_2 = QtWidgets.QFrame(self.frameOutput)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnAdd = QtWidgets.QPushButton(self.frame_2)
        self.btnAdd.setObjectName("btnAdd")
        self.horizontalLayout_2.addWidget(self.btnAdd)
        self.btnRemove = QtWidgets.QPushButton(self.frame_2)
        self.btnRemove.setObjectName("btnRemove")
        self.horizontalLayout_2.addWidget(self.btnRemove)
        self.btnUp = QtWidgets.QPushButton(self.frame_2)
        self.btnUp.setObjectName("btnUp")
        self.horizontalLayout_2.addWidget(self.btnUp)
        self.btnDown = QtWidgets.QPushButton(self.frame_2)
        self.btnDown.setObjectName("btnDown")
        self.horizontalLayout_2.addWidget(self.btnDown)
        spacerItem = QtWidgets.QSpacerItem(464, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        self.tabPathTemplate.addTab(self.tabDesign, "")
        self.tabCypher = QtWidgets.QWidget()
        self.tabCypher.setObjectName("tabCypher")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tabCypher)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.tabCypher)
        self.frame.setMinimumSize(QtCore.QSize(0, 41))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 41))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnSaveAs = QtWidgets.QPushButton(self.frame)
        self.btnSaveAs.setObjectName("btnSaveAs")
        self.horizontalLayout.addWidget(self.btnSaveAs)
        spacerItem1 = QtWidgets.QSpacerItem(711, 18, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.frame)
        self.frmDataGrid = QtWidgets.QFrame(self.tabCypher)
        self.frmDataGrid.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmDataGrid.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmDataGrid.setObjectName("frmDataGrid")
        self.verticalLayout.addWidget(self.frmDataGrid)
        self.tabPathTemplate.addTab(self.tabCypher, "")
        self.gridLayout_2.addWidget(self.tabPathTemplate, 0, 0, 1, 1)

        self.retranslateUi(PathTemplateTab)
        self.tabPathTemplate.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PathTemplateTab)

    def retranslateUi(self, PathTemplateTab):
        _translate = QtCore.QCoreApplication.translate
        PathTemplateTab.setWindowTitle(_translate("PathTemplateTab", "Form"))
        self.lblMetaHeader.setText(_translate("PathTemplateTab", "Node Definition"))
        self.btnAdd.setText(_translate("PathTemplateTab", "Add New"))
        self.btnRemove.setText(_translate("PathTemplateTab", "Remove"))
        self.btnUp.setText(_translate("PathTemplateTab", "Up"))
        self.btnDown.setText(_translate("PathTemplateTab", "Down"))
        self.tabPathTemplate.setTabText(self.tabPathTemplate.indexOf(self.tabDesign), _translate("PathTemplateTab", "Design"))
        self.btnSaveAs.setText(_translate("PathTemplateTab", "Save As..."))
        self.tabPathTemplate.setTabText(self.tabPathTemplate.indexOf(self.tabCypher), _translate("PathTemplateTab", "Cypher"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PathTemplateTab = QtWidgets.QWidget()
    ui = Ui_PathTemplateTab()
    ui.setupUi(PathTemplateTab)
    PathTemplateTab.show()
    sys.exit(app.exec_())

