# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Jsing\OneDrive\Documents\DEV_LAPTOP_LOCAL_REPO\NODEERA\forms\ProjectPropertyBox.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlgProjectPreferences(object):
    def setupUi(self, dlgProjectPreferences):
        dlgProjectPreferences.setObjectName("dlgProjectPreferences")
        dlgProjectPreferences.setWindowModality(QtCore.Qt.ApplicationModal)
        dlgProjectPreferences.resize(512, 436)
        dlgProjectPreferences.setSizeGripEnabled(False)
        self.gridLayout_8 = QtWidgets.QGridLayout(dlgProjectPreferences)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label = QtWidgets.QLabel(dlgProjectPreferences)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_8.addWidget(self.label, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(360, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem, 0, 1, 1, 1)
        self.frame = QtWidgets.QFrame(dlgProjectPreferences)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frameIndex = QtWidgets.QFrame(self.frame)
        self.frameIndex.setFrameShape(QtWidgets.QFrame.Box)
        self.frameIndex.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameIndex.setObjectName("frameIndex")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frameIndex)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pbGeneral = QtWidgets.QPushButton(self.frameIndex)
        self.pbGeneral.setObjectName("pbGeneral")
        self.verticalLayout.addWidget(self.pbGeneral)
        self.pbPageSettings = QtWidgets.QPushButton(self.frameIndex)
        self.pbPageSettings.setObjectName("pbPageSettings")
        self.verticalLayout.addWidget(self.pbPageSettings)
        self.pbInstanceFormats = QtWidgets.QPushButton(self.frameIndex)
        self.pbInstanceFormats.setObjectName("pbInstanceFormats")
        self.verticalLayout.addWidget(self.pbInstanceFormats)
        self.pbTemplateFormats = QtWidgets.QPushButton(self.frameIndex)
        self.pbTemplateFormats.setObjectName("pbTemplateFormats")
        self.verticalLayout.addWidget(self.pbTemplateFormats)
        self.pbTemplateDiagram = QtWidgets.QPushButton(self.frameIndex)
        self.pbTemplateDiagram.setObjectName("pbTemplateDiagram")
        self.verticalLayout.addWidget(self.pbTemplateDiagram)
        spacerItem1 = QtWidgets.QSpacerItem(20, 158, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout.addWidget(self.frameIndex)
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame)
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.stackedWidget.setObjectName("stackedWidget")
        self.General = QtWidgets.QWidget()
        self.General.setObjectName("General")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.General)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lblGeneral = QtWidgets.QLabel(self.General)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblGeneral.setFont(font)
        self.lblGeneral.setObjectName("lblGeneral")
        self.gridLayout_7.addWidget(self.lblGeneral, 0, 1, 1, 1)
        self.lblAuthor = QtWidgets.QLabel(self.General)
        self.lblAuthor.setObjectName("lblAuthor")
        self.gridLayout_7.addWidget(self.lblAuthor, 1, 0, 1, 1)
        self.txtAuthor = QtWidgets.QLineEdit(self.General)
        self.txtAuthor.setObjectName("txtAuthor")
        self.gridLayout_7.addWidget(self.txtAuthor, 1, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.General)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lblDesc = QtWidgets.QLabel(self.frame_2)
        self.lblDesc.setObjectName("lblDesc")
        self.gridLayout_6.addWidget(self.lblDesc, 0, 0, 1, 1)
        self.txtDescription = QtWidgets.QPlainTextEdit(self.frame_2)
        self.txtDescription.setObjectName("txtDescription")
        self.gridLayout_6.addWidget(self.txtDescription, 0, 1, 2, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 217, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem2, 1, 0, 1, 1)
        self.gridLayout_7.addWidget(self.frame_2, 2, 0, 1, 2)
        self.stackedWidget.addWidget(self.General)
        self.pagePageSettings = QtWidgets.QWidget()
        self.pagePageSettings.setObjectName("pagePageSettings")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.pagePageSettings)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblNodeTemplateFormat_2 = QtWidgets.QLabel(self.pagePageSettings)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblNodeTemplateFormat_2.setFont(font)
        self.lblNodeTemplateFormat_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lblNodeTemplateFormat_2.setObjectName("lblNodeTemplateFormat_2")
        self.verticalLayout_2.addWidget(self.lblNodeTemplateFormat_2)
        self.groupBox = QtWidgets.QGroupBox(self.pagePageSettings)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.cmbPageSize = QtWidgets.QComboBox(self.groupBox)
        self.cmbPageSize.setObjectName("cmbPageSize")
        self.gridLayout_3.addWidget(self.cmbPageSize, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 1, 1, 1)
        self.txtWidth = QtWidgets.QLineEdit(self.groupBox)
        self.txtWidth.setReadOnly(True)
        self.txtWidth.setObjectName("txtWidth")
        self.gridLayout_3.addWidget(self.txtWidth, 0, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(114, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 1, 1, 1)
        self.txtHeight = QtWidgets.QLineEdit(self.groupBox)
        self.txtHeight.setReadOnly(True)
        self.txtHeight.setObjectName("txtHeight")
        self.gridLayout_3.addWidget(self.txtHeight, 1, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.grpOrientation = QtWidgets.QGroupBox(self.pagePageSettings)
        self.grpOrientation.setObjectName("grpOrientation")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.grpOrientation)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.rbPortrait = QtWidgets.QRadioButton(self.grpOrientation)
        self.rbPortrait.setObjectName("rbPortrait")
        self.gridLayout_2.addWidget(self.rbPortrait, 0, 0, 1, 1)
        self.rbLandscape = QtWidgets.QRadioButton(self.grpOrientation)
        self.rbLandscape.setObjectName("rbLandscape")
        self.gridLayout_2.addWidget(self.rbLandscape, 1, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.grpOrientation)
        self.groupBox_2 = QtWidgets.QGroupBox(self.pagePageSettings)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.spinRows = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinRows.setReadOnly(False)
        self.spinRows.setMinimum(1)
        self.spinRows.setMaximum(20)
        self.spinRows.setObjectName("spinRows")
        self.gridLayout.addWidget(self.spinRows, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.spinColumns = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinColumns.setMinimum(1)
        self.spinColumns.setMaximum(20)
        self.spinColumns.setObjectName("spinColumns")
        self.gridLayout.addWidget(self.spinColumns, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.stackedWidget.addWidget(self.pagePageSettings)
        self.pageInstanceFormats = QtWidgets.QWidget()
        self.pageInstanceFormats.setObjectName("pageInstanceFormats")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.pageInstanceFormats)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lblNodeFormat = QtWidgets.QLabel(self.pageInstanceFormats)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblNodeFormat.setFont(font)
        self.lblNodeFormat.setAlignment(QtCore.Qt.AlignCenter)
        self.lblNodeFormat.setObjectName("lblNodeFormat")
        self.verticalLayout_7.addWidget(self.lblNodeFormat)
        self.frmInstanceNodeFormat = QtWidgets.QFrame(self.pageInstanceFormats)
        self.frmInstanceNodeFormat.setFrameShape(QtWidgets.QFrame.Box)
        self.frmInstanceNodeFormat.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frmInstanceNodeFormat.setObjectName("frmInstanceNodeFormat")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frmInstanceNodeFormat)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frmInstanceNodeViewer = QtWidgets.QFrame(self.frmInstanceNodeFormat)
        self.frmInstanceNodeViewer.setMinimumSize(QtCore.QSize(150, 0))
        self.frmInstanceNodeViewer.setFrameShape(QtWidgets.QFrame.Box)
        self.frmInstanceNodeViewer.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frmInstanceNodeViewer.setObjectName("frmInstanceNodeViewer")
        self.horizontalLayout_2.addWidget(self.frmInstanceNodeViewer)
        self.frmInstanceNodeBtn = QtWidgets.QFrame(self.frmInstanceNodeFormat)
        self.frmInstanceNodeBtn.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frmInstanceNodeBtn.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmInstanceNodeBtn.setObjectName("frmInstanceNodeBtn")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frmInstanceNodeBtn)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pbInstanceNode = QtWidgets.QPushButton(self.frmInstanceNodeBtn)
        self.pbInstanceNode.setObjectName("pbInstanceNode")
        self.verticalLayout_3.addWidget(self.pbInstanceNode)
        spacerItem4 = QtWidgets.QSpacerItem(20, 19, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.horizontalLayout_2.addWidget(self.frmInstanceNodeBtn)
        self.verticalLayout_7.addWidget(self.frmInstanceNodeFormat)
        self.lblRelFormat = QtWidgets.QLabel(self.pageInstanceFormats)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblRelFormat.setFont(font)
        self.lblRelFormat.setAlignment(QtCore.Qt.AlignCenter)
        self.lblRelFormat.setObjectName("lblRelFormat")
        self.verticalLayout_7.addWidget(self.lblRelFormat)
        self.frmInstanceRelFormat = QtWidgets.QFrame(self.pageInstanceFormats)
        self.frmInstanceRelFormat.setFrameShape(QtWidgets.QFrame.Box)
        self.frmInstanceRelFormat.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frmInstanceRelFormat.setObjectName("frmInstanceRelFormat")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frmInstanceRelFormat)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frmInstanceRelViewer = QtWidgets.QFrame(self.frmInstanceRelFormat)
        self.frmInstanceRelViewer.setMinimumSize(QtCore.QSize(150, 0))
        self.frmInstanceRelViewer.setFrameShape(QtWidgets.QFrame.Box)
        self.frmInstanceRelViewer.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frmInstanceRelViewer.setObjectName("frmInstanceRelViewer")
        self.horizontalLayout_3.addWidget(self.frmInstanceRelViewer)
        self.frmInstanceRelBtn = QtWidgets.QFrame(self.frmInstanceRelFormat)
        self.frmInstanceRelBtn.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frmInstanceRelBtn.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmInstanceRelBtn.setObjectName("frmInstanceRelBtn")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frmInstanceRelBtn)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pbInstanceRel = QtWidgets.QPushButton(self.frmInstanceRelBtn)
        self.pbInstanceRel.setObjectName("pbInstanceRel")
        self.verticalLayout_4.addWidget(self.pbInstanceRel)
        spacerItem5 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem5)
        self.horizontalLayout_3.addWidget(self.frmInstanceRelBtn)
        self.verticalLayout_7.addWidget(self.frmInstanceRelFormat)
        self.stackedWidget.addWidget(self.pageInstanceFormats)
        self.pageTemplateFormats = QtWidgets.QWidget()
        self.pageTemplateFormats.setObjectName("pageTemplateFormats")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.pageTemplateFormats)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lblNodeTemplateFormat = QtWidgets.QLabel(self.pageTemplateFormats)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblNodeTemplateFormat.setFont(font)
        self.lblNodeTemplateFormat.setAlignment(QtCore.Qt.AlignCenter)
        self.lblNodeTemplateFormat.setObjectName("lblNodeTemplateFormat")
        self.verticalLayout_8.addWidget(self.lblNodeTemplateFormat)
        self.frmTemplateNodeFormat = QtWidgets.QFrame(self.pageTemplateFormats)
        self.frmTemplateNodeFormat.setFrameShape(QtWidgets.QFrame.Box)
        self.frmTemplateNodeFormat.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frmTemplateNodeFormat.setObjectName("frmTemplateNodeFormat")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frmTemplateNodeFormat)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frmTemplateNodeViewer = QtWidgets.QFrame(self.frmTemplateNodeFormat)
        self.frmTemplateNodeViewer.setMinimumSize(QtCore.QSize(150, 0))
        self.frmTemplateNodeViewer.setFrameShape(QtWidgets.QFrame.Box)
        self.frmTemplateNodeViewer.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frmTemplateNodeViewer.setObjectName("frmTemplateNodeViewer")
        self.horizontalLayout_4.addWidget(self.frmTemplateNodeViewer)
        self.frmInstanceNodeBtn_2 = QtWidgets.QFrame(self.frmTemplateNodeFormat)
        self.frmInstanceNodeBtn_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frmInstanceNodeBtn_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmInstanceNodeBtn_2.setObjectName("frmInstanceNodeBtn_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frmInstanceNodeBtn_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pbTemplateNode = QtWidgets.QPushButton(self.frmInstanceNodeBtn_2)
        self.pbTemplateNode.setObjectName("pbTemplateNode")
        self.verticalLayout_5.addWidget(self.pbTemplateNode)
        spacerItem6 = QtWidgets.QSpacerItem(20, 19, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem6)
        self.horizontalLayout_4.addWidget(self.frmInstanceNodeBtn_2)
        self.verticalLayout_8.addWidget(self.frmTemplateNodeFormat)
        self.lblRelTemplateFormat = QtWidgets.QLabel(self.pageTemplateFormats)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblRelTemplateFormat.setFont(font)
        self.lblRelTemplateFormat.setAlignment(QtCore.Qt.AlignCenter)
        self.lblRelTemplateFormat.setObjectName("lblRelTemplateFormat")
        self.verticalLayout_8.addWidget(self.lblRelTemplateFormat)
        self.frmRelTemplateFormat = QtWidgets.QFrame(self.pageTemplateFormats)
        self.frmRelTemplateFormat.setFrameShape(QtWidgets.QFrame.Box)
        self.frmRelTemplateFormat.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frmRelTemplateFormat.setObjectName("frmRelTemplateFormat")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frmRelTemplateFormat)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frmRelTemplateViewer = QtWidgets.QFrame(self.frmRelTemplateFormat)
        self.frmRelTemplateViewer.setMinimumSize(QtCore.QSize(150, 0))
        self.frmRelTemplateViewer.setFrameShape(QtWidgets.QFrame.Box)
        self.frmRelTemplateViewer.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frmRelTemplateViewer.setObjectName("frmRelTemplateViewer")
        self.horizontalLayout_5.addWidget(self.frmRelTemplateViewer)
        self.frmInstanceRelBtn_2 = QtWidgets.QFrame(self.frmRelTemplateFormat)
        self.frmInstanceRelBtn_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frmInstanceRelBtn_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmInstanceRelBtn_2.setObjectName("frmInstanceRelBtn_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frmInstanceRelBtn_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pbRelTemplate = QtWidgets.QPushButton(self.frmInstanceRelBtn_2)
        self.pbRelTemplate.setObjectName("pbRelTemplate")
        self.verticalLayout_6.addWidget(self.pbRelTemplate)
        spacerItem7 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem7)
        self.horizontalLayout_5.addWidget(self.frmInstanceRelBtn_2)
        self.verticalLayout_8.addWidget(self.frmRelTemplateFormat)
        self.stackedWidget.addWidget(self.pageTemplateFormats)
        self.TemplateDiagram = QtWidgets.QWidget()
        self.TemplateDiagram.setObjectName("TemplateDiagram")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.TemplateDiagram)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.grpRelType = QtWidgets.QGroupBox(self.TemplateDiagram)
        self.grpRelType.setObjectName("grpRelType")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.grpRelType)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.rbElbow = QtWidgets.QRadioButton(self.grpRelType)
        self.rbElbow.setObjectName("rbElbow")
        self.gridLayout_4.addWidget(self.rbElbow, 0, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(229, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem8, 0, 1, 1, 2)
        self.rbStraight = QtWidgets.QRadioButton(self.grpRelType)
        self.rbStraight.setObjectName("rbStraight")
        self.gridLayout_4.addWidget(self.rbStraight, 1, 0, 1, 2)
        spacerItem9 = QtWidgets.QSpacerItem(202, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem9, 1, 2, 1, 1)
        self.gridLayout_5.addWidget(self.grpRelType, 0, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 190, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem10, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.TemplateDiagram)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.gridLayout_8.addWidget(self.frame, 1, 0, 1, 2)
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setObjectName("hboxlayout")
        spacerItem11 = QtWidgets.QSpacerItem(131, 31, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem11)
        self.okButton = QtWidgets.QPushButton(dlgProjectPreferences)
        self.okButton.setObjectName("okButton")
        self.hboxlayout.addWidget(self.okButton)
        self.cancelButton = QtWidgets.QPushButton(dlgProjectPreferences)
        self.cancelButton.setObjectName("cancelButton")
        self.hboxlayout.addWidget(self.cancelButton)
        self.gridLayout_8.addLayout(self.hboxlayout, 2, 0, 1, 2)
        self.lblAuthor.setBuddy(self.txtAuthor)
        self.label_4.setBuddy(self.txtWidth)
        self.label_5.setBuddy(self.txtHeight)

        self.retranslateUi(dlgProjectPreferences)
        self.stackedWidget.setCurrentIndex(0)
        self.okButton.clicked.connect(dlgProjectPreferences.accept)
        self.cancelButton.clicked.connect(dlgProjectPreferences.reject)
        QtCore.QMetaObject.connectSlotsByName(dlgProjectPreferences)
        dlgProjectPreferences.setTabOrder(self.pbPageSettings, self.pbInstanceFormats)
        dlgProjectPreferences.setTabOrder(self.pbInstanceFormats, self.pbTemplateFormats)
        dlgProjectPreferences.setTabOrder(self.pbTemplateFormats, self.cmbPageSize)
        dlgProjectPreferences.setTabOrder(self.cmbPageSize, self.txtWidth)
        dlgProjectPreferences.setTabOrder(self.txtWidth, self.txtHeight)
        dlgProjectPreferences.setTabOrder(self.txtHeight, self.rbPortrait)
        dlgProjectPreferences.setTabOrder(self.rbPortrait, self.rbLandscape)
        dlgProjectPreferences.setTabOrder(self.rbLandscape, self.spinRows)
        dlgProjectPreferences.setTabOrder(self.spinRows, self.spinColumns)
        dlgProjectPreferences.setTabOrder(self.spinColumns, self.pbInstanceNode)
        dlgProjectPreferences.setTabOrder(self.pbInstanceNode, self.pbInstanceRel)
        dlgProjectPreferences.setTabOrder(self.pbInstanceRel, self.pbTemplateNode)
        dlgProjectPreferences.setTabOrder(self.pbTemplateNode, self.pbRelTemplate)
        dlgProjectPreferences.setTabOrder(self.pbRelTemplate, self.okButton)
        dlgProjectPreferences.setTabOrder(self.okButton, self.cancelButton)

    def retranslateUi(self, dlgProjectPreferences):
        _translate = QtCore.QCoreApplication.translate
        dlgProjectPreferences.setWindowTitle(_translate("dlgProjectPreferences", "Project Properties"))
        self.label.setText(_translate("dlgProjectPreferences", "Project Properties"))
        self.pbGeneral.setText(_translate("dlgProjectPreferences", "General"))
        self.pbPageSettings.setText(_translate("dlgProjectPreferences", "Page Settings"))
        self.pbInstanceFormats.setText(_translate("dlgProjectPreferences", "Instance Formats"))
        self.pbTemplateFormats.setText(_translate("dlgProjectPreferences", "Template Formats"))
        self.pbTemplateDiagram.setText(_translate("dlgProjectPreferences", "Template Diagram"))
        self.lblGeneral.setText(_translate("dlgProjectPreferences", "General Settings"))
        self.lblAuthor.setText(_translate("dlgProjectPreferences", "Author:"))
        self.lblDesc.setText(_translate("dlgProjectPreferences", "Description:"))
        self.lblNodeTemplateFormat_2.setText(_translate("dlgProjectPreferences", "Diagram Page Settings"))
        self.groupBox.setTitle(_translate("dlgProjectPreferences", "Page Size"))
        self.label_4.setText(_translate("dlgProjectPreferences", "Width:"))
        self.label_5.setText(_translate("dlgProjectPreferences", "Height:"))
        self.grpOrientation.setTitle(_translate("dlgProjectPreferences", "Orientation"))
        self.rbPortrait.setText(_translate("dlgProjectPreferences", "Portrait"))
        self.rbLandscape.setText(_translate("dlgProjectPreferences", "LandScape"))
        self.groupBox_2.setTitle(_translate("dlgProjectPreferences", "Page Grid"))
        self.label_6.setText(_translate("dlgProjectPreferences", "Number of rows:"))
        self.label_7.setText(_translate("dlgProjectPreferences", "Number of columns:"))
        self.lblNodeFormat.setText(_translate("dlgProjectPreferences", "Instance Node Default Format"))
        self.pbInstanceNode.setText(_translate("dlgProjectPreferences", "Edit Format..."))
        self.lblRelFormat.setText(_translate("dlgProjectPreferences", "Instance Relationship Default Format"))
        self.pbInstanceRel.setText(_translate("dlgProjectPreferences", "Edit Format..."))
        self.lblNodeTemplateFormat.setText(_translate("dlgProjectPreferences", "Node Template Default Format"))
        self.pbTemplateNode.setText(_translate("dlgProjectPreferences", "Edit Format..."))
        self.lblRelTemplateFormat.setText(_translate("dlgProjectPreferences", "Relationship Template Default Format"))
        self.pbRelTemplate.setText(_translate("dlgProjectPreferences", "Edit Format..."))
        self.grpRelType.setTitle(_translate("dlgProjectPreferences", "Relationship Line Type"))
        self.rbElbow.setText(_translate("dlgProjectPreferences", "Elbows"))
        self.rbStraight.setText(_translate("dlgProjectPreferences", "Straight Line"))
        self.okButton.setText(_translate("dlgProjectPreferences", "&OK"))
        self.cancelButton.setText(_translate("dlgProjectPreferences", "&Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlgProjectPreferences = QtWidgets.QDialog()
    ui = Ui_dlgProjectPreferences()
    ui.setupUi(dlgProjectPreferences)
    dlgProjectPreferences.show()
    sys.exit(app.exec_())
