# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Jsing\OneDrive\Documents\DEV_LAPTOP_LOCAL_REPO\NODEERA\forms\PageSetupDlg.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlgPageSetup(object):
    def setupUi(self, dlgPageSetup):
        dlgPageSetup.setObjectName("dlgPageSetup")
        dlgPageSetup.resize(362, 346)
        dlgPageSetup.setSizeGripEnabled(True)
        self.gridLayout_4 = QtWidgets.QGridLayout(dlgPageSetup)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox = QtWidgets.QGroupBox(dlgPageSetup)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cmbPageSize = QtWidgets.QComboBox(self.groupBox)
        self.cmbPageSize.setMinimumSize(QtCore.QSize(111, 0))
        self.cmbPageSize.setObjectName("cmbPageSize")
        self.gridLayout_2.addWidget(self.cmbPageSize, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 1, 1, 1)
        self.txtWidth = QtWidgets.QLineEdit(self.groupBox)
        self.txtWidth.setReadOnly(True)
        self.txtWidth.setObjectName("txtWidth")
        self.gridLayout_2.addWidget(self.txtWidth, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(136, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 1, 1, 1)
        self.txtHeight = QtWidgets.QLineEdit(self.groupBox)
        self.txtHeight.setReadOnly(True)
        self.txtHeight.setObjectName("txtHeight")
        self.gridLayout_2.addWidget(self.txtHeight, 1, 2, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 3)
        self.grpOrientation = QtWidgets.QGroupBox(dlgPageSetup)
        self.grpOrientation.setObjectName("grpOrientation")
        self.gridLayout = QtWidgets.QGridLayout(self.grpOrientation)
        self.gridLayout.setObjectName("gridLayout")
        self.rbPortrait = QtWidgets.QRadioButton(self.grpOrientation)
        self.rbPortrait.setObjectName("rbPortrait")
        self.gridLayout.addWidget(self.rbPortrait, 0, 0, 1, 1)
        self.rbLandscape = QtWidgets.QRadioButton(self.grpOrientation)
        self.rbLandscape.setObjectName("rbLandscape")
        self.gridLayout.addWidget(self.rbLandscape, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.grpOrientation, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(116, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 1, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(dlgPageSetup)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.spinRows = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinRows.setReadOnly(False)
        self.spinRows.setMinimum(1)
        self.spinRows.setMaximum(20)
        self.spinRows.setObjectName("spinRows")
        self.gridLayout_3.addWidget(self.spinRows, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 1)
        self.spinColumns = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinColumns.setMinimum(1)
        self.spinColumns.setMaximum(20)
        self.spinColumns.setObjectName("spinColumns")
        self.gridLayout_3.addWidget(self.spinColumns, 1, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 2, 0, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(115, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 2, 2, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(dlgPageSetup)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_4.addWidget(self.buttonBox, 3, 0, 1, 2)
        self.label.setBuddy(self.txtWidth)
        self.label_2.setBuddy(self.txtHeight)
        self.label_3.setBuddy(self.spinRows)
        self.label_4.setBuddy(self.spinColumns)

        self.retranslateUi(dlgPageSetup)
        QtCore.QMetaObject.connectSlotsByName(dlgPageSetup)
        dlgPageSetup.setTabOrder(self.cmbPageSize, self.txtWidth)
        dlgPageSetup.setTabOrder(self.txtWidth, self.txtHeight)
        dlgPageSetup.setTabOrder(self.txtHeight, self.rbPortrait)
        dlgPageSetup.setTabOrder(self.rbPortrait, self.rbLandscape)
        dlgPageSetup.setTabOrder(self.rbLandscape, self.spinRows)
        dlgPageSetup.setTabOrder(self.spinRows, self.spinColumns)

    def retranslateUi(self, dlgPageSetup):
        _translate = QtCore.QCoreApplication.translate
        dlgPageSetup.setWindowTitle(_translate("dlgPageSetup", "Page Setup"))
        self.groupBox.setTitle(_translate("dlgPageSetup", "Page Size"))
        self.label.setText(_translate("dlgPageSetup", "Width:"))
        self.label_2.setText(_translate("dlgPageSetup", "Height:"))
        self.grpOrientation.setTitle(_translate("dlgPageSetup", "Orientation"))
        self.rbPortrait.setText(_translate("dlgPageSetup", "Portrait"))
        self.rbLandscape.setText(_translate("dlgPageSetup", "LandScape"))
        self.groupBox_2.setTitle(_translate("dlgPageSetup", "Page Grid"))
        self.label_3.setText(_translate("dlgPageSetup", "Number of rows:"))
        self.label_4.setText(_translate("dlgPageSetup", "Number of columns:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlgPageSetup = QtWidgets.QDialog()
    ui = Ui_dlgPageSetup()
    ui.setupUi(dlgPageSetup)
    dlgPageSetup.show()
    sys.exit(app.exec_())
