# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Jsing\OneDrive\Documents\DEV_LAPTOP_LOCAL_REPO\NODEERA\forms\ReverseEngineerDlg.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlgReverseEngineer(object):
    def setupUi(self, dlgReverseEngineer):
        dlgReverseEngineer.setObjectName("dlgReverseEngineer")
        dlgReverseEngineer.resize(1042, 745)
        dlgReverseEngineer.setSizeGripEnabled(False)
        dlgReverseEngineer.setModal(True)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(dlgReverseEngineer)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lblHeader = QtWidgets.QLabel(dlgReverseEngineer)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeader.setFont(font)
        self.lblHeader.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeader.setObjectName("lblHeader")
        self.verticalLayout_7.addWidget(self.lblHeader)
        self.frmSettings = QtWidgets.QFrame(dlgReverseEngineer)
        self.frmSettings.setFrameShape(QtWidgets.QFrame.Box)
        self.frmSettings.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frmSettings.setObjectName("frmSettings")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frmSettings)
        self.verticalLayout_2.setContentsMargins(-1, 3, -1, 3)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.frmSettings)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lblURL = QtWidgets.QLabel(self.frame_4)
        self.lblURL.setObjectName("lblURL")
        self.gridLayout_2.addWidget(self.lblURL, 0, 0, 1, 1)
        self.editNeoURL = QtWidgets.QLineEdit(self.frame_4)
        self.editNeoURL.setMinimumSize(QtCore.QSize(311, 0))
        self.editNeoURL.setReadOnly(True)
        self.editNeoURL.setObjectName("editNeoURL")
        self.gridLayout_2.addWidget(self.editNeoURL, 0, 1, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(396, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 4, 1, 2)
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 2)
        self.editNumNodes = QtWidgets.QLineEdit(self.frame_4)
        self.editNumNodes.setReadOnly(True)
        self.editNumNodes.setObjectName("editNumNodes")
        self.gridLayout_2.addWidget(self.editNumNodes, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 3, 1, 1)
        self.editNumRels = QtWidgets.QLineEdit(self.frame_4)
        self.editNumRels.setReadOnly(True)
        self.editNumRels.setObjectName("editNumRels")
        self.gridLayout_2.addWidget(self.editNumRels, 1, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(205, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 5, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.frame = QtWidgets.QFrame(self.frmSettings)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setContentsMargins(3, 3, -1, 3)
        self.gridLayout_3.setHorizontalSpacing(3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.spinProcessSize = QtWidgets.QSpinBox(self.frame)
        self.spinProcessSize.setMinimum(1000)
        self.spinProcessSize.setMaximum(10000)
        self.spinProcessSize.setSingleStep(1000)
        self.spinProcessSize.setProperty("value", 10000)
        self.spinProcessSize.setObjectName("spinProcessSize")
        self.gridLayout_3.addWidget(self.spinProcessSize, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(134, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 0, 2, 2, 1)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 3, 1, 1)
        self.txtNodeScanAmt = QtWidgets.QLineEdit(self.frame)
        self.txtNodeScanAmt.setReadOnly(True)
        self.txtNodeScanAmt.setObjectName("txtNodeScanAmt")
        self.gridLayout_3.addWidget(self.txtNodeScanAmt, 0, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 5, 1, 1)
        self.txtNodePercent = QtWidgets.QLineEdit(self.frame)
        self.txtNodePercent.setReadOnly(True)
        self.txtNodePercent.setObjectName("txtNodePercent")
        self.gridLayout_3.addWidget(self.txtNodePercent, 0, 6, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(137, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 0, 7, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 3, 2, 1)
        self.txtRelScanAmt = QtWidgets.QLineEdit(self.frame)
        self.txtRelScanAmt.setReadOnly(True)
        self.txtRelScanAmt.setObjectName("txtRelScanAmt")
        self.gridLayout_3.addWidget(self.txtRelScanAmt, 1, 4, 2, 1)
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 1, 5, 2, 1)
        self.txtRelPercent = QtWidgets.QLineEdit(self.frame)
        self.txtRelPercent.setReadOnly(True)
        self.txtRelPercent.setObjectName("txtRelPercent")
        self.gridLayout_3.addWidget(self.txtRelPercent, 1, 6, 2, 1)
        spacerItem4 = QtWidgets.QSpacerItem(137, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 1, 7, 2, 1)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 2, 0, 1, 1)
        self.spinSkipAmt = QtWidgets.QSpinBox(self.frame)
        self.spinSkipAmt.setMaximum(1000000)
        self.spinSkipAmt.setSingleStep(1000)
        self.spinSkipAmt.setObjectName("spinSkipAmt")
        self.gridLayout_3.addWidget(self.spinSkipAmt, 2, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(134, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 2, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(self.frmSettings)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setLineWidth(0)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setContentsMargins(-1, 3, -1, 3)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cbScanNodes = QtWidgets.QCheckBox(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbScanNodes.sizePolicy().hasHeightForWidth())
        self.cbScanNodes.setSizePolicy(sizePolicy)
        self.cbScanNodes.setMinimumSize(QtCore.QSize(91, 0))
        self.cbScanNodes.setObjectName("cbScanNodes")
        self.horizontalLayout.addWidget(self.cbScanNodes)
        self.cbScanRels = QtWidgets.QCheckBox(self.frame_3)
        self.cbScanRels.setMinimumSize(QtCore.QSize(112, 0))
        self.cbScanRels.setObjectName("cbScanRels")
        self.horizontalLayout.addWidget(self.cbScanRels)
        self.btnStart = QtWidgets.QPushButton(self.frame_3)
        self.btnStart.setObjectName("btnStart")
        self.horizontalLayout.addWidget(self.btnStart)
        self.btnStop = QtWidgets.QPushButton(self.frame_3)
        self.btnStop.setObjectName("btnStop")
        self.horizontalLayout.addWidget(self.btnStop)
        spacerItem6 = QtWidgets.QSpacerItem(398, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.verticalLayout_7.addWidget(self.frmSettings)
        self.tabWidget = QtWidgets.QTabWidget(dlgReverseEngineer)
        self.tabWidget.setObjectName("tabWidget")
        self.tabProgress = QtWidgets.QWidget()
        self.tabProgress.setObjectName("tabProgress")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tabProgress)
        self.verticalLayout_5.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_5.setSpacing(1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.tabProgress)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.editProgress = QtWidgets.QPlainTextEdit(self.groupBox)
        self.editProgress.setReadOnly(True)
        self.editProgress.setObjectName("editProgress")
        self.gridLayout.addWidget(self.editProgress, 0, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.tabWidget.addTab(self.tabProgress, "")
        self.tabResults = QtWidgets.QWidget()
        self.tabResults.setObjectName("tabResults")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tabResults)
        self.verticalLayout_6.setContentsMargins(1, -1, 1, 1)
        self.verticalLayout_6.setSpacing(1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tabResults)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setContentsMargins(-1, 2, -1, 2)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridTemplates = QtWidgets.QTableView(self.groupBox_2)
        self.gridTemplates.setObjectName("gridTemplates")
        self.verticalLayout.addWidget(self.gridTemplates)
        self.frame_6 = QtWidgets.QFrame(self.groupBox_2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_2.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pbUncheck = QtWidgets.QPushButton(self.frame_6)
        self.pbUncheck.setObjectName("pbUncheck")
        self.horizontalLayout_2.addWidget(self.pbUncheck)
        self.pbCheck = QtWidgets.QPushButton(self.frame_6)
        self.pbCheck.setObjectName("pbCheck")
        self.horizontalLayout_2.addWidget(self.pbCheck)
        self.btnSaveTemplates = QtWidgets.QPushButton(self.frame_6)
        self.btnSaveTemplates.setObjectName("btnSaveTemplates")
        self.horizontalLayout_2.addWidget(self.btnSaveTemplates)
        spacerItem7 = QtWidgets.QSpacerItem(693, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.verticalLayout.addWidget(self.frame_6)
        self.verticalLayout_6.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tabResults)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setContentsMargins(-1, 2, -1, 2)
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridTemplates_Rel = QtWidgets.QTableView(self.groupBox_3)
        self.gridTemplates_Rel.setObjectName("gridTemplates_Rel")
        self.verticalLayout_4.addWidget(self.gridTemplates_Rel)
        self.frame_7 = QtWidgets.QFrame(self.groupBox_3)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pbUncheck_Rel = QtWidgets.QPushButton(self.frame_7)
        self.pbUncheck_Rel.setObjectName("pbUncheck_Rel")
        self.horizontalLayout_3.addWidget(self.pbUncheck_Rel)
        self.pbCheck_Rel = QtWidgets.QPushButton(self.frame_7)
        self.pbCheck_Rel.setObjectName("pbCheck_Rel")
        self.horizontalLayout_3.addWidget(self.pbCheck_Rel)
        self.btnSaveTemplates_Rel = QtWidgets.QPushButton(self.frame_7)
        self.btnSaveTemplates_Rel.setObjectName("btnSaveTemplates_Rel")
        self.horizontalLayout_3.addWidget(self.btnSaveTemplates_Rel)
        spacerItem8 = QtWidgets.QSpacerItem(380, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.verticalLayout_4.addWidget(self.frame_7)
        self.verticalLayout_6.addWidget(self.groupBox_3)
        self.tabWidget.addTab(self.tabResults, "")
        self.verticalLayout_7.addWidget(self.tabWidget)
        self.frame_5 = QtWidgets.QFrame(dlgReverseEngineer)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.line = QtWidgets.QFrame(self.frame_5)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.frame_5)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)
        self.verticalLayout_7.addWidget(self.frame_5)
        self.lblURL.setBuddy(self.editNeoURL)
        self.label.setBuddy(self.editNumNodes)
        self.label_2.setBuddy(self.editNumRels)
        self.label_3.setBuddy(self.spinProcessSize)
        self.label_5.setBuddy(self.txtNodeScanAmt)
        self.label_7.setBuddy(self.txtNodePercent)
        self.label_6.setBuddy(self.txtRelScanAmt)
        self.label_8.setBuddy(self.txtRelPercent)
        self.label_4.setBuddy(self.spinSkipAmt)

        self.retranslateUi(dlgReverseEngineer)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(dlgReverseEngineer)
        dlgReverseEngineer.setTabOrder(self.editNeoURL, self.editNumNodes)
        dlgReverseEngineer.setTabOrder(self.editNumNodes, self.editNumRels)
        dlgReverseEngineer.setTabOrder(self.editNumRels, self.spinProcessSize)
        dlgReverseEngineer.setTabOrder(self.spinProcessSize, self.txtNodeScanAmt)
        dlgReverseEngineer.setTabOrder(self.txtNodeScanAmt, self.txtNodePercent)
        dlgReverseEngineer.setTabOrder(self.txtNodePercent, self.spinSkipAmt)
        dlgReverseEngineer.setTabOrder(self.spinSkipAmt, self.txtRelScanAmt)
        dlgReverseEngineer.setTabOrder(self.txtRelScanAmt, self.txtRelPercent)
        dlgReverseEngineer.setTabOrder(self.txtRelPercent, self.cbScanNodes)
        dlgReverseEngineer.setTabOrder(self.cbScanNodes, self.cbScanRels)
        dlgReverseEngineer.setTabOrder(self.cbScanRels, self.btnStart)
        dlgReverseEngineer.setTabOrder(self.btnStart, self.btnStop)
        dlgReverseEngineer.setTabOrder(self.btnStop, self.tabWidget)
        dlgReverseEngineer.setTabOrder(self.tabWidget, self.editProgress)
        dlgReverseEngineer.setTabOrder(self.editProgress, self.gridTemplates)
        dlgReverseEngineer.setTabOrder(self.gridTemplates, self.pbUncheck)
        dlgReverseEngineer.setTabOrder(self.pbUncheck, self.pbCheck)
        dlgReverseEngineer.setTabOrder(self.pbCheck, self.btnSaveTemplates)
        dlgReverseEngineer.setTabOrder(self.btnSaveTemplates, self.gridTemplates_Rel)
        dlgReverseEngineer.setTabOrder(self.gridTemplates_Rel, self.pbUncheck_Rel)
        dlgReverseEngineer.setTabOrder(self.pbUncheck_Rel, self.pbCheck_Rel)
        dlgReverseEngineer.setTabOrder(self.pbCheck_Rel, self.btnSaveTemplates_Rel)

    def retranslateUi(self, dlgReverseEngineer):
        _translate = QtCore.QCoreApplication.translate
        dlgReverseEngineer.setWindowTitle(_translate("dlgReverseEngineer", "Reverse Engineer"))
        self.lblHeader.setText(_translate("dlgReverseEngineer", "Reverse Engineer Node and Relationship Templates"))
        self.lblURL.setText(_translate("dlgReverseEngineer", "Neo4j URL:"))
        self.label.setText(_translate("dlgReverseEngineer", "Number of Nodes:"))
        self.label_2.setText(_translate("dlgReverseEngineer", "Number of Relationships:"))
        self.label_3.setText(_translate("dlgReverseEngineer", "Process Amount:"))
        self.label_5.setText(_translate("dlgReverseEngineer", "Number of Nodes Scanned:"))
        self.label_7.setText(_translate("dlgReverseEngineer", "Percent Of Total:"))
        self.label_6.setText(_translate("dlgReverseEngineer", "Number of Relationships Scanned:"))
        self.label_8.setText(_translate("dlgReverseEngineer", "Percent Of Total:"))
        self.label_4.setText(_translate("dlgReverseEngineer", "Skip Amount:"))
        self.cbScanNodes.setText(_translate("dlgReverseEngineer", "Scan Nodes"))
        self.cbScanRels.setText(_translate("dlgReverseEngineer", "Scan Relationships"))
        self.btnStart.setText(_translate("dlgReverseEngineer", "Start"))
        self.btnStop.setText(_translate("dlgReverseEngineer", "Stop"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabProgress), _translate("dlgReverseEngineer", "Progress"))
        self.groupBox_2.setTitle(_translate("dlgReverseEngineer", "Node Templates"))
        self.pbUncheck.setText(_translate("dlgReverseEngineer", "Uncheck All"))
        self.pbCheck.setText(_translate("dlgReverseEngineer", "Check All"))
        self.btnSaveTemplates.setText(_translate("dlgReverseEngineer", "Save Node Templates"))
        self.groupBox_3.setTitle(_translate("dlgReverseEngineer", "Relationship Templates"))
        self.pbUncheck_Rel.setText(_translate("dlgReverseEngineer", "Uncheck All"))
        self.pbCheck_Rel.setText(_translate("dlgReverseEngineer", "Check All"))
        self.btnSaveTemplates_Rel.setText(_translate("dlgReverseEngineer", "Save Relationship Templates"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabResults), _translate("dlgReverseEngineer", "Results"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlgReverseEngineer = QtWidgets.QDialog()
    ui = Ui_dlgReverseEngineer()
    ui.setupUi(dlgReverseEngineer)
    dlgReverseEngineer.show()
    sys.exit(app.exec_())
