# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Jsing\OneDrive\Documents\DEV_LAPTOP_LOCAL_REPO\NODEERA\forms\SystemPreferenceBox.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SystemPreferenceBox(object):
    def setupUi(self, SystemPreferenceBox):
        SystemPreferenceBox.setObjectName("SystemPreferenceBox")
        SystemPreferenceBox.setWindowModality(QtCore.Qt.ApplicationModal)
        SystemPreferenceBox.resize(840, 600)
        SystemPreferenceBox.setSizeGripEnabled(False)
        self.gridLayout = QtWidgets.QGridLayout(SystemPreferenceBox)
        self.gridLayout.setObjectName("gridLayout")
        self.frameIndex = QtWidgets.QFrame(SystemPreferenceBox)
        self.frameIndex.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameIndex.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameIndex.setObjectName("frameIndex")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frameIndex)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.frameIndex)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pbPageSettings = QtWidgets.QPushButton(self.frameIndex)
        self.pbPageSettings.setObjectName("pbPageSettings")
        self.verticalLayout.addWidget(self.pbPageSettings)
        self.pbInstanceFormats = QtWidgets.QPushButton(self.frameIndex)
        self.pbInstanceFormats.setObjectName("pbInstanceFormats")
        self.verticalLayout.addWidget(self.pbInstanceFormats)
        self.pbTemplateFormats = QtWidgets.QPushButton(self.frameIndex)
        self.pbTemplateFormats.setObjectName("pbTemplateFormats")
        self.verticalLayout.addWidget(self.pbTemplateFormats)
        spacerItem = QtWidgets.QSpacerItem(20, 311, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout.addWidget(self.frameIndex, 0, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(SystemPreferenceBox)
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.stackedWidget.setObjectName("stackedWidget")
        self.pageGeneral = QtWidgets.QWidget()
        self.pageGeneral.setObjectName("pageGeneral")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.pageGeneral)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.frame_2 = QtWidgets.QFrame(self.pageGeneral)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_6.addWidget(self.label_9, 0, 0, 1, 1)
        self.lblLoggingPath = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblLoggingPath.sizePolicy().hasHeightForWidth())
        self.lblLoggingPath.setSizePolicy(sizePolicy)
        self.lblLoggingPath.setMinimumSize(QtCore.QSize(350, 0))
        self.lblLoggingPath.setFrameShape(QtWidgets.QFrame.Box)
        self.lblLoggingPath.setText("")
        self.lblLoggingPath.setObjectName("lblLoggingPath")
        self.gridLayout_6.addWidget(self.lblLoggingPath, 0, 1, 1, 1)
        self.btnLoggingPath = QtWidgets.QToolButton(self.frame_2)
        self.btnLoggingPath.setToolTip("")
        self.btnLoggingPath.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.btnLoggingPath.setObjectName("btnLoggingPath")
        self.gridLayout_6.addWidget(self.btnLoggingPath, 0, 2, 1, 1)
        self.gridLayout_7.addWidget(self.frame_2, 2, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 399, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem1, 3, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.pageGeneral)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 0, 0, 1, 1)
        self.lblProjPath = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblProjPath.sizePolicy().hasHeightForWidth())
        self.lblProjPath.setSizePolicy(sizePolicy)
        self.lblProjPath.setMinimumSize(QtCore.QSize(350, 0))
        self.lblProjPath.setFrameShape(QtWidgets.QFrame.Box)
        self.lblProjPath.setText("")
        self.lblProjPath.setObjectName("lblProjPath")
        self.gridLayout_5.addWidget(self.lblProjPath, 0, 1, 1, 1)
        self.btnProjPath = QtWidgets.QToolButton(self.frame)
        self.btnProjPath.setToolTip("")
        self.btnProjPath.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.btnProjPath.setObjectName("btnProjPath")
        self.gridLayout_5.addWidget(self.btnProjPath, 0, 2, 1, 1)
        self.gridLayout_7.addWidget(self.frame, 1, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.pageGeneral)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(0, 25))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_7.addWidget(self.label_5, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageGeneral)
        self.pagePageSettings = QtWidgets.QWidget()
        self.pagePageSettings.setObjectName("pagePageSettings")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.pagePageSettings)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_10 = QtWidgets.QLabel(self.pagePageSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(0, 25))
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_9.addWidget(self.label_10)
        self.groupBox = QtWidgets.QGroupBox(self.pagePageSettings)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.cmbPageSize = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbPageSize.sizePolicy().hasHeightForWidth())
        self.cmbPageSize.setSizePolicy(sizePolicy)
        self.cmbPageSize.setMinimumSize(QtCore.QSize(175, 0))
        self.cmbPageSize.setObjectName("cmbPageSize")
        self.gridLayout_4.addWidget(self.cmbPageSize, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 1, 1, 1)
        self.txtWidth = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtWidth.sizePolicy().hasHeightForWidth())
        self.txtWidth.setSizePolicy(sizePolicy)
        self.txtWidth.setReadOnly(True)
        self.txtWidth.setObjectName("txtWidth")
        self.gridLayout_4.addWidget(self.txtWidth, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(205, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 0, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(205, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 1, 1, 1, 1)
        self.txtHeight = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtHeight.sizePolicy().hasHeightForWidth())
        self.txtHeight.setSizePolicy(sizePolicy)
        self.txtHeight.setReadOnly(True)
        self.txtHeight.setObjectName("txtHeight")
        self.gridLayout_4.addWidget(self.txtHeight, 1, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(205, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem4, 1, 3, 1, 1)
        self.verticalLayout_9.addWidget(self.groupBox)
        self.grpOrientation = QtWidgets.QGroupBox(self.pagePageSettings)
        self.grpOrientation.setMinimumSize(QtCore.QSize(0, 73))
        self.grpOrientation.setMaximumSize(QtCore.QSize(16777215, 73))
        self.grpOrientation.setObjectName("grpOrientation")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.grpOrientation)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.rbPortrait = QtWidgets.QRadioButton(self.grpOrientation)
        self.rbPortrait.setObjectName("rbPortrait")
        self.gridLayout_2.addWidget(self.rbPortrait, 0, 0, 1, 1)
        self.rbLandscape = QtWidgets.QRadioButton(self.grpOrientation)
        self.rbLandscape.setObjectName("rbLandscape")
        self.gridLayout_2.addWidget(self.rbLandscape, 1, 0, 1, 1)
        self.verticalLayout_9.addWidget(self.grpOrientation)
        self.groupBox_2 = QtWidgets.QGroupBox(self.pagePageSettings)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self.spinRows = QtWidgets.QSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinRows.sizePolicy().hasHeightForWidth())
        self.spinRows.setSizePolicy(sizePolicy)
        self.spinRows.setReadOnly(False)
        self.spinRows.setMinimum(1)
        self.spinRows.setMaximum(20)
        self.spinRows.setObjectName("spinRows")
        self.gridLayout_3.addWidget(self.spinRows, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(530, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 0, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 1, 0, 1, 1)
        self.spinColumns = QtWidgets.QSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinColumns.sizePolicy().hasHeightForWidth())
        self.spinColumns.setSizePolicy(sizePolicy)
        self.spinColumns.setMinimum(1)
        self.spinColumns.setMaximum(20)
        self.spinColumns.setObjectName("spinColumns")
        self.gridLayout_3.addWidget(self.spinColumns, 1, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(530, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 1, 2, 1, 1)
        self.verticalLayout_9.addWidget(self.groupBox_2)
        spacerItem7 = QtWidgets.QSpacerItem(20, 120, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem7)
        self.stackedWidget.addWidget(self.pagePageSettings)
        self.pageInstanceFormats = QtWidgets.QWidget()
        self.pageInstanceFormats.setObjectName("pageInstanceFormats")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.pageInstanceFormats)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.lblNodeFormat = QtWidgets.QLabel(self.pageInstanceFormats)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblNodeFormat.setFont(font)
        self.lblNodeFormat.setAlignment(QtCore.Qt.AlignCenter)
        self.lblNodeFormat.setObjectName("lblNodeFormat")
        self.verticalLayout_12.addWidget(self.lblNodeFormat)
        self.frmInstanceNodeFormat = QtWidgets.QFrame(self.pageInstanceFormats)
        self.frmInstanceNodeFormat.setFrameShape(QtWidgets.QFrame.Box)
        self.frmInstanceNodeFormat.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frmInstanceNodeFormat.setObjectName("frmInstanceNodeFormat")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frmInstanceNodeFormat)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frmInstanceNodeViewer = QtWidgets.QFrame(self.frmInstanceNodeFormat)
        self.frmInstanceNodeViewer.setMinimumSize(QtCore.QSize(150, 0))
        self.frmInstanceNodeViewer.setFrameShape(QtWidgets.QFrame.Box)
        self.frmInstanceNodeViewer.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frmInstanceNodeViewer.setObjectName("frmInstanceNodeViewer")
        self.horizontalLayout_2.addWidget(self.frmInstanceNodeViewer)
        self.frmInstanceNodeBtn = QtWidgets.QFrame(self.frmInstanceNodeFormat)
        self.frmInstanceNodeBtn.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frmInstanceNodeBtn.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmInstanceNodeBtn.setObjectName("frmInstanceNodeBtn")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frmInstanceNodeBtn)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2.addWidget(self.frmInstanceNodeBtn)
        self.frame_3 = QtWidgets.QFrame(self.frmInstanceNodeFormat)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pbInstanceNode = QtWidgets.QPushButton(self.frame_3)
        self.pbInstanceNode.setObjectName("pbInstanceNode")
        self.verticalLayout_7.addWidget(self.pbInstanceNode)
        spacerItem8 = QtWidgets.QSpacerItem(20, 19, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem8)
        self.horizontalLayout_2.addWidget(self.frame_3)
        spacerItem9 = QtWidgets.QSpacerItem(393, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.verticalLayout_12.addWidget(self.frmInstanceNodeFormat)
        self.lblRelFormat = QtWidgets.QLabel(self.pageInstanceFormats)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblRelFormat.setFont(font)
        self.lblRelFormat.setAlignment(QtCore.Qt.AlignCenter)
        self.lblRelFormat.setObjectName("lblRelFormat")
        self.verticalLayout_12.addWidget(self.lblRelFormat)
        self.frmInstanceRelFormat = QtWidgets.QFrame(self.pageInstanceFormats)
        self.frmInstanceRelFormat.setFrameShape(QtWidgets.QFrame.Box)
        self.frmInstanceRelFormat.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frmInstanceRelFormat.setObjectName("frmInstanceRelFormat")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frmInstanceRelFormat)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frmInstanceRelViewer = QtWidgets.QFrame(self.frmInstanceRelFormat)
        self.frmInstanceRelViewer.setMinimumSize(QtCore.QSize(150, 0))
        self.frmInstanceRelViewer.setFrameShape(QtWidgets.QFrame.Box)
        self.frmInstanceRelViewer.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frmInstanceRelViewer.setObjectName("frmInstanceRelViewer")
        self.horizontalLayout_3.addWidget(self.frmInstanceRelViewer)
        self.frmInstanceRelBtn = QtWidgets.QFrame(self.frmInstanceRelFormat)
        self.frmInstanceRelBtn.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frmInstanceRelBtn.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmInstanceRelBtn.setObjectName("frmInstanceRelBtn")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frmInstanceRelBtn)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_4 = QtWidgets.QFrame(self.frmInstanceRelBtn)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.pbInstanceRel = QtWidgets.QPushButton(self.frame_4)
        self.pbInstanceRel.setObjectName("pbInstanceRel")
        self.verticalLayout_11.addWidget(self.pbInstanceRel)
        spacerItem10 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem10)
        self.verticalLayout_4.addWidget(self.frame_4)
        self.horizontalLayout_3.addWidget(self.frmInstanceRelBtn)
        spacerItem11 = QtWidgets.QSpacerItem(399, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem11)
        self.verticalLayout_12.addWidget(self.frmInstanceRelFormat)
        self.stackedWidget.addWidget(self.pageInstanceFormats)
        self.pageTemplateFormats = QtWidgets.QWidget()
        self.pageTemplateFormats.setObjectName("pageTemplateFormats")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.pageTemplateFormats)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lblNodeTemplateFormat = QtWidgets.QLabel(self.pageTemplateFormats)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblNodeTemplateFormat.setFont(font)
        self.lblNodeTemplateFormat.setAlignment(QtCore.Qt.AlignCenter)
        self.lblNodeTemplateFormat.setObjectName("lblNodeTemplateFormat")
        self.verticalLayout_5.addWidget(self.lblNodeTemplateFormat)
        self.frmTemplateNodeFormat = QtWidgets.QFrame(self.pageTemplateFormats)
        self.frmTemplateNodeFormat.setFrameShape(QtWidgets.QFrame.Box)
        self.frmTemplateNodeFormat.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frmTemplateNodeFormat.setObjectName("frmTemplateNodeFormat")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frmTemplateNodeFormat)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frmTemplateNodeViewer = QtWidgets.QFrame(self.frmTemplateNodeFormat)
        self.frmTemplateNodeViewer.setMinimumSize(QtCore.QSize(150, 0))
        self.frmTemplateNodeViewer.setFrameShape(QtWidgets.QFrame.Box)
        self.frmTemplateNodeViewer.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frmTemplateNodeViewer.setObjectName("frmTemplateNodeViewer")
        self.horizontalLayout_4.addWidget(self.frmTemplateNodeViewer)
        self.frame_5 = QtWidgets.QFrame(self.frmTemplateNodeFormat)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pbTemplateNode = QtWidgets.QPushButton(self.frame_5)
        self.pbTemplateNode.setObjectName("pbTemplateNode")
        self.verticalLayout_8.addWidget(self.pbTemplateNode)
        spacerItem12 = QtWidgets.QSpacerItem(20, 19, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem12)
        self.horizontalLayout_4.addWidget(self.frame_5)
        spacerItem13 = QtWidgets.QSpacerItem(417, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem13)
        self.verticalLayout_5.addWidget(self.frmTemplateNodeFormat)
        self.lblRelTemplateFormat = QtWidgets.QLabel(self.pageTemplateFormats)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblRelTemplateFormat.setFont(font)
        self.lblRelTemplateFormat.setAlignment(QtCore.Qt.AlignCenter)
        self.lblRelTemplateFormat.setObjectName("lblRelTemplateFormat")
        self.verticalLayout_5.addWidget(self.lblRelTemplateFormat)
        self.frmRelTemplateFormat = QtWidgets.QFrame(self.pageTemplateFormats)
        self.frmRelTemplateFormat.setFrameShape(QtWidgets.QFrame.Box)
        self.frmRelTemplateFormat.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frmRelTemplateFormat.setObjectName("frmRelTemplateFormat")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frmRelTemplateFormat)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frmRelTemplateViewer = QtWidgets.QFrame(self.frmRelTemplateFormat)
        self.frmRelTemplateViewer.setMinimumSize(QtCore.QSize(150, 0))
        self.frmRelTemplateViewer.setFrameShape(QtWidgets.QFrame.Box)
        self.frmRelTemplateViewer.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frmRelTemplateViewer.setObjectName("frmRelTemplateViewer")
        self.horizontalLayout_5.addWidget(self.frmRelTemplateViewer)
        self.frmInstanceRelBtn_2 = QtWidgets.QFrame(self.frmRelTemplateFormat)
        self.frmInstanceRelBtn_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frmInstanceRelBtn_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmInstanceRelBtn_2.setObjectName("frmInstanceRelBtn_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frmInstanceRelBtn_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_5.addWidget(self.frmInstanceRelBtn_2)
        self.frame_6 = QtWidgets.QFrame(self.frmRelTemplateFormat)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.pbRelTemplate = QtWidgets.QPushButton(self.frame_6)
        self.pbRelTemplate.setObjectName("pbRelTemplate")
        self.verticalLayout_13.addWidget(self.pbRelTemplate)
        spacerItem14 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem14)
        self.horizontalLayout_5.addWidget(self.frame_6)
        spacerItem15 = QtWidgets.QSpacerItem(393, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem15)
        self.verticalLayout_5.addWidget(self.frmRelTemplateFormat)
        self.stackedWidget.addWidget(self.pageTemplateFormats)
        self.gridLayout.addWidget(self.stackedWidget, 0, 1, 1, 1)
        self.btnLayout = QtWidgets.QHBoxLayout()
        self.btnLayout.setContentsMargins(0, 0, 0, 0)
        self.btnLayout.setSpacing(6)
        self.btnLayout.setObjectName("btnLayout")
        spacerItem16 = QtWidgets.QSpacerItem(131, 31, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.btnLayout.addItem(spacerItem16)
        self.btnClose = QtWidgets.QPushButton(SystemPreferenceBox)
        self.btnClose.setObjectName("btnClose")
        self.btnLayout.addWidget(self.btnClose)
        self.gridLayout.addLayout(self.btnLayout, 1, 0, 1, 2)
        self.label_3.setBuddy(self.txtWidth)
        self.label_4.setBuddy(self.txtHeight)
        self.label_7.setBuddy(self.spinRows)
        self.label_8.setBuddy(self.spinColumns)

        self.retranslateUi(SystemPreferenceBox)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SystemPreferenceBox)
        SystemPreferenceBox.setTabOrder(self.pushButton, self.pbPageSettings)
        SystemPreferenceBox.setTabOrder(self.pbPageSettings, self.pbInstanceFormats)
        SystemPreferenceBox.setTabOrder(self.pbInstanceFormats, self.pbTemplateFormats)
        SystemPreferenceBox.setTabOrder(self.pbTemplateFormats, self.btnProjPath)
        SystemPreferenceBox.setTabOrder(self.btnProjPath, self.btnLoggingPath)
        SystemPreferenceBox.setTabOrder(self.btnLoggingPath, self.cmbPageSize)
        SystemPreferenceBox.setTabOrder(self.cmbPageSize, self.txtWidth)
        SystemPreferenceBox.setTabOrder(self.txtWidth, self.txtHeight)
        SystemPreferenceBox.setTabOrder(self.txtHeight, self.rbPortrait)
        SystemPreferenceBox.setTabOrder(self.rbPortrait, self.rbLandscape)
        SystemPreferenceBox.setTabOrder(self.rbLandscape, self.spinRows)
        SystemPreferenceBox.setTabOrder(self.spinRows, self.spinColumns)
        SystemPreferenceBox.setTabOrder(self.spinColumns, self.pbInstanceNode)
        SystemPreferenceBox.setTabOrder(self.pbInstanceNode, self.pbInstanceRel)
        SystemPreferenceBox.setTabOrder(self.pbInstanceRel, self.pbTemplateNode)
        SystemPreferenceBox.setTabOrder(self.pbTemplateNode, self.pbRelTemplate)
        SystemPreferenceBox.setTabOrder(self.pbRelTemplate, self.btnClose)

    def retranslateUi(self, SystemPreferenceBox):
        _translate = QtCore.QCoreApplication.translate
        SystemPreferenceBox.setWindowTitle(_translate("SystemPreferenceBox", "System Preferences"))
        self.pushButton.setText(_translate("SystemPreferenceBox", "General"))
        self.pbPageSettings.setText(_translate("SystemPreferenceBox", "Page Settings"))
        self.pbInstanceFormats.setText(_translate("SystemPreferenceBox", "Instance Formats"))
        self.pbTemplateFormats.setText(_translate("SystemPreferenceBox", "Template Formats"))
        self.label_9.setText(_translate("SystemPreferenceBox", "Logging Path:"))
        self.btnLoggingPath.setText(_translate("SystemPreferenceBox", "Path..."))
        self.label_6.setText(_translate("SystemPreferenceBox", "Project Path:"))
        self.btnProjPath.setText(_translate("SystemPreferenceBox", "Path..."))
        self.label_5.setText(_translate("SystemPreferenceBox", "General Preferences"))
        self.label_10.setText(_translate("SystemPreferenceBox", "Page Settings"))
        self.groupBox.setTitle(_translate("SystemPreferenceBox", "Page Size"))
        self.label_3.setText(_translate("SystemPreferenceBox", "Width:"))
        self.label_4.setText(_translate("SystemPreferenceBox", "Height:"))
        self.grpOrientation.setTitle(_translate("SystemPreferenceBox", "Orientation"))
        self.rbPortrait.setText(_translate("SystemPreferenceBox", "Portrait"))
        self.rbLandscape.setText(_translate("SystemPreferenceBox", "LandScape"))
        self.groupBox_2.setTitle(_translate("SystemPreferenceBox", "Page Grid"))
        self.label_7.setText(_translate("SystemPreferenceBox", "Number of rows:"))
        self.label_8.setText(_translate("SystemPreferenceBox", "Number of columns:"))
        self.lblNodeFormat.setText(_translate("SystemPreferenceBox", "Instance Node Default Format"))
        self.pbInstanceNode.setText(_translate("SystemPreferenceBox", "Edit Format..."))
        self.lblRelFormat.setText(_translate("SystemPreferenceBox", "Instance Relationship Default Format"))
        self.pbInstanceRel.setText(_translate("SystemPreferenceBox", "Edit Format..."))
        self.lblNodeTemplateFormat.setText(_translate("SystemPreferenceBox", "Node Template Default Format"))
        self.pbTemplateNode.setText(_translate("SystemPreferenceBox", "Edit Format..."))
        self.lblRelTemplateFormat.setText(_translate("SystemPreferenceBox", "Relationship Template Default Format"))
        self.pbRelTemplate.setText(_translate("SystemPreferenceBox", "Edit Format..."))
        self.btnClose.setText(_translate("SystemPreferenceBox", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SystemPreferenceBox = QtWidgets.QDialog()
    ui = Ui_SystemPreferenceBox()
    ui.setupUi(SystemPreferenceBox)
    SystemPreferenceBox.show()
    sys.exit(app.exec_())
