# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Jsing\OneDrive\Documents\DEV_LAPTOP_LOCAL_REPO\NODEERA\forms\TRelFormatDlg.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TRelFormatDlg(object):
    def setupUi(self, TRelFormatDlg):
        TRelFormatDlg.setObjectName("TRelFormatDlg")
        TRelFormatDlg.setWindowModality(QtCore.Qt.ApplicationModal)
        TRelFormatDlg.resize(313, 400)
        TRelFormatDlg.setSizeGripEnabled(False)
        TRelFormatDlg.setModal(True)
        self.gridLayout_3 = QtWidgets.QGridLayout(TRelFormatDlg)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.boxLineStyle = QtWidgets.QGroupBox(TRelFormatDlg)
        self.boxLineStyle.setObjectName("boxLineStyle")
        self.gridLayout = QtWidgets.QGridLayout(self.boxLineStyle)
        self.gridLayout.setObjectName("gridLayout")
        self.rbSolidLine = QtWidgets.QRadioButton(self.boxLineStyle)
        self.rbSolidLine.setObjectName("rbSolidLine")
        self.gridLayout.addWidget(self.rbSolidLine, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(43, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.rbDashLine = QtWidgets.QRadioButton(self.boxLineStyle)
        self.rbDashLine.setObjectName("rbDashLine")
        self.gridLayout.addWidget(self.rbDashLine, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(43, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        self.rbDotLine = QtWidgets.QRadioButton(self.boxLineStyle)
        self.rbDotLine.setObjectName("rbDotLine")
        self.gridLayout.addWidget(self.rbDotLine, 2, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(43, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(43, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 3, 2, 2, 1)
        self.rbDashDotLine = QtWidgets.QRadioButton(self.boxLineStyle)
        self.rbDashDotLine.setObjectName("rbDashDotLine")
        self.gridLayout.addWidget(self.rbDashDotLine, 4, 0, 1, 1)
        self.rbDashDotDotLine = QtWidgets.QRadioButton(self.boxLineStyle)
        self.rbDashDotDotLine.setObjectName("rbDashDotDotLine")
        self.gridLayout.addWidget(self.rbDashDotDotLine, 5, 0, 1, 2)
        spacerItem4 = QtWidgets.QSpacerItem(43, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 5, 2, 1, 1)
        self.lblLineWidth = QtWidgets.QLabel(self.boxLineStyle)
        self.lblLineWidth.setObjectName("lblLineWidth")
        self.gridLayout.addWidget(self.lblLineWidth, 6, 0, 1, 1)
        self.spinLineWidth = QtWidgets.QSpinBox(self.boxLineStyle)
        self.spinLineWidth.setMinimum(1)
        self.spinLineWidth.setMaximum(10)
        self.spinLineWidth.setObjectName("spinLineWidth")
        self.gridLayout.addWidget(self.spinLineWidth, 6, 1, 1, 1)
        self.gridLayout_3.addWidget(self.boxLineStyle, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(179, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 0, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(TRelFormatDlg)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frmView = QtWidgets.QFrame(self.groupBox)
        self.frmView.setMinimumSize(QtCore.QSize(88, 88))
        self.frmView.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmView.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frmView.setObjectName("frmView")
        self.gridLayout_2.addWidget(self.frmView, 0, 0, 2, 1)
        self.btnLineColor = QtWidgets.QPushButton(self.groupBox)
        self.btnLineColor.setObjectName("btnLineColor")
        self.gridLayout_2.addWidget(self.btnLineColor, 0, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 58, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem6, 1, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 1, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(97, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem7, 1, 1, 1, 1)
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setObjectName("hboxlayout")
        spacerItem8 = QtWidgets.QSpacerItem(71, 31, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem8)
        self.okButton = QtWidgets.QPushButton(TRelFormatDlg)
        self.okButton.setObjectName("okButton")
        self.hboxlayout.addWidget(self.okButton)
        self.cancelButton = QtWidgets.QPushButton(TRelFormatDlg)
        self.cancelButton.setObjectName("cancelButton")
        self.hboxlayout.addWidget(self.cancelButton)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem9)
        self.gridLayout_3.addLayout(self.hboxlayout, 2, 0, 1, 2)
        self.lblLineWidth.setBuddy(self.spinLineWidth)

        self.retranslateUi(TRelFormatDlg)
        self.okButton.clicked.connect(TRelFormatDlg.accept)
        self.cancelButton.clicked.connect(TRelFormatDlg.reject)
        QtCore.QMetaObject.connectSlotsByName(TRelFormatDlg)
        TRelFormatDlg.setTabOrder(self.rbSolidLine, self.rbDashLine)
        TRelFormatDlg.setTabOrder(self.rbDashLine, self.rbDotLine)
        TRelFormatDlg.setTabOrder(self.rbDotLine, self.rbDashDotLine)
        TRelFormatDlg.setTabOrder(self.rbDashDotLine, self.rbDashDotDotLine)
        TRelFormatDlg.setTabOrder(self.rbDashDotDotLine, self.spinLineWidth)
        TRelFormatDlg.setTabOrder(self.spinLineWidth, self.btnLineColor)
        TRelFormatDlg.setTabOrder(self.btnLineColor, self.okButton)
        TRelFormatDlg.setTabOrder(self.okButton, self.cancelButton)

    def retranslateUi(self, TRelFormatDlg):
        _translate = QtCore.QCoreApplication.translate
        TRelFormatDlg.setWindowTitle(_translate("TRelFormatDlg", "Relationship Template Format Editor"))
        self.boxLineStyle.setTitle(_translate("TRelFormatDlg", "Line Style"))
        self.rbSolidLine.setText(_translate("TRelFormatDlg", "Solid"))
        self.rbDashLine.setText(_translate("TRelFormatDlg", "Dash"))
        self.rbDotLine.setText(_translate("TRelFormatDlg", "Dot"))
        self.rbDashDotLine.setText(_translate("TRelFormatDlg", "Dash Dot"))
        self.rbDashDotDotLine.setText(_translate("TRelFormatDlg", "Dash Dot Dot"))
        self.lblLineWidth.setText(_translate("TRelFormatDlg", "Line Width: "))
        self.groupBox.setTitle(_translate("TRelFormatDlg", "Relationship Template Preview"))
        self.btnLineColor.setText(_translate("TRelFormatDlg", "Line Color"))
        self.okButton.setText(_translate("TRelFormatDlg", "&OK"))
        self.cancelButton.setText(_translate("TRelFormatDlg", "&Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TRelFormatDlg = QtWidgets.QDialog()
    ui = Ui_TRelFormatDlg()
    ui.setupUi(TRelFormatDlg)
    TRelFormatDlg.show()
    sys.exit(app.exec_())
