# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Jsing\OneDrive\Documents\DEV_LAPTOP_LOCAL_REPO\NODEERA\forms\TPPropertyBox.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TPPropertyBox(object):
    def setupUi(self, TPPropertyBox):
        TPPropertyBox.setObjectName("TPPropertyBox")
        TPPropertyBox.setWindowModality(QtCore.Qt.ApplicationModal)
        TPPropertyBox.resize(1130, 716)
        TPPropertyBox.setSizeGripEnabled(True)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(TPPropertyBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_2 = QtWidgets.QFrame(TPPropertyBox)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.txtPathTemplateName = QtWidgets.QLineEdit(self.frame_2)
        self.txtPathTemplateName.setObjectName("txtPathTemplateName")
        self.horizontalLayout.addWidget(self.txtPathTemplateName)
        spacerItem = QtWidgets.QSpacerItem(142, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_5.addWidget(self.frame_2)
        self.frame_6 = QtWidgets.QFrame(TPPropertyBox)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.txtCypher = QtWidgets.QPlainTextEdit(self.frame_6)
        self.txtCypher.setObjectName("txtCypher")
        self.horizontalLayout_3.addWidget(self.txtCypher)
        spacerItem1 = QtWidgets.QSpacerItem(20, 84, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_5.addWidget(self.frame_6)
        self.tabPathTemplate = QtWidgets.QTabWidget(TPPropertyBox)
        self.tabPathTemplate.setObjectName("tabPathTemplate")
        self.tabDefinition = QtWidgets.QWidget()
        self.tabDefinition.setObjectName("tabDefinition")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tabDefinition)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter_2 = QtWidgets.QSplitter(self.tabDefinition)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.frmPathBox = QtWidgets.QFrame(self.splitter)
        self.frmPathBox.setObjectName("frmPathBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frmPathBox)
        self.horizontalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_2.setSpacing(1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.frmPathBox)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tvPath = QtWidgets.QTreeWidget(self.frame_3)
        self.tvPath.setProperty("showDropIndicator", False)
        self.tvPath.setAnimated(True)
        self.tvPath.setObjectName("tvPath")
        self.tvPath.headerItem().setText(0, "1")
        self.verticalLayout_4.addWidget(self.tvPath)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frmPathBox)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnAddNode = QtWidgets.QPushButton(self.frame_4)
        self.btnAddNode.setObjectName("btnAddNode")
        self.verticalLayout_2.addWidget(self.btnAddNode)
        self.btnAddRel = QtWidgets.QPushButton(self.frame_4)
        self.btnAddRel.setObjectName("btnAddRel")
        self.verticalLayout_2.addWidget(self.btnAddRel)
        self.btnRemove = QtWidgets.QPushButton(self.frame_4)
        self.btnRemove.setObjectName("btnRemove")
        self.verticalLayout_2.addWidget(self.btnRemove)
        spacerItem2 = QtWidgets.QSpacerItem(20, 174, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.frame_7 = QtWidgets.QFrame(self.splitter)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lblMetaHeader = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblMetaHeader.setFont(font)
        self.lblMetaHeader.setAlignment(QtCore.Qt.AlignCenter)
        self.lblMetaHeader.setObjectName("lblMetaHeader")
        self.verticalLayout_3.addWidget(self.lblMetaHeader)
        self.gridMetaBox = QtWidgets.QTableView(self.frame_7)
        self.gridMetaBox.setObjectName("gridMetaBox")
        self.gridMetaBox.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.gridMetaBox)
        self.frame_5 = QtWidgets.QFrame(self.splitter_2)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_4.setSpacing(1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridPropBox = QtWidgets.QTableView(self.frame_5)
        self.gridPropBox.setObjectName("gridPropBox")
        self.horizontalLayout_4.addWidget(self.gridPropBox)
        self.frame = QtWidgets.QFrame(self.frame_5)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.btnAdd = QtWidgets.QPushButton(self.frame)
        self.btnAdd.setObjectName("btnAdd")
        self.verticalLayout_6.addWidget(self.btnAdd)
        self.btnRemove_2 = QtWidgets.QPushButton(self.frame)
        self.btnRemove_2.setObjectName("btnRemove_2")
        self.verticalLayout_6.addWidget(self.btnRemove_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 85, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem3)
        self.horizontalLayout_4.addWidget(self.frame)
        self.gridLayout_2.addWidget(self.splitter_2, 0, 0, 1, 1)
        self.tabPathTemplate.addTab(self.tabDefinition, "")
        self.tabDescription = QtWidgets.QWidget()
        self.tabDescription.setObjectName("tabDescription")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tabDescription)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.tabDescription)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.editDescription = QtWidgets.QPlainTextEdit(self.tabDescription)
        self.editDescription.setMaximumSize(QtCore.QSize(16777215, 75))
        self.editDescription.setObjectName("editDescription")
        self.verticalLayout.addWidget(self.editDescription)
        self.label_3 = QtWidgets.QLabel(self.tabDescription)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.brwsrGeneratedDesc = QtWidgets.QTextBrowser(self.tabDescription)
        self.brwsrGeneratedDesc.setObjectName("brwsrGeneratedDesc")
        self.verticalLayout.addWidget(self.brwsrGeneratedDesc)
        self.tabPathTemplate.addTab(self.tabDescription, "")
        self.tabDataGrid = QtWidgets.QWidget()
        self.tabDataGrid.setObjectName("tabDataGrid")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tabDataGrid)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.dataTabFrame = QtWidgets.QFrame(self.tabDataGrid)
        self.dataTabFrame.setObjectName("dataTabFrame")
        self.gridLayout_3.addWidget(self.dataTabFrame, 0, 0, 1, 1)
        self.tabPathTemplate.addTab(self.tabDataGrid, "")
        self.verticalLayout_5.addWidget(self.tabPathTemplate)
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setObjectName("hboxlayout")
        spacerItem4 = QtWidgets.QSpacerItem(71, 31, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem4)
        self.okButton = QtWidgets.QPushButton(TPPropertyBox)
        self.okButton.setObjectName("okButton")
        self.hboxlayout.addWidget(self.okButton)
        self.cancelButton = QtWidgets.QPushButton(TPPropertyBox)
        self.cancelButton.setObjectName("cancelButton")
        self.hboxlayout.addWidget(self.cancelButton)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem5)
        self.verticalLayout_5.addLayout(self.hboxlayout)
        self.label.setBuddy(self.txtPathTemplateName)
        self.label_2.setBuddy(self.editDescription)

        self.retranslateUi(TPPropertyBox)
        self.tabPathTemplate.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TPPropertyBox)
        TPPropertyBox.setTabOrder(self.txtPathTemplateName, self.tabPathTemplate)
        TPPropertyBox.setTabOrder(self.tabPathTemplate, self.editDescription)
        TPPropertyBox.setTabOrder(self.editDescription, self.brwsrGeneratedDesc)
        TPPropertyBox.setTabOrder(self.brwsrGeneratedDesc, self.okButton)
        TPPropertyBox.setTabOrder(self.okButton, self.cancelButton)

    def retranslateUi(self, TPPropertyBox):
        _translate = QtCore.QCoreApplication.translate
        TPPropertyBox.setWindowTitle(_translate("TPPropertyBox", "Path Template"))
        self.label.setText(_translate("TPPropertyBox", "Path Template Name:"))
        self.btnAddNode.setText(_translate("TPPropertyBox", "Add Node"))
        self.btnAddRel.setText(_translate("TPPropertyBox", "Add Relationship"))
        self.btnRemove.setText(_translate("TPPropertyBox", "Remove Item"))
        self.lblMetaHeader.setText(_translate("TPPropertyBox", "Node Definition"))
        self.btnAdd.setText(_translate("TPPropertyBox", "Add"))
        self.btnRemove_2.setText(_translate("TPPropertyBox", "Remove"))
        self.tabPathTemplate.setTabText(self.tabPathTemplate.indexOf(self.tabDefinition), _translate("TPPropertyBox", "Definition"))
        self.label_2.setText(_translate("TPPropertyBox", "Description:"))
        self.label_3.setText(_translate("TPPropertyBox", "Generated Description:"))
        self.tabPathTemplate.setTabText(self.tabPathTemplate.indexOf(self.tabDescription), _translate("TPPropertyBox", "Description"))
        self.tabPathTemplate.setTabText(self.tabPathTemplate.indexOf(self.tabDataGrid), _translate("TPPropertyBox", "Data"))
        self.okButton.setText(_translate("TPPropertyBox", "&OK"))
        self.cancelButton.setText(_translate("TPPropertyBox", "&Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TPPropertyBox = QtWidgets.QDialog()
    ui = Ui_TPPropertyBox()
    ui.setupUi(TPPropertyBox)
    TPPropertyBox.show()
    sys.exit(app.exec_())
