# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Jsing\OneDrive\Documents\DEV_LAPTOP_LOCAL_REPO\NODEERA\forms\TNodeFormatDlg.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TNodeFormatDlg(object):
    def setupUi(self, TNodeFormatDlg):
        TNodeFormatDlg.setObjectName("TNodeFormatDlg")
        TNodeFormatDlg.setWindowModality(QtCore.Qt.ApplicationModal)
        TNodeFormatDlg.resize(387, 501)
        TNodeFormatDlg.setSizeGripEnabled(False)
        TNodeFormatDlg.setModal(True)
        self.gridLayout_2 = QtWidgets.QGridLayout(TNodeFormatDlg)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(TNodeFormatDlg)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.spinHeight = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinHeight.setMinimum(25)
        self.spinHeight.setMaximum(200)
        self.spinHeight.setObjectName("spinHeight")
        self.gridLayout.addWidget(self.spinHeight, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.spinWidth = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinWidth.setMinimum(50)
        self.spinWidth.setMaximum(200)
        self.spinWidth.setProperty("value", 100)
        self.spinWidth.setObjectName("spinWidth")
        self.gridLayout.addWidget(self.spinWidth, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(115, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        self.boxLineStyle = QtWidgets.QGroupBox(TNodeFormatDlg)
        self.boxLineStyle.setObjectName("boxLineStyle")
        self.formLayout = QtWidgets.QFormLayout(self.boxLineStyle)
        self.formLayout.setObjectName("formLayout")
        self.rbNoLine = QtWidgets.QRadioButton(self.boxLineStyle)
        self.rbNoLine.setObjectName("rbNoLine")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.rbNoLine)
        self.rbSolidLine = QtWidgets.QRadioButton(self.boxLineStyle)
        self.rbSolidLine.setObjectName("rbSolidLine")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.rbSolidLine)
        self.rbDashLine = QtWidgets.QRadioButton(self.boxLineStyle)
        self.rbDashLine.setObjectName("rbDashLine")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.rbDashLine)
        self.rbDotLine = QtWidgets.QRadioButton(self.boxLineStyle)
        self.rbDotLine.setObjectName("rbDotLine")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.rbDotLine)
        self.rbDashDotLine = QtWidgets.QRadioButton(self.boxLineStyle)
        self.rbDashDotLine.setObjectName("rbDashDotLine")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.rbDashDotLine)
        self.rbDashDotDotLine = QtWidgets.QRadioButton(self.boxLineStyle)
        self.rbDashDotDotLine.setObjectName("rbDashDotDotLine")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.rbDashDotDotLine)
        self.lblLineWidth = QtWidgets.QLabel(self.boxLineStyle)
        self.lblLineWidth.setObjectName("lblLineWidth")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.lblLineWidth)
        self.spinLineWidth = QtWidgets.QSpinBox(self.boxLineStyle)
        self.spinLineWidth.setMinimum(1)
        self.spinLineWidth.setMaximum(10)
        self.spinLineWidth.setObjectName("spinLineWidth")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.spinLineWidth)
        self.gridLayout_2.addWidget(self.boxLineStyle, 0, 2, 2, 1)
        self.boxFillStyle = QtWidgets.QGroupBox(TNodeFormatDlg)
        self.boxFillStyle.setObjectName("boxFillStyle")
        self.formLayout_2 = QtWidgets.QFormLayout(self.boxFillStyle)
        self.formLayout_2.setObjectName("formLayout_2")
        self.rbNone = QtWidgets.QRadioButton(self.boxFillStyle)
        self.rbNone.setChecked(True)
        self.rbNone.setObjectName("rbNone")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.rbNone)
        self.rbFill = QtWidgets.QRadioButton(self.boxFillStyle)
        self.rbFill.setObjectName("rbFill")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.rbFill)
        self.rbPattern = QtWidgets.QRadioButton(self.boxFillStyle)
        self.rbPattern.setObjectName("rbPattern")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.rbPattern)
        self.spinPattern = QtWidgets.QSpinBox(self.boxFillStyle)
        self.spinPattern.setMinimum(1)
        self.spinPattern.setMaximum(7)
        self.spinPattern.setObjectName("spinPattern")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinPattern)
        self.gridLayout_2.addWidget(self.boxFillStyle, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(115, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(TNodeFormatDlg)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frmView = QtWidgets.QFrame(self.groupBox)
        self.frmView.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmView.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frmView.setObjectName("frmView")
        self.gridLayout_3.addWidget(self.frmView, 0, 0, 3, 1)
        self.btnFillColor = QtWidgets.QPushButton(self.groupBox)
        self.btnFillColor.setObjectName("btnFillColor")
        self.gridLayout_3.addWidget(self.btnFillColor, 0, 1, 1, 1)
        self.btnLineColor = QtWidgets.QPushButton(self.groupBox)
        self.btnLineColor.setObjectName("btnLineColor")
        self.gridLayout_3.addWidget(self.btnLineColor, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 58, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 2, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 2, 0, 1, 3)
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setObjectName("hboxlayout")
        spacerItem3 = QtWidgets.QSpacerItem(71, 31, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem3)
        self.okButton = QtWidgets.QPushButton(TNodeFormatDlg)
        self.okButton.setObjectName("okButton")
        self.hboxlayout.addWidget(self.okButton)
        self.cancelButton = QtWidgets.QPushButton(TNodeFormatDlg)
        self.cancelButton.setObjectName("cancelButton")
        self.hboxlayout.addWidget(self.cancelButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem4)
        self.gridLayout_2.addLayout(self.hboxlayout, 3, 0, 1, 3)
        self.label.setBuddy(self.spinHeight)
        self.label_2.setBuddy(self.spinWidth)
        self.lblLineWidth.setBuddy(self.spinLineWidth)

        self.retranslateUi(TNodeFormatDlg)
        self.okButton.clicked.connect(TNodeFormatDlg.accept)
        self.cancelButton.clicked.connect(TNodeFormatDlg.reject)
        QtCore.QMetaObject.connectSlotsByName(TNodeFormatDlg)
        TNodeFormatDlg.setTabOrder(self.spinHeight, self.spinWidth)
        TNodeFormatDlg.setTabOrder(self.spinWidth, self.rbNone)
        TNodeFormatDlg.setTabOrder(self.rbNone, self.rbFill)
        TNodeFormatDlg.setTabOrder(self.rbFill, self.rbPattern)
        TNodeFormatDlg.setTabOrder(self.rbPattern, self.spinPattern)
        TNodeFormatDlg.setTabOrder(self.spinPattern, self.rbNoLine)
        TNodeFormatDlg.setTabOrder(self.rbNoLine, self.rbSolidLine)
        TNodeFormatDlg.setTabOrder(self.rbSolidLine, self.rbDashLine)
        TNodeFormatDlg.setTabOrder(self.rbDashLine, self.rbDotLine)
        TNodeFormatDlg.setTabOrder(self.rbDotLine, self.rbDashDotLine)
        TNodeFormatDlg.setTabOrder(self.rbDashDotLine, self.rbDashDotDotLine)
        TNodeFormatDlg.setTabOrder(self.rbDashDotDotLine, self.spinLineWidth)
        TNodeFormatDlg.setTabOrder(self.spinLineWidth, self.btnFillColor)
        TNodeFormatDlg.setTabOrder(self.btnFillColor, self.btnLineColor)
        TNodeFormatDlg.setTabOrder(self.btnLineColor, self.okButton)
        TNodeFormatDlg.setTabOrder(self.okButton, self.cancelButton)

    def retranslateUi(self, TNodeFormatDlg):
        _translate = QtCore.QCoreApplication.translate
        TNodeFormatDlg.setWindowTitle(_translate("TNodeFormatDlg", "Node Template Format Editor"))
        self.groupBox_2.setTitle(_translate("TNodeFormatDlg", "Node Size"))
        self.label.setText(_translate("TNodeFormatDlg", "Heght:"))
        self.label_2.setText(_translate("TNodeFormatDlg", "Width:"))
        self.boxLineStyle.setTitle(_translate("TNodeFormatDlg", "Line Style"))
        self.rbNoLine.setText(_translate("TNodeFormatDlg", "No Line"))
        self.rbSolidLine.setText(_translate("TNodeFormatDlg", "Solid"))
        self.rbDashLine.setText(_translate("TNodeFormatDlg", "Dash"))
        self.rbDotLine.setText(_translate("TNodeFormatDlg", "Dot"))
        self.rbDashDotLine.setText(_translate("TNodeFormatDlg", "Dash Dot"))
        self.rbDashDotDotLine.setText(_translate("TNodeFormatDlg", "Dash Dot Dot"))
        self.lblLineWidth.setText(_translate("TNodeFormatDlg", "Line Width: "))
        self.boxFillStyle.setTitle(_translate("TNodeFormatDlg", "Fill Style"))
        self.rbNone.setText(_translate("TNodeFormatDlg", "None"))
        self.rbFill.setText(_translate("TNodeFormatDlg", "Solid"))
        self.rbPattern.setText(_translate("TNodeFormatDlg", "Pattern"))
        self.groupBox.setTitle(_translate("TNodeFormatDlg", "Node Template Preview"))
        self.btnFillColor.setText(_translate("TNodeFormatDlg", "Fill Color"))
        self.btnLineColor.setText(_translate("TNodeFormatDlg", "Line Color"))
        self.okButton.setText(_translate("TNodeFormatDlg", "&OK"))
        self.cancelButton.setText(_translate("TNodeFormatDlg", "&Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TNodeFormatDlg = QtWidgets.QDialog()
    ui = Ui_TNodeFormatDlg()
    ui.setupUi(TNodeFormatDlg)
    TNodeFormatDlg.show()
    sys.exit(app.exec_())
