# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Jsing\OneDrive\Documents\DEV_LAPTOP_LOCAL_REPO\forms\TemplateNodeEditor.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TemplateNodeEditor(object):
    def setupUi(self, TemplateNodeEditor):
        TemplateNodeEditor.setObjectName("TemplateNodeEditor")
        TemplateNodeEditor.setWindowModality(QtCore.Qt.ApplicationModal)
        TemplateNodeEditor.resize(576, 623)
        TemplateNodeEditor.setSizeGripEnabled(True)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(TemplateNodeEditor)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lblHeader = QtWidgets.QLabel(TemplateNodeEditor)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeader.setFont(font)
        self.lblHeader.setObjectName("lblHeader")
        self.verticalLayout_3.addWidget(self.lblHeader)
        self.frame = QtWidgets.QFrame(TemplateNodeEditor)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.boxTemplate = QtWidgets.QGroupBox(self.frame)
        self.boxTemplate.setObjectName("boxTemplate")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.boxTemplate)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblTemplate = QtWidgets.QLabel(self.boxTemplate)
        self.lblTemplate.setObjectName("lblTemplate")
        self.horizontalLayout_3.addWidget(self.lblTemplate)
        self.lblTemplateName = QtWidgets.QLabel(self.boxTemplate)
        self.lblTemplateName.setObjectName("lblTemplateName")
        self.horizontalLayout_3.addWidget(self.lblTemplateName)
        spacerItem = QtWidgets.QSpacerItem(49, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addWidget(self.boxTemplate)
        self.groupBox_Labels = QtWidgets.QGroupBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_Labels.sizePolicy().hasHeightForWidth())
        self.groupBox_Labels.setSizePolicy(sizePolicy)
        self.groupBox_Labels.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_Labels.setToolTip("")
        self.groupBox_Labels.setObjectName("groupBox_Labels")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_Labels)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLabels = QtWidgets.QTableView(self.groupBox_Labels)
        self.gridLabels.setMinimumSize(QtCore.QSize(0, 0))
        self.gridLabels.setMaximumSize(QtCore.QSize(16777215, 100))
        self.gridLabels.setObjectName("gridLabels")
        self.horizontalLayout.addWidget(self.gridLabels)
        self.verticalLayout.addWidget(self.groupBox_Labels)
        self.groupBox_Properties = QtWidgets.QGroupBox(self.frame)
        self.groupBox_Properties.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_Properties.setToolTip("")
        self.groupBox_Properties.setObjectName("groupBox_Properties")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_Properties)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridProps = QtWidgets.QTableView(self.groupBox_Properties)
        self.gridProps.setMinimumSize(QtCore.QSize(0, 0))
        self.gridProps.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridProps.setObjectName("gridProps")
        self.horizontalLayout_4.addWidget(self.gridProps)
        self.verticalLayout.addWidget(self.groupBox_Properties)
        self.gboxIDs_2 = QtWidgets.QGroupBox(self.frame)
        self.gboxIDs_2.setObjectName("gboxIDs_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.gboxIDs_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.gboxIDs_2)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_5.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_5.setSpacing(1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.editNZID_2 = QtWidgets.QLineEdit(self.frame_2)
        self.editNZID_2.setMinimumSize(QtCore.QSize(200, 0))
        self.editNZID_2.setAcceptDrops(False)
        self.editNZID_2.setReadOnly(False)
        self.editNZID_2.setObjectName("editNZID_2")
        self.horizontalLayout_5.addWidget(self.editNZID_2)
        spacerItem1 = QtWidgets.QSpacerItem(248, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.gboxIDs_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_6.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_6.setSpacing(1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.editNeoID_2 = QtWidgets.QLineEdit(self.frame_3)
        self.editNeoID_2.setMinimumSize(QtCore.QSize(100, 0))
        self.editNeoID_2.setReadOnly(False)
        self.editNeoID_2.setObjectName("editNeoID_2")
        self.horizontalLayout_6.addWidget(self.editNeoID_2)
        spacerItem2 = QtWidgets.QSpacerItem(149, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.gboxIDs_2)
        self.verticalLayout_3.addWidget(self.frame)
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setObjectName("hboxlayout")
        spacerItem3 = QtWidgets.QSpacerItem(71, 31, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem3)
        self.okButton = QtWidgets.QPushButton(TemplateNodeEditor)
        self.okButton.setObjectName("okButton")
        self.hboxlayout.addWidget(self.okButton)
        self.cancelButton = QtWidgets.QPushButton(TemplateNodeEditor)
        self.cancelButton.setObjectName("cancelButton")
        self.hboxlayout.addWidget(self.cancelButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.hboxlayout)
        self.label_3.setBuddy(self.editNZID_2)
        self.label_4.setBuddy(self.editNeoID_2)

        self.retranslateUi(TemplateNodeEditor)
        QtCore.QMetaObject.connectSlotsByName(TemplateNodeEditor)
        TemplateNodeEditor.setTabOrder(self.gridLabels, self.okButton)
        TemplateNodeEditor.setTabOrder(self.okButton, self.cancelButton)

    def retranslateUi(self, TemplateNodeEditor):
        _translate = QtCore.QCoreApplication.translate
        TemplateNodeEditor.setWindowTitle(_translate("TemplateNodeEditor", "Template Node Editor"))
        self.lblHeader.setText(_translate("TemplateNodeEditor", "Node Editor"))
        self.boxTemplate.setTitle(_translate("TemplateNodeEditor", "Node Template"))
        self.lblTemplate.setText(_translate("TemplateNodeEditor", "Name:"))
        self.lblTemplateName.setText(_translate("TemplateNodeEditor", "templateName"))
        self.groupBox_Labels.setTitle(_translate("TemplateNodeEditor", "Labels"))
        self.groupBox_Properties.setTitle(_translate("TemplateNodeEditor", "Properties"))
        self.gboxIDs_2.setTitle(_translate("TemplateNodeEditor", "Node IDs"))
        self.label_3.setText(_translate("TemplateNodeEditor", "NodeEra ID:"))
        self.label_4.setText(_translate("TemplateNodeEditor", "Neo4j ID:"))
        self.okButton.setText(_translate("TemplateNodeEditor", "&OK"))
        self.cancelButton.setText(_translate("TemplateNodeEditor", "&Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TemplateNodeEditor = QtWidgets.QDialog()
    ui = Ui_TemplateNodeEditor()
    ui.setupUi(TemplateNodeEditor)
    TemplateNodeEditor.show()
    sys.exit(app.exec_())

